### ISSUE TITLE
Change orientation of z-axis of beams?

### ISSUE THREAD

**Issue by HannaIsabella** [strusoft/femdesign-api#1]
Hi,
I wonder if it's possible to change the orientation of the z-axis of beams using the grasshopper plugin?

For instance, I have columns that need to have mz-moments released, but not my-moments, and additional to that I need to rotate the columns in the global coordinate system, so that the z-axis is not aligned with the global x and y axes. Additionally, there are varying rotations of several columns. Simply having a cross section that is rotated will not work since I have to adapt the end releases correctly in order to transfer loads correctly globally.

I would appreciate if you can tell me how to do this in grasshopper, or implement this feature if it doesn't already exist.

**Comment by andosca** [comment]
Hi!

When setting local y in the beam component local z will be set accordingly as the cross-product of local x and local y. Setting local y will rotate the local coordinate system of the element. This should solve your problem.

![image](https://user-images.githubusercontent.com/52665994/108027873-231deb00-702b-11eb-9b9a-0dbcc49c7672.png)

**Comment by HannaIsabella** [comment]
Look at that, it seems I haven't updated to the latest API! My component library doesn't have this option, I will update to the latest release and see if I can get it to work now. Thank you!
