### ISSUE TITLE
EdgeConnection

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#10]
Review EdgeConnections. Fix constructors and sort out PredefinedTypes logic.

https://github.com/strusoft/femdesign-api/blob/71ef4cce6d0aba528d1d74cefdfcbdfaa780c8ad/src/Shells/ShellEdgeConnection.cs#L54-L61

https://github.com/strusoft/femdesign-api/blob/71ef4cce6d0aba528d1d74cefdfcbdfaa780c8ad/src/Shells/ShellEdgeConnection.cs#L26-L41

**Comment by xRadne** [comment]
Relates to #303 and #302

**Comment by xRadne** [comment]
@andosca Should we consider this done now that I have implemented 302 and 303?
