### ISSUE TITLE
Add public FromStruxml methods to material and section databases in C#.

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#100]
Add public FromStruxml methods to material and section databases in C#.

_Originally posted by @andosca in https://github.com/strusoft/femdesign-api/issues/93#issuecomment-919013726_

**Comment by xRadne** [comment]
`MaterialDatabase.DeserializeStruxml(string filePath)` and `SectionDatabase.DeserializeStruxml(string filePath)` already exists i just found out
