### ISSUE TITLE
implement excitation force settings

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#1001]
https://strusoft.fogbugz.com/f/cases/132987

```xml
      <thexforce
        nres = "5"
        tcend = "20.0"

        method = "0"

        alpha = "0.000"
        beta = "0.000"
        ksi = "5.0"
      />
```

- [x] Create new class
- [x] Update Analysis.cs (properties, constructor, add new analysis methods)
- [x] Create GH component
- [x] Update Analysis.Define GH component
- [x] Test GH objects
- [x] Close case: #988 
- [ ] #1018

**Comment by lorinczandrea** [comment]
- [ ] Create new class
- [ ] Update Analysis.cs (properties, constructor, add new analysis methods)
- [ ] Create GH component
- [ ] Update Analysis.Define GH component
- [ ] Test GH objects
