### ISSUE TITLE
14673 - Deserialize model with composite section throws exception

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#103]
`14673`

---

https://github.com/strusoft/femdesign-api/blob/a8f9a8a07ce4287bd541817512f2461c2613af13/FemDesign.Core/Model/Model.cs#L2266-L2289

**Comment by xRadne** [comment]
Currently users can't deserialize models with composite sections.

**Comment by JRiad** [comment]
We have had a request again today for this (from Viktors Magone). Would be good if we can implement this when we get the chance

**Comment by xRadne** [comment]
@andosca I'm not sure what the issue is or how to fix it? What needs to be done here for complex sections to work?

**Comment by andosca** [comment]
@JRiad 
This is in pipeline already. Will be released in a service release after 20.2.0 is finished. 

@xRadne 
Issue is that composite section definiiton is missing. 

Section on `bar_part`
https://github.com/strusoft/femdesign-api/blob/16b5e642c1fefccc86b2685b2b1d40030e88cee7/FD%2020.00.004%20strusoft.xsd#L1321-L1327

Library items, `composites`
https://github.com/strusoft/femdesign-api/blob/16b5e642c1fefccc86b2685b2b1d40030e88cee7/FD%2020.00.004%20strusoft.xsd#L5710-L5717

**Comment by andosca** [comment]
Problem with composite_section on bar_part serialised to empty guid for beams without composite_section as guid is not nullable.

**Comment by andosca** [comment]
New branch: https://github.com/strusoft/femdesign-api/tree/103-composite-section

**Comment by Marco-Pellegrino** [comment]
Note to self:
Truss element needs to be resolved. Section object to be review

**Comment by andosca** [comment]
Constructor bug in GH

<img width="832" alt="image" src="https://user-images.githubusercontent.com/52665994/163359512-78da8ae7-ea9e-40a0-b273-081d02a48cdd.png">

**Comment by Marco-Pellegrino** [comment]
ah right!
I have forgot that we have two components to create a Column or Bar.
This is something that we should probably discuss and simplify.

Thanks for spotting the bug

**Comment by andosca** [comment]
fixed bug above https://github.com/strusoft/femdesign-api/commit/72a2391c7b99cc8b94ac0c361ba278203db8ac4e

**Comment by andosca** [comment]
# 103 QA

[ x ] Grasshopper
[ x ] Dynamo

## Grasshopper
### Create
[ x ] Constructors

### Read/write

[ x ] index 0
[ x ] index 1
[ x ] index 2 - delta beam is missing. add to global test.
[ x ] index 3
[ x ] index 4
 
## DYN
### Create
[ x ] Constructors

### Read/write
[ x ] index 0
[ x ] index 1
[ x ] index 2 - delta beam is missing. add to global test.
[ x ] index 3
[ x ] index 4

**Comment by andosca** [comment]
merged to 21.1.1
