### ISSUE TITLE
EdgeConnection local axis does not match FEM-Design axis

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#1031]
step to reproduce:

- create a plate with edge connections
- read the edge connections in femdesign api
- compare the local axis

**Comment by lorinczandrea** [comment]
- Axes in .struxml & GH:

![image](https://github.com/strusoft/femdesign-api/assets/107181445/8440f47a-9a4d-46b9-b802-53293a54d80a)


- Axes in FD:

![image](https://github.com/strusoft/femdesign-api/assets/107181445/d8fd22e6-3aa4-4bff-961f-72f7e99d07d0)

**Comment by lorinczandrea** [comment]
Fogbugz ticket:
https://strusoft.fogbugz.com/f/cases/134033/FD-Line-connection-local-axes-does-not-match-with-the-struxml-file
