### ISSUE TITLE
File extension of listed results

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#104]
### What file extension should listed results have?

Listed results are tab-delimited (`	`) and might look like this:

```
Bar elements
Bar	Elem	Node 1	Node 2
Cable.4441.1	1	9915	9836
	2	9836	9778
	3	9778	9724

```

Alternatives: 
- FEM-Design calls these files `.txt` files. 
- These files are usually denoted as `.csv` files. 
"Alternative delimiter-separated files are often given a .csv extension despite the use of a non-comma field separator" [Wikipedia](https://en.wikipedia.org/wiki/Comma-separated_values)
- They might also be denoted `tsv` indicating that they are delimited by a tab character [Wikipedia](https://en.wikipedia.org/wiki/Tab-separated_values)

**Comment by andosca** [comment]
.csv!

**Comment by xRadne** [comment]
Already using `.csv`

**Comment by xRadne** [comment]
Since Microsoft excel is a bit dumb, it is impossible (it seems) to correctly open a file named `.csv` with tab delimiter. However renaming the file to `.tsv` it is opened correctly.
