### ISSUE TITLE
Shell model features

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#1053]
Is it possible through the API?

![attachment](https://github.com/strusoft/femdesign-api/assets/53620289/476e2bcc-4450-4545-8aa2-0b4a07dbb2eb)

Struxml has the attribute but I do not know if it is currently working.
Let's do a little test and reply to the user.
If the test is successful, let's implement it.

- [x] https://strusoft.freshdesk.com/a/tickets/42111

**Comment by lorinczandrea** [comment]
@Marco-Pellegrino, I've implemented the feature. Please have a look and if you are happy, I can merge and close the case.

**Comment by lorinczandrea** [comment]
![bar-shell](https://github.com/user-attachments/assets/080bf019-1985-49a4-a7ba-15e666e27a85)
