### ISSUE TITLE
Add unit hints to components

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#106]
It would be great to know if thicknesses, sizes etc should be in meters or millimeters. Would it be possible to add hints for that or does it depend on the current settings in FEM Design?

Edit:
### Add hints for the following elements 
- [x] Bars
- [x] Bars.Buckling
- [x] Calculate
- [x] Cover
- [x] Loads
- [x] Materials
- [x] Model
- [x] Modelling Tools
- [x] Ptc
- [x] Reinforcement
- [x] Support
- [x] Releases
- [x] Sections
- [x] Shells
- [x] Structure
- [x] Deconstruct

### Extra
- Double check all units that are already there. The ones I have already added might be wrong 😋

**Comment by andosca** [comment]
Measurements are in meters and angles are in radians in the XML-schema. Maybe there are some exceptions to this. This is indepedendent of user settings in FD.

We could add hints or specify this in an "about" component, #94.

**Comment by JRiad** [comment]
Explicit hint on every component, then you have the information when you need it. For example, when I create a slab and hover over thickness, I would like to see "mm" or "m"

**Comment by xRadne** [comment]
While creating the examples you may also add units in the input hints of the grasshopper components

**Comment by samnyb** [comment]
What format would you like it to be? Something like `[mm]`, or `unit: mm`, or something else?

Would you like me to add it to outputs as well, if appropriate?

Is it acceptable to only add unit to inputs where units are relevant, or would you like me to add blank (`[-]`) units to inputs without clear unit as well?

**Comment by andosca** [comment]
`[unit]` and leave blank if no unit.

**Comment by xRadne** [comment]
I suggest you start with adding unit hints to Loads and Support to begin with. These are of course very well used

**Comment by xRadne** [comment]
I just found the following:
- [ ] Releases.Motion.Define and Releases.Rotation.Define got the wrong units
![image](https://user-images.githubusercontent.com/32938476/163134996-17841019-3de5-4e42-a381-1c6dd8cc2ee3.png)
![image](https://user-images.githubusercontent.com/32938476/163135095-e696df3f-d83e-4bb7-a56a-5a54a11ab250.png)

**Comment by xRadne** [comment]
@andosca, Samuel have added unit hints to Load and Support components in grasshopper. We probably want more unit hints to Elements etc. but this is a good start and I think we should get this in the next release as well. Do you agree?

**Comment by andosca** [comment]
We can put it in 21.2.0
