### ISSUE TITLE
Make Cover parameter optional

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#107]
![bild](https://user-images.githubusercontent.com/52665994/133748665-f335f96e-9f99-48a0-86e9-47cdd96ceedc.png)

This is relevant for:

- Grasshopper
- Dynamo
- Core

Also see #98

**Comment by andosca** [comment]
The prefered solution would be to make the `_cover` field on the object nullable.

This is not necessarily straight forward though with serialization/deserializtion of XML.

**Comment by Marco-Pellegrino** [comment]
According to the schema the value is set to `0.02`

```xml
<xs:element name = "straight">
  <xs:complexType>
     <xs:attribute name="direction" type="direction_type"  use="required" />
     <xs:attribute name="space"     type="positive_double" use="required" />
     <xs:attribute name="face"      type="sf_rc_face"      use="optional" /> <!-- It needs for dual layer and NOT needs for single layer reinforcements! -->
     <xs:attribute name="cover"     type="positive_double" default="0.02" />
     <xs:anyAttribute processContents="skip"/>
  </xs:complexType>
</xs:element>
```

**Comment by Marco-Pellegrino** [comment]
Default parameter set to 0.02 to Gh and C#
