### ISSUE TITLE
Link does not work in Docs

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#1087]
Link doesn't work in docs:

![image](https://github.com/user-attachments/assets/ac1502b8-76f9-45a6-b070-2afd5f7ef601)

https://femdesign-api-docs.onstrusoft.com/docs/grasshopper/basics/livelink#global-calculation-configurations---globalcfg-file

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
