### ISSUE TITLE
Read results from str file with results

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#109]
![image](https://user-images.githubusercontent.com/32938476/133765736-3e93bef1-618f-4454-800f-acc85f3c86e4.png)

This will fix #20 as well (Method for the user to read an .str file "directly" in C#)

**Comment by xRadne** [comment]
Should this be **a separate component** or should it **replace the `Model.ReadStr`** component?

- I'm tilted towards a new component since that allows us to try it out and change it without breaking the old ReadStr component. 
- The downside is that introducing a new component (to our API with already a lot of components) increases the complexity. The two components are similar. If the suggested component in the comment above gets no input on resultTypes we could make it behave as ReadStr does when it is provided with no `bscPath`s. 

![image](https://user-images.githubusercontent.com/32938476/149161423-f153c052-0c7e-4e65-ac84-762c2e9d1582.png)

**Comment by JRiad** [comment]
I think it should be the same component. I don't think two separate "ReadStr" components makes sense from a user perspective even if I understand the practical advantages. I think it sounds good that it reads only model if no bsc files are provided

**Comment by andosca** [comment]
I don't have a strong opinion about this. 😌

**Comment by xRadne** [comment]
Ok! 😎

I will mark the current `Model.ReadStr` as obsolete ("Old" tag in grasshopper) for backwards compatability and create a this new component.

**Comment by xRadne** [comment]
### Dynamo
Should the resultTypes list be a list of `ResultType` enums or of `string`?

#### Enum
![image](https://user-images.githubusercontent.com/32938476/149330461-87f67898-42f0-4368-b95b-a110f0e1fc38.png)

#### String
![image](https://user-images.githubusercontent.com/32938476/149331064-98416c02-c4d9-4579-b6a7-bc6f0bbb3fac.png)

**Comment by andosca** [comment]
Strings are difficult as the user needs to know which strings to use. Enum is also a bit cumbersome. Maybe `Model.ReadStr` input `resultTypes` is `List<SomeEnum>` but there is a `ParseResultType` node that can be used for users who would rather use string.

Alternative if technically possible `resultTypes` is `List<Object>` with assertion that `Object` must be either `SomeEnum` or `string` then parser is used in node if input is `string`.

**Comment by andosca** [comment]
Also a general though on the `Model.ReadStr` component/node. As `bscFilePath` input option is removed the user will be restricted to our predefined result types. We must either have this input as optional or have two `Model.ReadStr` componentes/nodes otherwise we will restrict the user.

**Comment by xRadne** [comment]
Dynamo (just like C#) allow for overload methods. Multiple methods of the same name if the input arguments are of different types. If we use argument `List<ResultType> resultTypes` or `List<object> resultTypes`, we could keep the method using `List<string> bscPath` as well as the new one for compatibility.
