### ISSUE TITLE
Enum. Convert string properties to enums where appropriate

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#11]
Most restricted strings could be converted to enums.

https://github.com/strusoft/femdesign-api/blob/71ef4cce6d0aba528d1d74cefdfcbdfaa780c8ad/src/GenericClasses/RestrictedString.cs

### Used by the user (C#, Dynamo, Grasshopper)
- [x] Country
- [x] LoadCaseType
- [x] LoadCaseDurationType
- [x] LoadCombType
- [x] CmdUserModule
- [x] ForceLoadType
- [x] DirectionType
- [x] SfRcFace
- [x] VerticalAlign
- [x] WireProfileType 
- [x] SteelMadeType
- [x] ~EurocodeType~ _Leaving this as a string property_
- [x] ~EdgeType~ _Might be better to just use different geometry classes instead of having an enum that must correspond to the number of points and angles etc. provided._

### Used internally
Enums **not** intended for users should be set to `internal` to reduce confusion.
- [x] PanelType
- [x] BarBucklingType
- [x] DetachType
- [x] LoadDirType
- [x] SlabType

**Comment by xRadne** [comment]
Note: Converts string values to enums for Grasshopper and Dynamo. This means the deconstruct methods must convert them to back to string values before returning values to the main program.

**Comment by xRadne** [comment]
@andosca Restricted string for `LoadCaseType` includes the following `"seis_max"`, `"deviation"`, `"notional"`. But I have not been able to create these in the FemDesign GUI. Should these have an enum and if so, what do they represent?

**Comment by xRadne** [comment]
Decision to make for dynamo:
Components take a string input argument that gets converted to an enum **or** Dynamo default implementation for enum with combonents for each enum value.

**Comment by andosca** [comment]
> 
> 
> @andosca Restricted string for `LoadCaseType` includes the following `"seis_max"`, `"deviation"`, `"notional"`. But I have not been able to create these in the FemDesign GUI. Should these have an enum and if so, what do they represent?

These load case types are not directly accesibly to the user in the GUI but can be set to load cases generated by macros in, e.g `deviation` and `notional`:

![bild](https://user-images.githubusercontent.com/52665994/129536327-cc567341-a0be-4adc-bcdf-2181cb0e1ab2.png)

**Comment by andosca** [comment]
A struxml-model might contain these load cases so they should be implemented:

https://github.com/strusoft/femdesign-api/blob/1daa2907062f13a66dcf6bb9652ddb7bc51eaacc/FemDesign.Core/Loads/LoadCaseTypeEnum.cs#L16-L19

**Comment by xRadne** [comment]
> 
> 
> > @andosca Restricted string for `LoadCaseType` includes the following `"seis_max"`, `"deviation"`, `"notional"`. But I have not been able to create these in the FemDesign GUI. Should these have an enum and if so, what do they represent?
> 
> These load case types are not directly accesibly to the user in the GUI but can be set to load cases generated by macros in, e.g `deviation` and `notional`:
> 
> ![bild](https://user-images.githubusercontent.com/52665994/129536327-cc567341-a0be-4adc-bcdf-2181cb0e1ab2.png)
