### ISSUE TITLE
Implement "Rigidity Group" for edge connections

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#113]
Not implemented yet, causes error when trying to import a struxml file edited in GH that originally contained rigidity groups

**Comment by Marco-Pellegrino** [comment]
@xRadne Do you have any idea on what is it? 
not sure I follow.
Is it a FemDesign object which is in the schema?
🥲

**Comment by xRadne** [comment]
It has to do with the EdgeConnections and their rigidities. Not sure what the error is.
![image](https://user-images.githubusercontent.com/32938476/182109361-106ab97f-6c35-489e-b805-9f799b45f33c.png)

**Comment by Marco-Pellegrino** [comment]
@JRiad @johannariad 
I couldn't reproduce the bug.
It would be great if you can share a file where the problem occurs
