### ISSUE TITLE
Section of beam rotated 90 degrees when using Bar.Modify

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#114]
![image](https://user-images.githubusercontent.com/89396751/134317072-148e6299-0ba7-46a2-89e8-124edf17447e.png)

**Comment by andosca** [comment]
Can you add the related files to our commont folder so that I can debug?

**Comment by JRiad** [comment]
Sure, find them here: C:\Users\JohannaRiad\StruSoft AB\StruParam - Projects\femdesign-api\Files for debugging

**Comment by andosca** [comment]
Moved to \femdesign-api\Test files\114

**Comment by andosca** [comment]
On which build are you experiencing this?

**Comment by andosca** [comment]
When setting a new curve the `LocalY` of the new curve will overwrite the `LocalY` set on the `Beam`. So when setting a new base geometry for a `Beam` the user needs to specify the `LocalY` to make sure that the orientation remains as expected.

![bild](https://user-images.githubusercontent.com/52665994/134474387-560a9f27-5ce4-41e0-b9ba-d9d1cf0e4972.png)

Problem is that the new curve could have any direction and it is then not possible to save the old orientation.
