### ISSUE TITLE
Problem with guid being repeated

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#115]
Not urgent, it is solved with recomputing or reloading GH-file
![image](https://user-images.githubusercontent.com/89396751/134319414-dde9281c-ac0f-42ba-add7-0d47949535ea.png)

**Comment by andosca** [comment]
Not sure of the context here, but if you the `Loads` were modified from the `FdModel` you need to set `Overwrite` to `True`.

**Comment by JRiad** [comment]
I'm not changing anything, just adding supports and loads. I put the files here:
C:\Users\JohannaRiad\StruSoft AB\StruParam - Projects\femdesign-api\Files for debugging\Guid problem

It works when you open the file, but if you try removing or adding the cables to loads for example you should be able to replicate the error

**Comment by andosca** [comment]
On which build are you experiencing this?

**Comment by JRiad** [comment]
Right now I have the master build installed and get it on that. I think I got it on 20.2.0 as well yesterday

**Comment by andosca** [comment]
Did not clone model causing elements to be added several times on re-run.

**Comment by andosca** [comment]
Fixed on 20.2.0
