### ISSUE TITLE
Add string representation for objects

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#116]
Override `.ToString()`

**Comment by xRadne** [comment]
**Pros:**  
- Provides easier to read/understand objects. Good for objects with a unique identifier. 


**Cons:**  
- Introduces extra work.
- If not done thoughtfully it might instead cause more confusion for the user if objects don't appear as objects usually do

**Comment by samnyb** [comment]
LoadCase and LoadCombinations are hard to visualize in grasshopper/dynamo and might be nice to have a better string representation?

**Comment by Marco-Pellegrino** [comment]
@andosca 
I would like to work on the issue for the next milestone.

It is a small things that really improve the UI.
