### ISSUE TITLE
MassConversionTable

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#118]
MassConversionTable Is missing `ILoadElement` interface and can not be cast when added to model.

https://github.com/strusoft/femdesign-api/blob/e0d8fbcee382e1f1fed9ff7e4ad19f24d79312df/FemDesign.Core/Loads/MassConversionTable.cs#L48

https://github.com/strusoft/femdesign-api/blob/e0d8fbcee382e1f1fed9ff7e4ad19f24d79312df/FemDesign.Core/Model/Model.cs#L758

**Comment by xRadne** [comment]
Done! @andosca
