### ISSUE TITLE
Hide classes in Dynamo heirarchy in Dynamo

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#120]
There are a lot of methods that need to be ignored in dynamo ui.

**Comment by andosca** [comment]
- [ ] Bars.Connectivity.Default
- [ ] Bars.Eccentricity.Default
- [ ] Bars.BucklingType
- [ ] Bars.SteelMadeType
- [ ] Calculate.CmdUserModule
- [ ] Calculate.ListProc
- [ ] Country
- [ ] Dynamo
- [ ] ExtensionMethods
- [ ]

**Comment by xRadne** [comment]
Enums cannot be hidden since they cannot be `partial`.

**Comment by andosca** [comment]
Enums will be kept visible.

**Comment by andosca** [comment]
Everything in Dynamo category will be kept as is for now.

![image](https://user-images.githubusercontent.com/52665994/139829288-eb1e9838-b9b4-4dd9-97ef-3316496a9d3c.png)
