### ISSUE TITLE
Define new Section

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#122]
Add method to define some custom sections. 

At least for C#. But preferably also for dynamo and Grasshopper.

Proposing the following constructors:
- `Cicular(radius, groupName, typeName, sizeName)`
- `CicularHollow(radius, thickness, groupName, typeName, sizeName)`
- `Rectangular(width, height, groupName, typeName, sizeName)`
- `RectangularHollow(width, height, thickness, groupName, typeName, sizeName)`
- `Custom(contour, holes, groupName, typeName, sizeName)`

**Comment by andosca** [comment]
https://github.com/strusoft/femdesign-api/blob/8b575998bc2a0bfc74a3f6c7acadcaaba76d7fb5/FemDesign.Core/Sections/Section.cs#L87-L101
