### ISSUE TITLE
Implement Edge.Length for arc by three points

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#123]
The reason for this case is to enable the length calculation of an arc by three points. However, the correct way to go about this is probably to leave the Edge definition and use it only for serialization/deserialization purposes and create our own definition of curves.

**Comment by xRadne** [comment]
### Solution
Goal is to find centerpoint C. Then the length can be calculated as before.
1. Find plane through the 3 points. We are interested in the normal of the plane.
2. Find midpoints M1, M2.
3. Find normals N1, N2 perpendicular to plane and to Lines $\vec{V_{12}}$ and $\vec{V_{23}}$
4. Find centerpoint at the intersection of the the green lines. (TODO)
![image](https://user-images.githubusercontent.com/32938476/182870044-7eac0b34-9680-4931-b437-5f12bc0a5fb3.png)

**Comment by xRadne** [comment]
One more greed test 🧪✅
