### ISSUE TITLE
Naming consistency

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#129]
I think that the following could make the API more logical, especially for users moving between platforms

- The name of the GH component should be the same as the name of the function in C# when possible (deserialize and deconstruct for example)
- If possible, the naming should be more consistent. For example, it could be deconstruct + construct rather than deconstruct + create
- Rename Model.Create?

**Comment by JRiad** [comment]
**Some more notes**
Shells/slabs/walls/plates are used inconsistently
Hidden or concealed bars?

**Comment by andosca** [comment]
I think we should follow the UI naming for new classes. Please add a note to the class describing the xml-type reflection.


```csharp
/// <summary>
/// concealed_bar_type or whatever it is called
/// </summary>
public partial class HiddenBar
{
}
```

@xRadne  See my comment above. What do you think about this IF we want to generate object structure from xml in the future? When generating an object structure we are stuck with the xml-schema definition.

**Comment by xRadne** [comment]
> @xRadne See my comment above. What do you think about this IF we want to generate object structure from xml-schema in the future? When generating an object structure we are stuck with the xml-schema definition.

These comments could probably be generated automatically yes

**Comment by JRiad** [comment]
I can try to request from Laszlo that the naming should be consistent between FEM Design and struxml. Right now it's "hidden bar" in struxml and "concealed bar" in FEM Design. If they are different I think we should follow the name in the UI, because beginner API users will not necessarily ever open the struxml.

**Comment by andosca** [comment]
> 
> 
> I can try to request from Laszlo that the naming should be consistent between FEM Design and struxml. Right now it's "hidden bar" in struxml and "concealed bar" in FEM Design. If they are different I think we should follow the name in the UI, because beginner API users will not necessarily ever open the struxml.

Have a look at 94173 in fogbugz. I propose that we keep a list of naming changes we want to propose.
