### ISSUE TITLE
Don't break old scripts

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#131]
Find a strategy to not break the old scripts when updating components.

Old grasshopper components could be hidden and the new changes could be done on a newly created component (new GUID) in order not to break old components? But might lead to other problems

**Comment by xRadne** [comment]
The grasshopper way of handling this is to use the grasshopper `[Obsolete]` tag or rename the component with the postfix `_OBSOLETE`

https://discourse.mcneel.com/t/question-custom-components/68643/17?u=michael_pryor

**Comment by andosca** [comment]
@xRadne Great stuff! So basically we need to implement this when we make changes to a component that will break the user graph. 

- Move input/output parameter
- Add input/output parameter
- Remove input/output parameter

Any others?

I think we should add a description of this to some development guidelines in the wiki. What do you think?

**Comment by xRadne** [comment]
Seems about right! 

### The checklist when updating components:
- Mark old component with postfix `OBSOLETE` in class name and file name.
- Hide old component with `public override GH_Exposure Exposure => GH_Exposure.hidden;`
- Create a new Component with a new Guid and the new input/output parameters

**Comment by andosca** [comment]
Draft: https://github.com/strusoft/femdesign-api/wiki/Guidelines
