### ISSUE TITLE
bsc-file

### ISSUE THREAD

**Issue by ShahoRuhani** [strusoft/femdesign-api#143]
How can I create a bsc-file?

**Comment by andosca** [comment]
# Create a bsc-file
To create a bsc-file open the `List...` tool (fig. 1)

###### Figure 1
![bsc1](https://user-images.githubusercontent.com/52665994/141063351-6ec315fd-e34b-4129-9670-857bf5e0f5a5.PNG)

When you open the `List...` tool you will be asked to select the elements that are relevant for tabulating values. When you have entered the `List...` tool select the relevant data to tabulate and press `Add to batch` (fig. 2).

###### Figure 2
![bsc2](https://user-images.githubusercontent.com/52665994/141063460-8422e74d-f403-4bef-b58d-c987efbe93de.PNG)

To save the batch you have just created press `Save batch` and follow the instructions (fig. 3).

###### Figure 3
![bsc3](https://user-images.githubusercontent.com/52665994/141063808-822ea3e9-aab0-4a37-8a75-ccebf1c3ed61.PNG)

## Notes on bsc-files
Bsc-files can be used to batch-export tabulated values using the FEM-Design API.
