### ISSUE TITLE
Panel "type" missing

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#144]
Using the GH component "Add element" to add some other stuff, this attribute disappeared from the panel objects, making the struxml file unable to load
![image](https://user-images.githubusercontent.com/89396751/142198811-970d5f9d-7903-490d-9fd7-63be25f7e727.png)

**Comment by xRadne** [comment]
What branch are you using? 20.2.0?

**Comment by xRadne** [comment]
The problem should be that the PanelType is not set properly. (Reason unknown)
https://github.com/strusoft/femdesign-api/blob/7bfa88f56aa3d5bcc64f37b7b6cdb647e3797419/FemDesign.Core/Shells/Panel.cs#L209-L212

PanelType enum was added for 20.2.0: 
https://github.com/strusoft/femdesign-api/blob/7bfa88f56aa3d5bcc64f37b7b6cdb647e3797419/FemDesign.Core/Shells/PanelTypeEnum.cs#L11-L18

**Comment by JRiad** [comment]
I don't know, is it possible to check from the dll installed in Grasshopper? But I think probably "read-results-grasshopper"-branch
