### ISSUE TITLE
Make modelling in mm possible

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#147]
Request from a client to be able to import models in mm (since the Tekla model is in mm). I think we should wait with this and see if we can get some input on why scaling in GH is a problem. It would be possible for us to create a scaling component, or if Budapest change the struxml to allow different units

**Comment by xRadne** [comment]
This is actually quite a big task (8-40h) **for us** I think. Since **all** our elements needs to be scaled differently.

Currently we don't have any (or very little) geometry operations.

**Comment by andosca** [comment]
For now, will not fix this. There are a lot of caveats with this.
