### ISSUE TITLE
Rhino 7 compatibility

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#148]
Update to Rhino 7 compatibility.

This could cause problems for some of our customers. Maybe we need to do two separate builds.

**Comment by xRadne** [comment]
Upgrading from .Net Framework 4.7.2 to 4.8 might be suffucient. I had to do this another time and I think that made it work for both Rhino 6 and 7. But I might be wrong on this

**Comment by andosca** [comment]
Can't reproduce error posted by customer.

Loading 20.2.0 works fine in Rhino 7.14. 

Updating Grasshopper reference to +7 will force all users to upgrade to Rhino 7. Staying on 6.XX is preferable as it seems to be compatible with Rhino 7 as well.

**Comment by andosca** [comment]
User can't reproduce error on new computer.

**Comment by andosca** [comment]
Will stay on 6.XX reference. No need to update to 7.XX.

This means that the package will be compatible with both Rhino 6 and Rhino 7 (for now).
