### ISSUE TITLE
Generating GUIDs

### ISSUE THREAD

**Issue by ShahoRuhani** [strusoft/femdesign-api#150]
Is it possible to add the guid yourself when scripting in the struxml-file or do I need to use FEM-Design to generate the guid?
The guid looks like it is randomly generated - see attached file. In my model, the same vehicle is modeled along 7 different notional lanes.
![Moving Loads - GUID](https://user-images.githubusercontent.com/93928366/145000801-b82f0088-d8ec-4fa1-b33c-706e1b6a12de.png)

**Comment by xRadne** [comment]
Great question @ShahoRuhani! 

Guid (Globally Unique IDentifier) or UUID (Universally Unique IDentifier) are usually created by a program to keep track of unique objects. 

There are many ways to creata a guid manually:
- Use an online generator (such as https://www.guidgenerator.com/)

**Comment by ShahoRuhani** [comment]
Amazing.
Thanks a lot, @xRadne!
