### ISSUE TITLE
Create type hint for mass conversion component

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#155]
It needs to be clarified that a mass should be added as a load. Alternatively, add a new mass input

**Comment by andosca** [comment]
@JRiad

Where was this identified - in GH?

I'm not sure how to address this. If adding a hint for example - should it be added on the `MassConversionTable` component output or the `AddElements` component input?

Are there any other ways to think about this that would allow the user to identify `MassConversionTable` as a "Load"?

IMO we want to keep input on Model at a minimum so I think we would want to avoid adding a specific input parameter for "Mass".

**Comment by JRiad** [comment]
I think on hover over output on this component would be sufficient
![image](https://user-images.githubusercontent.com/89396751/145554625-61af0622-fb7c-48aa-8c49-fd19b134c7b7.png)

**Comment by xRadne** [comment]
@andosca FYI, currently MassConversionTable can only be added to the input parameter `Load` on the `Model.CreateSimple` component.

**Comment by xRadne** [comment]
@JRiad Could you come up with an intuitive solution for how to create and add mass converisons to the model.

**Comment by andosca** [comment]
96a566ef02ef0243ee96ecece56ae3178822b64d
