### ISSUE TITLE
Make it ok to have FEM Design 21 open instead of 20

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#156]
I think this is the first step to make sure the API is compatible with FD21. I hope this might be a quick fix :)
![image](https://user-images.githubusercontent.com/89396751/146734450-3a909ea2-0f49-45ef-9402-ee3474f2dfde.png)

**Comment by xRadne** [comment]
This is something that we need to discuss further I think. What is the expected behavior? Should new versions of the API require FD21? Is a struxml from FD20 fully compatible with FD21? (I think so, and that would make things easier)

**Comment by andosca** [comment]
As soon as we go to FD21 we can no longer assure that .struxml-files created with our tools are compatible with FD20. If we can't assure this we need to bump the required open process to FD21 as well.

**Comment by JRiad** [comment]
Hmm, okay that makes sense... I thought we could just open up for users to start using the API in FD21 as well, even before having all the functionality in place. So no change to the API, just the possibility to use it as it is without having FD20 installed. But this may be confusing actually

**Comment by andosca** [comment]
Read and write the `deconstruct 20.2.0` serialized from FD21 to .struxml works fine. No errors in FD21.

**Comment by andosca** [comment]
Running `deconstruct 20.2.0` and `analysis 20.2.0` in GH raises no unexpected new errors.
