### ISSUE TITLE
Test no gui option and add to FAQ if positive impression.

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#157]
```c#
ProcessStartInfo processStartInfo = new ProcessStartInfo(processPath)
{
  Arguments = arguments,
  UseShellExecute = false,
  WorkingDirectory = Path.GetDirectoryName(struxmlPath),
  FileName = this.FdPath,
  Verb = "open",
};

processStartInfo.EnvironmentVariables["FD_NOGUI"] = "1";

// start process
Process.Start(processStartInfo);
```

**Comment by andosca** [comment]
@xRadne

**Comment by andosca** [comment]
When running an analysis this option makes sure that the FD window does not pop up. However, as no window pops up the user does not get any information about the progress of their calculation. 

- [ ] Add as option for ReadStr
- [ ] Add as option for Analysis (will override endSession)
- [ ] Add as option for Design (will override endSession)

**Comment by xRadne** [comment]
What happens if the calculations fails with no gui? Does it get stuck forever without any notice?

**Comment by andosca** [comment]
No idea. If you have a good example we could test that. No gui does not necessary mean no gui. There is a window that is active. It just does not behave as normal nor does it pop up.

**Comment by andosca** [comment]
I will move this to backlog. I don't think we should implement it yet as we probably need to figure out any caveats with this.
