### ISSUE TITLE
Start FEM-Design without splash-screen

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#158]
Is it possible to start FEM-Design without splash-screen?

**Comment by andosca** [comment]
Yes. By setting the environment variable ´FD_NOLOGO´ it is possible to suppress the splash screen.

`FD_NOLOGO` can be either `0`or `1`.

One way to set this environment variable is to pass the following command;

`setx FD_NOLOGO 1`

in the windows command prompt. To show the splash screen set the environment variable to 0:

`setx FD_NOLOGO 0`.

**Comment by xRadne** [comment]
If the process is started from C# you might want to set the environment variable for the new process only, using 
`processStartInfo.EnvironmentVariables["FD_NOGUI"] = "1";`
