### ISSUE TITLE
Invalid loads should give Warning and null instead of Error in Grasshopper

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#166]
I think it would be more _Grasshopper-like_ to give a **warning** and return `null` (empty) when the input force is zero.

This goes for point and line forces and moments
![image](https://user-images.githubusercontent.com/32938476/149913063-b5270ceb-ab7a-44c0-94cd-4b60935d6e08.png)

**Comment by andosca** [comment]
1. What problem does this propose to solve for the user? 
2. Will the user expect this behaviour for all components in the package?

**Comment by xRadne** [comment]
> 1. What problem does this propose to solve for the user?

Mapping 1-1. A list of 10 input items will create 10 output items (of which some may be null).
Currently there are no way of knowing from the output what items could not be created (only by manually checking if input vector is 0)

>     2. Will the user expect this behavior for all components in the package?

I think so. This is how grasshopper usually handles these problems. See the _list item_ component for example.
![image](https://user-images.githubusercontent.com/32938476/149933488-44e76570-9dae-4748-a5bd-d545fc4c3a0b.png)

**Comment by xRadne** [comment]
Another example is the nodes with a run node boolean. I think it is weird to give an exception/error when it is the expected behavior. I think this should be a warning too. 

![image](https://user-images.githubusercontent.com/32938476/149939857-7ee3cb72-e58b-47b0-87c4-ec40b419bc3a.png)

**Comment by andosca** [comment]
### 1. What problem does this propose to solve for the user?
Ok. So this makes sense for GH and Dynamo as an exception does not actually break the application. In Dynamo this is already handled in the same way as you describe:

![image](https://user-images.githubusercontent.com/52665994/150331432-13eb3bcb-6d7d-469f-a619-a448aa883e0e.png)

👍 

### 2. Will the user expect this behaviour for all components in the package?
So as the user will expect this behaviour from all components it is important that we make this change everywhere **if** we make it.

Thus we need to implement a try/catch as in [5fec9d8471bfb826ce0b9a297cdbe14bcd003602](https://github.com/strusoft/femdesign-api/commit/5fec9d8471bfb826ce0b9a297cdbe14bcd003602) for all components.
