### ISSUE TITLE
Allow ISO codes as Annex/Country code input?

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#167]
Should we allow users to specify ISO codes?

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/32938476/149933989-b0c9e000-93f9-4ecb-961e-19c2a14fa562.png)

See ISO codes at https://countrycode.org/

**Comment by andosca** [comment]
If we use the above example the user could specify the country code for Sweden with at least two different options:

`SE`, `SWE` 

instead of only:

`SE`

?

**Comment by xRadne** [comment]
Correct!
