### ISSUE TITLE
RunDesign to read resulting model?

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#173]
![image](https://user-images.githubusercontent.com/32938476/150747679-77a316c6-7174-4587-8961-62234ffeef82.png)

Should RunDesign return the model after being analyzed and designed? 

This would simplify working with the resulting reinforcement in grasshopper when using autodesign.

**Comment by andosca** [comment]
Duplicate of https://github.com/strusoft/femdesign-api/issues/174

Technically the other way around but discussion in other issue..
