### ISSUE TITLE
Being able to access model after "Runanalysis" and "Rundesign"

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#174]
Both these nodes have output "hasexited". I have an example where I want to design reinforcement with autodesign, then deconstruct to read what reinforcement was designed. In order to do this, I want to trigger "readstruxml" after "rundesign" is completed. But I can only get the component to return "true" if I choose to enable "endsession". And then "readstruxml" doesn't work because FEM Design isn't open...
![image](https://user-images.githubusercontent.com/89396751/150933127-d5933e32-17ff-4a7f-83f1-32770b8951bd.png)
I think a solution could be if "Runanalysis" and "Rundesign" could output the model as well, or even the struxml path it was saved to. What do you think @xRadne @andosca?

**Comment by xRadne** [comment]
Relates to #173 
I agree that this workflow could be improved!

Not sure yet what option would be the best:
1. Output `FemDesign.Model`
2. Output `struxmlPath`
3. ReadStruxml to have a boolean `RunNode` input

I am leaning towards option 1.

**Comment by JRiad** [comment]
I agree, 1 or 2. I think 3 would not solve the problem, because it seems "hasexited" only becomes true when FEM Design is closed

**Comment by xRadne** [comment]
> It seems "hasexited" only becomes true when FEM Design is closed

True! It should be okay to read a struxml even if it is open in FEM-Design. (But not a .str that is open)

**Comment by andosca** [comment]
Since we want to read the potentially modified model we still need to know if FEM-Design `HasExited` or sniff for changes in the working directory. 

Let's do 1. and 3.

## 1.
Read .struxml saved with design changes after successfull autodesign.

## 3. 
Add boolean (default =  `True`) to ReadStruxml to allow users who want to "ping" the component based upstream actions.

**Comment by andosca** [comment]
![image](https://user-images.githubusercontent.com/52665994/186611694-f189bd11-b666-438c-ac88-e577e253a617.png)
