### ISSUE TITLE
NuGet: Warning about `.NETFramework` in `.NET core` applications

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#180]
Using NuGet package in a .NET Core app give the error:

> Package 'FemDesign.Core 21.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

![image](https://user-images.githubusercontent.com/32938476/151188191-cbf29aa4-db2d-4bcb-acd3-a6288deb4063.png)

**Comment by xRadne** [comment]
Consider also migrating from .NET Framework to .NET Core #91

**Comment by xRadne** [comment]
https://github.com/strusoft/femdesign-api/blob/8387cdb1ee438620727d142bafa231c2d7efd706/FemDesign.Core/FemDesign.Core.nuspec#L17-L19

**Comment by andosca** [comment]
I never really understood what the problem was here or how to solve it.

**Comment by xRadne** [comment]
### So the problem is that we (in #90) tried to add the dependencies for the package like this:
<img width="400px" src="https://user-images.githubusercontent.com/32938476/174239333-cd1d8799-ff34-43a0-a631-70d04f50fce4.png"/>

So I added the following lines to the `.nuspec`:
https://github.com/strusoft/femdesign-api/blob/8387cdb1ee438620727d142bafa231c2d7efd706/FemDesign.Core/FemDesign.Core.nuspec#L17-L19

### But what actually happened (i think) is that we instead limit the "Compatible target framework(s)" without changing the "Dependencies":
<div>
<img width="300px" style="display: inline;" src="https://user-images.githubusercontent.com/32938476/174240075-96dbac82-5e44-42c6-b90d-cfc5285f320a.png"/>
<img width="300px" style="display: inline;" src="https://user-images.githubusercontent.com/32938476/174240418-13725cff-2a8f-4b37-aa68-7840d5c48e66.png"/>
</div>

### What we wanted was something like this (Rhino3dm package):
<div>
<img width="300px" style="display: inline;" src="https://user-images.githubusercontent.com/32938476/174240896-a05440e8-944c-4776-a292-d1118d897c9f.png"/>
<img width="300px" style="display: inline;" src="https://user-images.githubusercontent.com/32938476/174240942-8be0130e-4923-4f2a-8c94-5ee4c18a8994.png"/>
</div>

### I suggest we simply remove the lines in the nuspec
https://github.com/strusoft/femdesign-api/blob/8387cdb1ee438620727d142bafa231c2d7efd706/FemDesign.Core/FemDesign.Core.nuspec#L17-L19

**Comment by Marco-Pellegrino** [comment]
https://docs.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview

@xRadne 
Would it help?
While I was trying to have a look at the differences between the framework I came across that tool

**Comment by xRadne** [comment]
Looks like a very useful tool! We should try it! 

Do you know what the differences between .NET Framework and .NET Core are? Is it even possible to have a grasshopper (and dynamo) plugin i .NET core? :)

**Comment by Marco-Pellegrino** [comment]
I definitely know anything about those topic.
I have just understood that Net Core should help in deploying for different operating system.
Not sure we will get benefit in the short term but probably in the long term.
We should try to use it together.
Last week I have broken my repository 😅

**Comment by xRadne** [comment]
> I definitely know anything about those topic.
> We should try to use it together. Last week I have broken my repository 😅

I don't know much about this either! 😅
So I think we could try it together and if it does not work we should go with the first option instead :) 

> ### I suggest
> Either
> 
> - We simply remove the lines in the .nuspec
>       https://github.com/strusoft/femdesign-api/blob/8387cdb1ee438620727d142bafa231c2d7efd706/FemDesign.Core/FemDesign.Core.nuspec#L17-L19
> 
> - Or we figure out how to do this properly and add support for .NET Core as well as .NET Framework. **FemDesign.Core is compatible with .NET Core!**. This will solve the issue but I don't know how to do it.

**Comment by xRadne** [comment]
Should we move this to the next milestone instead?

**Comment by xRadne** [comment]
https://stackoverflow.com/questions/68874397/net-framework-vs-net-core

It seems like we wont have much benefits from switching framework any longer. `.NET Framework` can be used in the newer versions (`.NET 5`, `.NET 6`).

![image](https://user-images.githubusercontent.com/32938476/175946493-5172fd0e-4633-4791-be74-eb465bc08abd.png)
