### ISSUE TITLE
Handling moving loads and indexed guids

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#181]
Models containing moving loads cannot be deserialized. This has to do with load groups and guids which have a # number at the end 
![image](https://user-images.githubusercontent.com/89396751/151199277-718bea83-e9e9-4fec-a9b1-f423bb9e4333.png)

The following Guid should be changed to an indexed guid class or a string
https://github.com/strusoft/femdesign-api/blob/f587165b693c68b9c30c3e61f9fa8ee94a025a65/FemDesign.Core/Loads/ModelLoadCase.cs#L14-L15

**Comment by xRadne** [comment]
@Marco-Pellegrino I wrote the code to read struxml with moving loads (indexed guid), but I have not merged it to any branch. Do you think we should merge this to 21.4.0? I don't know if this solves the issue you mentioned in the PR https://github.com/strusoft/femdesign-api/pull/489#issuecomment-1261078312

**Comment by Marco-Pellegrino** [comment]
@xRadne 
Great!
It might be the solution we were looking for.
I am going to do a little test and, if successful, I'll merge.
