### ISSUE TITLE
Can't generate more than one reinforcement per bar

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#183]
- [ ] #209

Grasshopper:

- [x] Stirrups
- [x] Longitudinal bars
- [x] AddToBar

Dynamo:

- [x] Stirrups
- [x] Longitudinal bars
- [x] AddToBar

## Struxml example
```xml
<bar_reinforcement guid="4bc58add-8209-49dc-947d-aef3370ccb53" last_change="2022-01-28T12:04:56.000" action="added">
	<base_bar guid="a9bf8743-c04d-45ef-b719-c2c8f977bfbc"></base_bar>
	<wire diameter="0.012" reinforcing_material="99986440-7a9c-4453-b997-9928d3ffa0d1"></wire>
	<stirrups start="0" end="4.26862818667734" distance="0.1">
		<region>
			<contour>
				<edge type="line">
					<point x="-0.074" y="0.124" z="0"></point>
					<point x="0.074" y="0.124" z="0"></point>
					<normal x="0" y="1" z="0"></normal>
				</edge>
				<edge type="line">
					<point x="0.074" y="0.124" z="0"></point>
					<point x="0.074" y="-0.124" z="0"></point>
					<normal x="1" y="0" z="0"></normal>
				</edge>
				<edge type="line">
					<point x="0.074" y="-0.124" z="0"></point>
					<point x="-0.074" y="-0.124" z="0"></point>
					<normal x="0" y="-1" z="0"></normal>
				</edge>
				<edge type="line">
					<point x="-0.074" y="-0.124" z="0"></point>
					<point x="-0.074" y="0.124" z="0"></point>
					<normal x="-1" y="0" z="0"></normal>
				</edge>
			</contour>
		</region>
	</stirrups>
</bar_reinforcement>
<bar_reinforcement guid="9e30aff7-2ff0-426c-b524-d76d85dcd982" last_change="2022-01-28T12:05:01.000" action="added">
	<base_bar guid="a9bf8743-c04d-45ef-b719-c2c8f977bfbc"></base_bar>
	<wire diameter="0.012" reinforcing_material="99986440-7a9c-4453-b997-9928d3ffa0d1"></wire>
	<longitudinal_bar start="0" end="4.26862818667734" auxiliary="false">
		<cross-sectional_position x="-3.19928186714542E-02" y="4.16876122082586E-02"></cross-sectional_position>
		<anchorage start="0.8" end="0.8"></anchorage>
	</longitudinal_bar>
</bar_reinforcement>
```

## Problem
A bar reinforcement can belong to one `bar` only. This is referenced by a `base_bar` guid. In order to construct a bar reinforcement technically a bar is needed. Both for this `base_bar` guid, but also if parametric start and end is used the bar is needed to calculate `start` and `end` distance.

![image](https://user-images.githubusercontent.com/52665994/151545700-f37f8a79-ded4-4633-95da-8ed1914c3979.png)

The best option here would be if the `AddToBar` component, or equivalent method, was not needed. However, this would not make sense as the `Stirrups` or `LongitudinalBar` components, or equivalent methods, would spit out a new bar for each time the method was run - which is not desired. 

Ok. But it is not desired to provide bar twice either; once for `Stirrups` or `LongitudinalBar` and once for `AddToBar`.

## Solutions
One solution would be to skip bar input in `Stirrups` and `LongitudinalBar`. This would create BarReinforcement without `base_bar` guid and with parametric `start` and `end` instead of distance. The `base_bar` and distance would be calculated in the `AddToBar` component, or equivalent method.

**Comment by xRadne** [comment]
Why would you need more than one rebar? Cant you just increase the section area? 🤪

**Comment by andosca** [comment]
Can one reinforcement bar reference different bars (base bar guid)? If so move base bar guid generation to AddReinforcementToBar method.

**Comment by andosca** [comment]
- [ ] Add clone option (to use one rebar on several bars)

**Comment by andosca** [comment]
Tested locally.
