### ISSUE TITLE
Have several versions of the API installed at once

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#188]
It would be nice to have "Fem Design 20" and "Fem Design 21" API installed at the same time in grasshopper. Could we have it as two separate tabs maybe? Should be just compiling them with different tab names I guess? @xRadne @andosca what do you think?

**Comment by xRadne** [comment]
I agree that it is incredibly annoying at the moment. I switch between 20 and 21 a few times every day. I'm thinking about creating an installer (#37) to solve this. Making it easier to switch at least

**Comment by xRadne** [comment]
Another thought is that the info component (#94) could store info of **what version of the API it was created with** and compare to the current installed. 

This would make it easier to find what version was used when creating an old script. This will probably be more important the more users and (major) versions of the API we get.

**Comment by JRiad** [comment]
I don't know the solution but it is annoying for us at the moment, and it definitely is an issue for our customers as well. Sometimes components just don't work and you have no idea why

**Comment by andosca** [comment]
## Intermediate solution for switching between versions
Intermediate solution to solve your problems would simply be to have different `Library folders`in `GrasshopperDeveloperSettings`. If two packages share GUID you will be prompted to pick which one to load. Then you can chose either 20 or 21.

## Separate tabs for libraries
I might be mistaken, but I don't think this would work without breaking old scripts, due to GUID reference issues.

**Comment by andosca** [comment]
> Another thought is that the info component (#94) could store info of **what version of the API it was created with** and compare to the current installed.
> 
> This would make it easier to find what version was used when creating an old script. This will probably be more important the more users and major versions (20, 21...) of the API we get.

Not really sure what you mean. If I would open your script created with 20.0.0, where you dumped an Info component, in 21.0.0 - what should the Info component show?

**Comment by JRiad** [comment]
That's a good workaround @andosca 👍 
![image](https://user-images.githubusercontent.com/89396751/152310334-6854214b-c120-446a-b17e-fef45e3aefad.png)
This feels very acceptable to me, could even be ok for users I think

**Comment by andosca** [comment]
@xRadne Would it be possible to rename the compiled files depending on assembly version info?

https://github.com/strusoft/femdesign-api/blob/f4c09bf61e6a7ce1e4a2069456fe97b1199625a7/FemDesign.Grasshopper/FemDesign.Grasshopper.csproj#L742-L752

https://github.com/strusoft/femdesign-api/blob/f4c09bf61e6a7ce1e4a2069456fe97b1199625a7/FemDesign.Core/Properties/AssemblyInfo.cs#L33-L34

If so, we could actually keep different versions in the same `Library folder`

**Comment by xRadne** [comment]
Don't know. Google gave me nothing.

**Comment by xRadne** [comment]
I don't think it is a good idea to rename the `.dll`s or `.gha`s. A better solution would be to create different folders in the `GrasshopperDeveloperSettings` as Andreas suggested. 
This could be done from an installer (#37).

**Comment by andosca** [comment]
Question resolved. Any development has been moved to #37.
