### ISSUE TITLE
Setup debug for Dynamo and Grasshopper

### ISSUE THREAD

**Issue by johannariad** [strusoft/femdesign-api#194]
It would be nice if it is easier for new users to get started with.
I think for Dynamo it would be best if all the necessary files are placed in a folder, which the user then can point to from any version of Dynamo

**Comment by andosca** [comment]
We could change the destination folder to project build folder.

https://github.com/strusoft/femdesign-api/blob/450150f130c39c27db956e86cd74ff4cd4c9f54f/FemDesign.Dynamo/FemDesign.Dynamo.csproj#L899-L917

@xRadne Would this be ok with you? You set up the post-build script.

**Comment by andosca** [comment]
Implemented.
