### ISSUE TITLE
Analysis from Grasshopper sometimes fails, no reason given

### ISSUE THREAD

**Issue by samnyb** [strusoft/femdesign-api#195]
I tried running the analysis for **Example 2 - Analysing a model** and ran into an issue where the analysis wouldn't run properly with some settings. I don't know if it's intentional or not - say, if it has insufficient data to run a proper analysis - but there's no message to explain what happens, it just fails.

More specifically, when I run the analysis with `calcCase` and `calcComb` it runs properly, but when I run `calcCase`, `calcComb` and `calcGmax` it just opens the model, but runs no analysis.

Running only `calcGmax` alone doesn't work either, so I suppose it's due to something lacking in my script - but I would like to get some sort of message/result telling me why it doesn't work so I can fix it.

**Comment by xRadne** [comment]
Great issue! But a duplicate #176
