### ISSUE TITLE
Refactor the `ResultType` enum

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#196]
The `ResultType` enum. Is unnecessary and only causes confusion. 

Each result class may have a field for the associated ListProc enums instead.

Each result class may have associated default `index`, `restype` and `option` as well.

**Comment by xRadne** [comment]
@Marco-Pellegrino @andosca FYI!

I see that you are working on the results a lot lately. 
I have a suggestion on how to slightly reduce the complexity of the code (from the perspective of a C# user).
Let me know if you think this is good and/or worth it

### Current Result-reader solution
Currently we have an enum `ResultType` where the user selects a type of result to be extracted from a model and then parsed. 

https://github.com/strusoft/femdesign-api/blob/0a08db186bf392b7f960c16ff1568f3519bd2b72/FemDesign.Core/Results/ResultTypeEnum.cs#L16-L21

The user may write something like this:
```C#
var resultTypes = new List<Results.ResultType> { 
  Results.ResultType.BarDisplacement,
  Results.ResultType.EigenFrequencies,
  Results.ResultType.QuantityEstimationConcrete,
};


var (model, results) = Model.ReadStr("path", resultTypes);
var barDisplacements = results.Where(r => r.GetType() == typeof(Results.BarDisplacement)).Cast<Results.BarDisplacement>();
// results is of type IEnumerable<Result.IResult> and can't be used directly
// barDisplacements is of type IEnumerable<Result.BarDisplacement>
```

### Suggestion
- Remove `ResultType` enum.
- Move the `ResultAttribute` class (`[Result(typeof(QuantityEstimationConcrete), ListProc.QuantityEstimationConcrete)]`) **from** the enum, **to** the result class

Make the restult classes look like this instead:
```C#
namespace FemDesign.Results
{
  /// <summary>
  /// FemDesign "Bars, Displacements" result
  /// </summary>

  [Parseable("BarDisplacement")]
  [Result(ListProc.QuantityEstimationConcrete)]
  public class BarDisplacement : IResult
```

### Why?
- Remove the **unnecessary** `ResultType` enum.
- Will help if we want to use **typed** result parser method. 

This is how I would have written it if I were to start over. :)
(End of this novel)

**Comment by andosca** [comment]
@xRadne 

* How would you query the results from the `ReadStr` method?
* Is it stupid to output a `Dictionary<string, IEnumerable<IResult>>` instead of an unsorted IEnumerable<IResult>. I guess you still have to cast, but you don't have to sort.

**Comment by xRadne** [comment]
>     * How would you query the results from the `ReadStr` method?

Currently I use use `text match` to group the results and then use BHoM explode or python component to extract the right fields of the results. A result deconstructor would solve this.

>     * Is it stupid to output a `Dictionary<string, IEnumerable<IResult>>` instead of an unsorted IEnumerable. I guess you still have to cast, but you don't have to sort.

I think this is very good! Should do it!

**Comment by andosca** [comment]
@Marco-Pellegrino Is this still relevant?

**Comment by xRadne** [comment]
This is probably better to do with the other refactoring of the C# classes and constructors in that milestone

**Comment by Marco-Pellegrino** [comment]
yes. I agree with @xRadne 
The code is already working and the refactoring can wait.
