### ISSUE TITLE
Labelled section for Grasshopper

### ISSUE THREAD

**Issue by johannariad** [strusoft/femdesign-api#200]
Make a component for labelled sections in Grasshopper

**Comment by xRadne** [comment]
Continue from the C# classes from #50

**Comment by johannariad** [comment]
You can assign this to me if you like :) I could do this for the webinar

**Comment by xRadne** [comment]
Wouldn't it be cool to also read the results in the sections to grasshopper? Maybe you could have a look on implementing `Labelled sections, Internal forces` and `Labelled sections, Resultants` as well?

**Comment by johannariad** [comment]
That would be great, could do that as a next step. Maybe depending on how much we want to work with results reading before we get the new results reader from Budapest.

**Comment by Marco-Pellegrino** [comment]
@johannariad Would you like me to have a look at this?
I am kind of fresh about the topic and I might be able to help you

**Comment by JRiad** [comment]
Please @Marco-Pellegrino if you have time that would be great. I haven't had a chance to look at it yet but I think it would be useful for lots of things 🙏 Perhaps "result points" should also be in the component (or have its own), it is kind of a similar topic
