### ISSUE TITLE
Rename FemDesign.Samples --> FemDesign.Examples

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#203]
### ❓ Why
Samples 💩
Examples 😎

### ⚠ Caution
- [x] This change will break links such as to this blog post: https://strusoft.com/blog/fem-design/connect-fem-design-to-grasshopper/ @JRiad

**Comment by samnyb** [comment]
### C# migration

The migration is currently in progress on branch 289-create-c#-examples, as part of creating examples for #289.

Once added to the new file structure and separated into distinct projects, the examples should be added to the Visual Studio solution within a FemDesign.Examples folder: 
![image](https://user-images.githubusercontent.com/97892858/165258654-451f973b-005d-4512-a61f-8cea65ebeb39.png)

Migration progress:
- [ ] ChangeLengthOfBeam
- [ ] Example1-CreateSimpleModel
- [ ] LoadGroups
- [ ] LoadGroupsCombine
- [ ] ParametricStudy
- [ ] RunAnalysis
- [ ] CreatePostTensionedCable
- [ ] MeshSizeConvergenceStudy

**Comment by samnyb** [comment]
### Grasshopper migration

It is advisable to wait with the migration of the Grasshopper examples until the C# examples have been migrated on branch 289, and the branch merged with the main branch, to avoid any confusion or conflicting directories. 

- [ ] Add todo-list for Grasshopper files once the C# migration is complete and merged to main

**Comment by samnyb** [comment]
### Related important tasks

- [ ] Move the `README` file to the new directory
- [ ] Check if any external links are broken (see top)
- [ ] Update Wiki page to reflect new structure

**Comment by samnyb** [comment]
> ### ⚠ Caution
> 
>  This change will break links such as to this blog post: https://strusoft.com/blog/fem-design/connect-fem-design-to-grasshopper/ @JRiad

I could only find the one blog post linking to the old folder. Google gave no more, either. But I sent an email to Alexandra asking her to edit the one post. If we find more in the future, we can always send another email, or just leave it and let newer blog posts filter it out.
