### ISSUE TITLE
Map components with missing public C# methods

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#222]
A proposed workflow could be to map GH components where there is logic on the component level and create a corresponding public C# method for the relevant class.

## Mapped components with missing public C# method
- [x] #223

- [x] FemDesign.Model.Open(filepath)
- [x] #440
- [x] #439

**Comment by Marco-Pellegrino** [comment]
https://github.com/struparam/2205_ncc-denmark/blob/72fcc893132f301c148831b6aaa7776af0e86874/WallDTO.cs#L121-L125
