### ISSUE TITLE
BinaryFormatter should not be used

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#242]
[BinaryFormatter has been deprecated](https://stackoverflow.com/a/129395/10703508) and should not be used. Also it cannot be used in a ASP.NET application. (Needed for internal project)

### Risks when using in web app
> As a simpler analogy, assume that calling BinaryFormatter.Deserialize over a payload is the equivalent of interpreting that payload as a standalone executable and launching it.

- [Deserialization risks in use of BinaryFormatter](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide)

### Suggested change
I suggest we change 
https://github.com/strusoft/femdesign-api/blob/30909eabb98bc4024fd60cd43a2a5f831933d218/FemDesign.Core/GenericClasses/ExtensionMethods.cs#L11-L21

to instead using `System.Reflection` to clone the objects. https://stackoverflow.com/a/11308879/10703508

**Comment by xRadne** [comment]
@andosca Ok if I include this in Milestone 21.2.0?

**Comment by andosca** [comment]
@xRadne How does this solution work? Does it serialise/deserialise the specified object with regard to the predefined xml serialisation attribute?

**Comment by xRadne** [comment]
> @xRadne How does this solution work? Does it serialise/deserialise the specified object with regard to the predefined xml serialisation attribute?

I don't think so (i hope not). But it needs to be tested.

**Comment by andosca** [comment]
If `XmlIgnore`-attributes are ignored this will cause a lot of problems when some objects are cloned in runtime.

**Comment by xRadne** [comment]
> > As a simpler analogy, assume that calling BinaryFormatter.Deserialize over a payload is the equivalent of interpreting that payload as a standalone executable and launching it.
> 
>     * [Deserialization risks in use of BinaryFormatter](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide)

This should not be a risk for us, since we go from `object -> binary -> object` which should only clone the objects. Assuming the BinaryFormatter recreates the objects identically. (We **do not** go from `binary -> object` which would pose a security risk in web apps due to the possibility of forge the `binary` maliciously.)

**Comment by xRadne** [comment]
> If `XmlIgnore`-attributes are ignored this will cause a lot of problems when some objects are cloned in runtime.

I think you are correct. We could probably use JsonSerializer instead and avoid problems.

**Comment by xRadne** [comment]
> ### Suggested change
> 
> I suggest we change
> 
> ...
> 
> to instead using `System.Reflection` to clone the objects. https://stackoverflow.com/a/11308879/10703508

This seems to be a good solution. It seems to work fine when testing against `gh_decostruct 21.1.0.gh`
