### ISSUE TITLE
C# constructors and methods

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#244]
# C# constructors and methods
`Initiative 2`

## Goals

* Improved C# workflow.

## Background
FemDesign.Core was created to serve GH (and Dyn). Alot of of GH components have logic on the component level - this logic is missing for C# users. 

There is a need to implement this logic for the C# users that are now starting to increase.

## Research
A proposed workflow could be to map GH components where there is logic on the component level and create a corresponding public C# method for the relevant class.

- [x] #222 

#### Geometry
- [x]  #441 
- [x]  #442

- [x] #445
- [x]  #443

- [x]  #444
- [x] #465 

- [x] #516

Evaluate Curve at Length

#### Materials - Sections

- [ ]  Get object with Static Property. Need to do some research to do it properly. One Idea I had is to create a code to generate code with the static property. (probably a bad solution)

Our xml looks like this
```xml
<section fd_name_code="Steel sections" fd_name_type="VKR" fd_name_size="400x400x12.5">
```
c# user might want to do something like this.
```csharp
var mySection = SectionDataBase.Material.Type.Name
var mySection = SectionDatabase.Steel.VKR.400_400_12.5
```

The Intellisense should suggest `SteelSections`, `TimberSections`, `ConcreteSections` for the Material
----------------  should suggest `VKR` for Type
----------------  should suggest `400_400_12.5` for Name

#### Geometry

- [x] #505
- [x] #510

#### Element
- [x] #503

Derived Class
```csharp
new Beam()
new Truss()
new Column()
```

- [x] remove SimpleBeam, SimpleColumn

#### Materials and Sections
- [x] #512

#### Loads
- [x] #506
- [x] #507

#### Loads Combination

- [x] #515
Inspiration taken from `System.IO.Path.Combine()`

## Not doing
The following method can not implemented yet because the .fdscript is not completed/implemented
- [ ] #436 
- [ ] #437 
- [ ] #433 
- [ ]  #446 
- [ ] #433

**Comment by Marco-Pellegrino** [comment]
- [ ] Create a LineEdge with default LocalY or default CoordinateSystem

**Comment by Marco-Pellegrino** [comment]
Material/Section can wait.
Happy with the rest but we will need to wait for Budapest for implementing the other type of analysis
