### ISSUE TITLE
Allow to set Line and Surface load projection.

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#247]
### Line load - Force (variable and uniform)
- [x] C# Constructors with default to false
- [x] GH
- [x] ~Dynamo~ _Not doing_

### Line load - Moment (variable and uniform)
- [x] C# Constructors with default to false
- [x] GH
- [x] ~Dynamo~ _Not doing_

### Surface load - Force (variable and uniform)
- [x] C# Constructors with default to false
- [x] GH
- [x] ~Dynamo~ _Not doing_

https://github.com/strusoft/femdesign-api/blob/30909eabb98bc4024fd60cd43a2a5f831933d218/FemDesign.Core/Loads/SurfaceLoad.cs#L67

**Comment by andosca** [comment]
NEVER! 👹
