### ISSUE TITLE
Design parameters

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#249]
# Design parameters
## Goals

* It should be possible to setup general and element settings for the most common code-checks and design calculations.

## Background
General and element settings for code-check and design calculations were extended to `fdscript` in FEM-Design 21. This feature still needs to be implemented to this project.

## Not doing

**Comment by xRadne** [comment]
Does design parameters refer to Calculation parameters?
![image](https://user-images.githubusercontent.com/32938476/190172584-fafe491b-f459-4c3b-8add-6eb0a0f77f7c.png)

**Comment by andosca** [comment]
Note from IM conversation:

> Calculation settings are a subset of design parameters

In other words the settings `RC shell calculation settings` will be implemented.

**Comment by andosca** [comment]
Will replace with separate initiatives for each material.
