### ISSUE TITLE
Set load combination calculation options

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#254]
Two load combinations are defined, "SLS" and "ULS":

<img width="801" alt="image" src="https://user-images.githubusercontent.com/52665994/156547606-0a0d4dc1-f366-4883-8eec-f1da5f025070.png">

The first one, "SLS" should have no specific options, and the second one, "ULS" should have options as in the picture.

However, in the generated `fdscript`-file the options from the second load combination has been inserted for the first load combination as well.

```xml
  <cmdcalculation command="; CXL $MODULE CALC">
    <analysis calcCase="1" calcCStage="0" calcCImpf="0" calcComb="1" calcGmax="0" calcStab="1" calcFreq="1" calcSeis="0" calcDesign="0" calcFootfall="0" elemfine="0" diaphragm="0" peaksmoothing="0">
      <stage ghost="0" />
      <comb NLEmaxiter="30" PLdefloadstep="20" PLminloadstep="2" PLmaxeqiter="30" CRloadstep="20" CRmaxiter="30" CRstifferror="2" NLSMohr="1" NLSinitloadstep="10" NLSminloadstep="10" NLSactiveelemratio="5" NLSplasticelemratio="5">
        <combitem NLE="0" PL="0" NLS="0" Cr="0" f2nd="0" Im="0" Waterlevel="0" ImpfRqd="0" StabRqd="1" /><!--SLS-->
        <combitem NLE="0" PL="0" NLS="0" Cr="0" f2nd="0" Im="0" Waterlevel="0" ImpfRqd="0" StabRqd="1" /><!--ULS-->
      </comb>
      <freq X="0" Y="0" Z="1" Numshapes="5" MaxSturm="0" top="-0.01" />
      <footfall TopOfSubstructure="-0.01" />
    </analysis>
  </cmdcalculation>
```

**Comment by andosca** [comment]
Make sure to clear all combItems before adding new ones:

https://github.com/strusoft/femdesign-api/blob/91689a4e04990403fb64e274233eea57d01f8bcc/FemDesign.Core/Calculate/Analysis.cs#L243-L250

**Comment by Marco-Pellegrino** [comment]
we should warn the user if they don't set all the load combination as per initial model.

![image](https://user-images.githubusercontent.com/53620289/158993488-61e1bf07-5ddc-41b4-9b81-d9ef19ae43e3.png)


if the user wants to set only one combination, it has to set also the other.

**Comment by andosca** [comment]
b43be82a760d063bcdd61cf671eeede5be95ba08
