### ISSUE TITLE
Example 5: Creating custom section

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#257]
- [x] Creating custom section in Rhino (parametrically define the section)
- [x] Creating custom section  in FEM-Design and load using `SectionDatabase.FromStruxml`

**Comment by xRadne** [comment]
You may hava a look at this as a reference
[Custom sections.zip](https://github.com/strusoft/femdesign-api/files/8204809/Custom.sections.zip)

**Comment by samnyb** [comment]
Idea from Alexander: an example of connected beams, where the height of the section varies parametrically. On hold now but might be relevant later?
![possible sections example](https://user-images.githubusercontent.com/97892858/157243843-c7a8bd15-06b7-433e-a8aa-f536d47c2cfa.png)

**Comment by samnyb** [comment]
Possible implementation: reinforements in section

**Comment by samnyb** [comment]
Leaving suggestions for now, the example is ready for approval. Published it on GitHub
