### ISSUE TITLE
Example 6: RC design

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#258]
An example for how to design an RC-beam/wall/structure.

### Create two parts
- [x] Autodesign 
- [x] Manual design (manual design phi 5 s150 top/bottom x/y)

### Models
Both these should be shown
- [x] A beam with 3 supports
- [x] A slab with several supports

![image](https://user-images.githubusercontent.com/32938476/157422691-5c6f4974-7560-4f53-a2f6-2a9e95c2b63a.png)

![image](https://user-images.githubusercontent.com/32938476/157422452-d736d544-506a-410f-85f5-785227253f68.png)

**Comment by xRadne** [comment]
There are changes in `21.1.1` to the way reinforcement is defined (#183 #209).

Therefore this example must either
1. Wait for them to be merged
2. Be built on branch `21.1.1` to be compatible with the new changes.

**Comment by andosca** [comment]
@samnyb 
With the new component in `21.1.1` you can just "loop" it over `Start`, `End` and `Spacing` input as lists. So 1 component only.

**Comment by samnyb** [comment]
@andosca good point! Still adds a few more components for generating these values, but far less.

**Comment by xRadne** [comment]
- [x] Approved
