### ISSUE TITLE
Facilitate utilisation of materials and sections database in GH

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#262]
Beginner user comment:

> Related to profiles as there are around 1.700 in the database, it is not easy to search for the proper one. I have not known the possibilities of Grasshopper functions, but besides of grouping profiles by materials and types (as it is in FEM-Design) alphabetic order could help. So, for example finding HE-A 200 with its correct naming is not easy.

**Comment by Marco-Pellegrino** [comment]
@andosca 
I have got the same feeling of the user the first time I tried to create a model.
There are definitely several way to get the right section/material with some Grasshopper component but I think we should do the work for them and make everything in one component
