### ISSUE TITLE
Problem with load groups in deconstruct FdModel component

### ISSUE THREAD

**Issue by GabrielEdefors** [strusoft/femdesign-api#265]
Problem with deconstructing FdModel when no load groups are added

**Comment by xRadne** [comment]
I could not reproduce. Could you elaborate when this happens or do you have a file for me to reproduce this?

![image](https://user-images.githubusercontent.com/32938476/157900261-7e6ab4f5-d197-40cc-a2c8-7a601692d2b2.png)

**Comment by GabrielEdefors** [comment]
I figured I probably used an old build of the project. It works fine when using the latest version :)
