### ISSUE TITLE
Make sure Strusoft.Interop.Struxml.Data classes do not show up in Dynamo package

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#276]

**Comment by xRadne** [comment]
It might be worth considering abandoning the Dynamo Zero Touch components and instead go for the [Dynamo NodeModel](https://developer.dynamobim.org/03-Development-Options/3-5-nodemodel-derived-nodes.html). 

`NodeModel` could be used to create a base-component (similar to `GH_Component`) to inherit for all methods we want to expose to the Dynamo.

**Comment by Marco-Pellegrino** [comment]
@andosca @xRadne 
I have generated a script that create an extended `FD_21.00.001.cs` class.
I was reviewing my code and I have realise:
- the version of the schema will update in the future and the name reference should reference that name. What's the best way to find that name? Something to discuss.

https://github.com/strusoft/femdesign-api/blob/81f0b32097a3f9e4819b8923beba9568658eb4eb/FemDesign.Utils/Program.cs#L47-L48

I would like to solve the same visible issue for the enum as well following this kind of approach. It is not super urgent though

**Comment by andosca** [comment]
I guess it could look for a file named "FD*" in Strusoft/Interop/Struxml/Data. There will be no other files with that name.
