### ISSUE TITLE
Replace or add type

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#278]
https://github.com/strusoft/femdesign-api/blob/821bc32b860f6c87e157dbbb28cd061ebf829704/FemDesign.Core/Model/Model.cs#L65

https://github.com/strusoft/femdesign-api/blob/821bc32b860f6c87e157dbbb28cd061ebf829704/FemDesign.Core/Model/Model.cs#L86-L87

https://github.com/strusoft/femdesign-api/blob/821bc32b860f6c87e157dbbb28cd061ebf829704/FemDesign.Core/Model/Model.cs#L92-L93

**Comment by Marco-Pellegrino** [comment]
to double check tomorrow:
when we have to use List<> or not in this case.
I think I have understood but better to see it together

**Comment by andosca** [comment]
5ae6901eb6d37fa4326e4514adc20ce8f02d02cd
