### ISSUE TITLE
Planar surface is not planar

### ISSUE THREAD

**Issue by samnyb** [strusoft/femdesign-api#282]
![image](https://user-images.githubusercontent.com/97892858/159436664-2f5a7cbc-98fb-43ad-b906-c0da57d17b15.png)

Probably need a tolerance for checking if the surface is planar

**Comment by andosca** [comment]
Please link to code in repo on relevant branch:

* [create a permanent link to a code snippet](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet)

Also please describe the situation where this exception is thrown.

Is this related to #279

**Comment by samnyb** [comment]
Added test script 282. Search for `Brep surface is not planar` // @xRadne

**Comment by samnyb** [comment]
> Please link to code in repo on relevant branch:
> 
>     * [create a permanent link to a code snippet](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet)
> 
> 
> Also please describe the situation where this exception is thrown.
> 
> Is this related to #279?

Will do // @xRadne

**Comment by samnyb** [comment]
> Is this related to #279?

Yes, I realize now I double-issued this. Sorry about that!

**Comment by xRadne** [comment]
We probably need to set the tolerance to check against here:

https://github.com/strusoft/femdesign-api/blob/91689a4e04990403fb64e274233eea57d01f8bcc/FemDesign.Grasshopper/Geometry/Convert.cs#L522-L526

**Comment by samnyb** [comment]
UPDATE: Problem seems to stem from the units used in the Rhino model. In both #279 and #282, the surfaces used were imported from a model using millimeters instead of meters. 

I never realized this, but looking back, it should have been obvious - since the FEM-Design model is about four kilometers wide and eight kilometers long...

Changing the Rhino unit to meters - and scaling the model by 0.001 - removed the problem. 

So, it seems this might be another problem entirely. Is there a way to read units from Rhino and send it to FEM-Design to avoid this problem? Otherwise, it might just be a "user will have to figure it out" type of problem...

**Comment by andosca** [comment]
Update
