### ISSUE TITLE
dynamic deserialisation

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#285]
https://github.com/andrewheumann/jSwan

I was using this tool in the past and I am placing here the repository so we all know about the tool.
It create a grasshopper component following the json output. It might be pretty cool to "borrow it" and place it in FEM-Design

**Comment by xRadne** [comment]
I've used it too and it is a really good way of deserializing and deconstructing objects in Grasshopper.

Also there is the `Explode` component in [BHoM](https://bhom.xyz/) that does the same thing for any object, not just JSON

**Comment by andosca** [comment]
Duplicate of #92
