### ISSUE TITLE
Create C# examples

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#289]
> We should create these examples in `C#` as well. These examples should be equivalent so that a user familiar with one framework could easily compare c# to grasshopper (and eventually python and/or dynamo)

_Originally posted by @xRadne in https://github.com/strusoft/femdesign-api/issues/34#issuecomment-1084438395_

### Basic examples to implement (Scripts)
- [x] Example 1: **Creating** a simply supported **beam** with supports, loads, loadcases
- [x] #327
- [x] Example 3:
- [x] #293 - prio 1
- [x] Example 5:
- [ ] Example 6:
- [x] Example 7:
- [x] #392

### Practical examples
- [x] #321

**Comment by samnyb** [comment]
### TODO: Spring cleaning of C# examples

A better file structure would help a user find their way in the samples folder. Our current plan looks something like this:
- 📁 FemDesign.Samples\C#
   - 📁 Example 1: blaha
      - 📁 Output
      - 📃 Associated files (scripts, .bsc, .struxml and so on)
   - 📁 Example 2: blaha
      - 📁 Output
      - 📃 Associated files (scripts, .bsc, .struxml and so on)
   - 📁 Example 3: blaha
      - 📁 Output
      - 📃 Associated files (scripts, .bsc, .struxml and so on)
   - ....
   - 📁 Practical example: blaha
      - 📁 Output
      - 📃 Associated files (scripts, .bsc, .struxml and so on)
   - 📁 Practical example: blaha
      - 📁 Output
      - 📃 Associated files (scripts, .bsc, .struxml and so on)
   - 📃 Femdesign.Samples.csproj
   - 📃 Main.cs
   - 📃 Other associated files

Naming conventions should, if possible, corelate with Grasshopper examples for easier comparison. Old files can be repurposed as Practical examples.

❗ When sorting the files, renaming, and so on, remember to change the scripts to properly account for new directories and file paths!

**Comment by samnyb** [comment]
Should examples have a .txt file in their folders, with a short summary on what it does and where you can find the results (bin)? Or is that obvious?
