### ISSUE TITLE
Method of sorting Panels by walls/plates not consistent with Slabs

### ISSUE THREAD

**Issue by samnyb** [strusoft/femdesign-api#298]
Slabs can be filtered by walls (horizontal) and plates (vertical) by using `Shells.Slabtype`, which gives either `Wall` or `Plate`. Panels however doesn't have the same system, because `Shells.PanelType` gives `Concrete` and `Timber` rather than wall and plate.

Additionally, there doesn't seem to be any other way of sorting Plates either, at least what I could find. The best idea I had after looking at the properties of shells were to test for the orientation of the Region Edges, see if they were perpendicular to world Z - it works, but is a lot more roundabout than just comparing `SlabType`.

![image](https://user-images.githubusercontent.com/97892858/161975959-15bae7b2-4e5f-47c8-817a-fe5594447067.png)
**Image:** a generated slab. Note `type="wall"`.

![image](https://user-images.githubusercontent.com/97892858/161975860-4f4ca88c-9ca1-4260-b3fb-61bbf2318deb.png)
**Image:** a generated panel. Note `type="timber"`. Note also that there is no other tag which clearly communicates the distinction between wall/plate.

**Comment by andosca** [comment]
From FD's point of view, in struxml, there is no distinction between `walls` and non-`walls` for `panels`. FD uses geometrical information to decide what is a `wall` and what is not. Could be either `direction` or normal to the region (direction of outer contour in region).

Will ask BP.

**Comment by andosca** [comment]
https://strusoft.fogbugz.com/f/cases/119639/Panel-wall-non-wall

**Comment by andosca** [comment]
No answer from BP...
