### ISSUE TITLE
ShellEdgeConnection.Define lacks inputs for Plastic limits

### ISSUE THREAD

**Issue by samnyb** [strusoft/femdesign-api#302]
![image](https://user-images.githubusercontent.com/97892858/162919829-b3aed821-2314-4953-8081-0bfd2c5b8a62.png)

`ShellEdgeConnection.Define` lacks inputs for Plastic limits, despite this being available in the `.struxml` scheme. For comparison, the `PointSupport.Define` component has these inputs.

**Comment by xRadne** [comment]
I can do this together with #303

**Comment by andosca** [comment]
We can put both of them in 21.2.0 if you intend to do them now.
