### ISSUE TITLE
ShellEdgeConnection doesn't work

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#303]
Nothing happens when we use the Grasshopper component to edit edge connections

**Comment by andosca** [comment]
If you define a `rigid` edge connection this is the .xsd default value, and in this case the edge connection is nulled. The `release` should be true if an edge connection being set is not `rigid`.

I do not have enough information to give a good answer here - that solves this bug with minimal effort. @xRadne  Does your unit test reproduce the error, such that I can have a look at that one?
