### ISSUE TITLE
Refactor namespaces in Tests

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#306]
Namespaces should be FemDesign.**Area**.**Class**Test. For example:

`FemDesign.AuxiliaryResults.LabelledSectionTests`

**Comment by Marco-Pellegrino** [comment]
@andosca 

just double checking.
Were you thinking at renaming the namespace in the way I have done it?
https://github.com/strusoft/femdesign-api/commit/3886ea121ea9092d68bb912fa74ea4fc920fa0bb

**Comment by andosca** [comment]
Yes that looks good!
