### ISSUE TITLE
Result Reader - EigenFrequency

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#310]
It is an helpful value for several case studies such as Bridge Design and Staircases.

**Comment by xRadne** [comment]
I know @ShahoRuhani would be interested in this!

**Comment by Marco-Pellegrino** [comment]
it will be a great opportunity to meet @ShahoRuhani  :)

**Comment by Marco-Pellegrino** [comment]
@xRadne 
I have fallen in love with your parser and here a little issue that I do not fully understand.
The parser works great (it is able to assign the value and create the object as it should) but for some reason the HeaderExpression test failed to pass.

It would be great to understand the reason even though the method "Parse" works as expected

```
Eigenfrequencies
Shape	Frequency	Period	Modal mass	mx'	my'	mz'
[-]	[Hz]	[s]	[t]	[%]	[%]	[%]
1	1.491	0.671	10.260	0.000	0.000	81.302
2	6.041	0.166	4.163	0.000	0.000	0.104
3	19.250	0.052	4.102	0.000	0.000	2.653
4	21.010	0.048	3.524	0.000	0.000	8.512
5	25.865	0.039	8.156	0.424	68.956	0.000
6	32.680	0.031	1.594	0.000	0.000	0.000
```

https://github.com/strusoft/femdesign-api/blob/50856fddb534253ca11637beb73a794611d65612/FemDesign.Core/Results/EigenFrequencies/EigenFrequencies.cs#L64-L78

**Comment by Marco-Pellegrino** [comment]
I have spotted the issue.
The regular expression was missing `$` that specify an end of string or end of line.
The test file was also formatted in a wrong way. `space` instead of `tab` 😞

**Comment by xRadne** [comment]
> The regular expression was missing `$` that specify an end of string or end of line. 
> The test file was also formatted in a wrong way. `space` instead of `tab` 😞

Two easy to miss errors... I've done the same several times 😅
