### ISSUE TITLE
Result Reader - Shell Derived Internal Forces

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#313]
- [x] not extract

- [x] extract

**Comment by xRadne** [comment]
I think we already have this, but might be worth checking if it works the way it should

https://github.com/strusoft/femdesign-api/blob/a7c15b1027db3814fc39b453ea134362292dae01/FemDesign.Core/Results/ShelllnternalForce.cs#L104-L138

**Comment by Marco-Pellegrino** [comment]
`ShellDerivedInternalForce` should be different from `ShellInternalForce` :)
I'll have a proper look when I get there

**Comment by xRadne** [comment]
Of course haha! 😂

**Comment by Marco-Pellegrino** [comment]
https://github.com/strusoft/femdesign-api/commit/74d4c8c5b28948cc35a5ff11eeb749119a00483b
