### ISSUE TITLE
Nodal Displacement Deconstructor - Dynamo - Grasshopper

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#318]
- [x] Grasshopper Component #97 
- [x] Dynamo Component #97

**Comment by Marco-Pellegrino** [comment]
@andosca @xRadne 
A little study that I have done for the implementation of Nodal Displacement for Grasshopper
it looks like that checking if an object has a certain type is really time consuming and we should avoid it.

The idea is that the user will need to select the correct result type objects after the analyses. ExplodeTree or TreeBranch from Grasshopper be sufficient.

![image](https://user-images.githubusercontent.com/53620289/164692630-bdb2e739-075d-4787-832f-00851126d818.png)

As you can see in line 66, we cast the result to the type `FemDesign.Results.NodalDisplacement` as we are already aware that the inputs belong to that class.

https://github.com/strusoft/femdesign-api/blob/485fb546f0ec41d24aed439c542e79c99161c887/FemDesign.Grasshopper/Results/NodalDisplacement.cs#L55-L67

**Comment by andosca** [comment]
That is unfortunate. So DataTree/Dictionary for Grasshopper/Dynamo.

**Comment by Marco-Pellegrino** [comment]
@andosca 

I was thinking to start creating the other deconstructor for Dynamo and Grasshopper and it would be great to have your opinion on the following

🦗 Code
https://github.com/strusoft/femdesign-api/blob/60549f13df153f5651703398c44b92df66d96f9b/FemDesign.Grasshopper/Results/NodalDisplacement.cs#L52-L123

Dynamo Code
https://github.com/strusoft/femdesign-api/blob/60549f13df153f5651703398c44b92df66d96f9b/FemDesign.Dynamo/Dynamo/Results/NodalDisplacement.cs#L23-L83


The code are basically the same apart for ToRhino() and ToDynamo().
Any thought?

**Comment by andosca** [comment]
Well in that case you could abstract everything to a public C# method and just do handling of input and output in GH/DYN.
