### ISSUE TITLE
Create a NuGet C# package

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#32]
- [x] StruSoft organization on NuGet.org
- [x] Setup `FemDesign.Core` package specification `.nuspec`
- [x] Upgrade version
- [x] Publish `nupkg` 
- [x] #49 Publish nuget github action?

### Decisions to be made
- [x] ~Use namespace `StruSoft.FemDesign` instead?~ No, can be changed if we publish APIs for other software too.
- [x] ~Should debug symbols be included in package? (`-symbols`)~ User can download the source code for this.

**Comment by xRadne** [comment]
@andosca @ibjorhag I just published a nuget package for C# developers. FYI

https://www.nuget.org/packages/FemDesign.Core/

**Comment by andosca** [comment]
Version should be 20.0.0 not 1.3.1. This is a bit confusing but major version will follow FEM-Design version in the future to point out which xml-schema the framework is compatible with.
