### ISSUE TITLE
Replace DummyXmlObject with Strusoft.Interop.Data types

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#324]
Now that we have included the schema we should be able to replace all dummy elements meaning we can reduce (remove all?) loss of information when read-writing a .struxml file. 

If this does not come with any drawbacks i think we should do this quite soon :)

**Comment by andosca** [comment]
We implemented a lot of them in 21.1.1 already. But will continue according to: https://github.com/strusoft/femdesign-api/issues/243

**Comment by xRadne** [comment]
OK cool!
