### ISSUE TITLE
Get access to silent mode of FEM-Design (or call to the program running on a server or similar)

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#325]
User request. It would be nice to be able to create custom workflows using FEM-Design without having to open the program at all. The file created should still be saved somewhere for documentation.

**Comment by xRadne** [comment]
It is already possible for a programmer to run fdscripts in the background using `FD_NOGUI="1"` #157

**Comment by xRadne** [comment]
Included in #567 and will be available in 21.6.0
