### ISSUE TITLE
Create a Python package

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#33]
# Python package
A wrapper around the FemDesign.Core.  
- Pip package
- Downloads latest (or a specific version) of Core `dll` from NuGet? 
- Loaded with `clr`
- With type hints (from stubs or generated wrapper classes?)

### Potential Issues
- Core is currently compiled to .Net Framewirk, which only works for Windows. However FemDesign is exclusive for windows too. https://stackoverflow.com/questions/2822424/python-copy-a-dll-to-site-packages-on-windows

**Comment by andosca** [comment]
@andosca test the sample.

**Comment by xRadne** [comment]
We should ask a python developer to test this example to see if the solution is sufficient before we continue to work on including it as a pip package or something.
