### ISSUE TITLE
String Representation for Results

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#330]
Have a better string representation for the object.

We could include some numerical output. To be discuss
![image](https://user-images.githubusercontent.com/53620289/165728616-5bf61e49-44b4-4eb3-9fc3-a3b847bb8988.png)

**Comment by xRadne** [comment]
Do we have anything we could compare with. I don't know how we could display the numbers without overwhelming the reader :P

**Comment by xRadne** [comment]
What was the result? :)

**Comment by Marco-Pellegrino** [comment]
I wrote a method that will return all the properties in a formatted way.
We will need to get some feedback from the user if they want to see less information but I personally don't mind. The amount of information shown in the string representation are manageble.

Most of the users will use the deconstructore anyway.

![image](https://user-images.githubusercontent.com/53620289/173571669-d070ac88-8e7f-48df-a7fd-4cbbe4848c13.png)

https://github.com/strusoft/femdesign-api/blob/ab108a30e3ad746b1f9d718744a4001da1e00c2a/FemDesign.Core/Results/ResultsReader.cs#L184-L200

**Comment by xRadne** [comment]
Looking good!
