### ISSUE TITLE
DeepClone speed issue

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#334]
The new DeepClone solution seems to have some speed issues that causes GH to freeze when cloning a fd-model.

Try to run:

https://github.com/strusoft/femdesign-api/blob/d30d4a07e536ae63f585096eb98be047b3e435f6/FemDesign.Tests/Model/ModelTests.cs#L122-L132

**Comment by xRadne** [comment]
Switching back the FemDesign.Model.Geometry to be a `DummyXmlObject` makes the deepclone run fast again. Which means:

> We got ~400 thousand lines of problem and `<geometry>` is 99% of them

![image](https://user-images.githubusercontent.com/32938476/165773128-19892584-18ef-450d-bc4d-d3e1802ff7fe.png)

**Comment by andosca** [comment]
This is crazy.

This geometry of geometry takes up 13 mb if saved to .struxml:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/52665994/165782877-5476abfa-b5c3-46a3-a28b-1d0bbdf40a09.png">

**Comment by andosca** [comment]
It seems like FD is multiplying new `region`-geometry when serialising to `.struxml`...
