### ISSUE TITLE
Design gmax

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#335]
Allow user to set the type of design check to be run

```xml
<cmduser command="; CXL $MODULE STEELDESIGN" />
<cmdcalculation command="; CXL $MODULE CALC">
  <design>
    <!-- <cmax /> -->
    <gmax /> 
    <autodesign>false</autodesign>
    <check>true</check>
  </design>
</cmdcalculation>
```

https://github.com/strusoft/femdesign-api/blob/0779d5aa6580e245567cc141be29428fb54d05f6/FemDesign.Core/Calculate/Design.cs#L13-L16

**Comment by Marco-Pellegrino** [comment]
There are no clue on what to use in Cmax and Gmax.
The example.fdscript does not show the the value to use in the xml attribute unfortunately.

![image](https://user-images.githubusercontent.com/53620289/181193596-7d656b35-1dd0-489b-9332-3db4fb2de36c.png)

**Comment by Marco-Pellegrino** [comment]
it might be a:
cmax or gmax 😄

**Comment by Marco-Pellegrino** [comment]
it worked!
The code will serialize `cmax` or `gmax` depending on the input
