### ISSUE TITLE
Update schema and FD icon

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#339]
@andosca Two questions:
- Should the Schema be updated?
- Should we update to the new FD logo in the `FemDesign.Core/Resources/icon` so that it is used in the NuGet packages?

_Originally posted by @xRadne in https://github.com/strusoft/femdesign-api/issues/319#issuecomment-1114611044_

**Comment by Marco-Pellegrino** [comment]
the latest schema `FD 21.00.002 strusoft.xsd` doesn't seem to have any substantial conflict with `FD 21.00.001 strusoft.xsd`.
I have compare the two files and the only difference occurs in the following type. Nothing important I believe

```xml
  <xs:simpleType name="geometry_text1023"> <!-- From FD21.00.002, for text_type only! -->
    <xs:restriction base="xs:string">
      <xs:pattern value="[&#x0009;&#x000A;&#x000d; -&#xfffd;]{0,1023}" />
    </xs:restriction>
  </xs:simpleType>
```

**Comment by Marco-Pellegrino** [comment]
@andosca @xRadne @johannariad 

Which version do you prefer as icon for the NuGet package? 
I am pointing towards the minimal version with no text.
![image](https://user-images.githubusercontent.com/53620289/166423223-bd0d0292-cace-498f-9a71-ba0d19f46e8c.png)

**Comment by xRadne** [comment]
[Since the logo is displayed quite small](https://www.nuget.org/packages/FemDesign.Core/), I prefer the minimal logo

**Comment by Marco-Pellegrino** [comment]
I haven't seen that the icon was going to be so tiny 😄 
Minimal is definitely the way to go!

**Comment by Marco-Pellegrino** [comment]
The schema is not going to be update as .cs file is missing
