### ISSUE TITLE
Remove old Python examples from wiki?

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#341]
I'm afraid the old examples where Isak modifies a struxml file directly in Python (without the new C# API) might cause confusion, even though they still work and the documentation is nice.

https://wiki.fem-design.strusoft.com/xwiki/bin/view/FEM-Design%20API/Python/Optimization%20using%20Python%20script/

So I don't know, keep or remove from wiki? What do you think @andosca @Marco-Pellegrino @xRadne @ibjorhag?
I vote "kill your darlings" on this one 😢

**Comment by xRadne** [comment]
I vote **keep but add an outdated/not-recomended flag**

**Comment by ibjorhag** [comment]
I think the python API-wrapper should be removed.
I don't really have an opinion otherwise. Just a question.
Is there now a way to modify all settings using the deconstruct/construct method in the API?

**Comment by andosca** [comment]
I think the python API still has a purpose. So I think there should be some information about it still. However, we can probably make it less accessible and direct users there if they ask us for example. 

Maybe we can refurbish the wiki a little bit. I'll see what I can do.

@ibjorhag It is not possible to read/write everything yet even though there are only a couple of "fringe" elements left.

**Comment by JRiad** [comment]
@andosca just to clarify: The old Python examples are still available on GitHub, I was just thinking about the wiki. Seeing as it can be hard to navigate I thought it was a risk that users may end up on that page instead of the newer, more relevant pages.

![image](https://user-images.githubusercontent.com/89396751/166882231-d3ac41aa-0a4f-4d31-8090-dba55888eee7.png)

**Comment by samnyb** [comment]
[I left them for now](https://wiki.fem-design.strusoft.com/xwiki/bin/view/FEM-Design%20API/Python/Optimization%20using%20Python%20script/#), but put the same disclaimer there as I did on the main Python page, mentioning that we suggest using C# instead for now. Sort of a middle way between your suggestions, you are welcome to change it if you'd like!

**Comment by JRiad** [comment]
> [I left them for now](https://wiki.fem-design.strusoft.com/xwiki/bin/view/FEM-Design%20API/Python/Optimization%20using%20Python%20script/#), but put the same disclaimer there as I did on the main Python page, mentioning that we suggest using C# instead for now. Sort of a middle way between your suggestions, you are welcome to change it if you'd like!

Sounds good 👍
