### ISSUE TITLE
Dynamo installation text

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#343]
Text on how to get started with Dynamo.
- Installation of Revit/Dynamo
- Installation of FEM-Design API
- Opening up the examples

**Comment by samnyb** [comment]
All that needs to be added is Installation of Revit/Dynamo, right? I think the other two are covered:

Installation of FEM-Design API is in the main README.md: https://github.com/strusoft/femdesign-api

Opening the examples is in the Examples README.md: https://github.com/strusoft/femdesign-api/tree/master/FemDesign.Examples

Can they be improved in some way maybe, any instructions missing?

**Comment by xRadne** [comment]
Skipping text on Installation of Revit/Dynamo.
