### ISSUE TITLE
Implement soil elements

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#349]
https://github.com/strusoft/femdesign-api/blob/2ac4d5703894dbbbec176947fa88add0ad25c2ef/FD%2021.00.001.xsd#L5976-L5986

**Comment by Marco-Pellegrino** [comment]
https://github.com/strusoft/femdesign-api/commit/0d33753c44ab6dc9246bc7f1e2bbd5c243bb6fc0

**Comment by xRadne** [comment]
I just had a client asking about creating piles and soil from the grasshopper plugin. Is this planned to be added or is this issue only about serilization to/from struxml? :)

**Comment by Marco-Pellegrino** [comment]
The issue was related to Serialisation to/from struxml.
It should also be solved
