### ISSUE TITLE
shell stresses

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#358]

**Comment by Marco-Pellegrino** [comment]
Need to get the information "Shell side" when parsing the data

**Comment by Marco-Pellegrino** [comment]
the HeaderExpression is working in the test but it does not return the Type in the main script.

**Comment by xRadne** [comment]
> the HeaderExpression is working in the test but it does not return the Type in the main script.

What type is it returning?  
Does it receive identical input? :)

**Comment by Marco-Pellegrino** [comment]
I need to be more clear. Sorry @xRadne 
When I say type, I mean the Key-Value that we can get if Regex succeed.

regex101 is definitely really helpful. I have just solved a bug with that for LineSupportReaction
