### ISSUE TITLE
Section reference disappears from .struxml script

### ISSUE THREAD

**Issue by samnyb** [strusoft/femdesign-api#362]
## Problem
Sometimes when adding a bar element to a model, the section gets added as a "complex section" without also adding the reference section. As a result, that FEM-Design can't read the file properly, and can't create the element.

The user reported this problem after downloading the 21.1.1 version of the Grasshopper API Toolbox, but reports no similar issues with 21.0.0.

## Example
- In Grasshopper, I use the section here - note the Guid marked in green:
![iGH](https://user-images.githubusercontent.com/97892858/168078685-be1eb351-5910-4fed-b5d7-172510aade1e.png)

- When opening the model, this error message is displayed: 
![image](https://user-images.githubusercontent.com/97892858/168079399-63d1c58b-25c2-4ced-8bcc-38bb215a2d62.png)

- In the created `.struxml` file, the section is used for a complex section (see Guid in green) and the complex section is used as the beam section (not visible, but following yellow arrow). However, the original section itself isn't referenced in the `.struxml` file, so the reading fails: ![beskrivning](https://user-images.githubusercontent.com/97892858/168078243-d9cf160d-ffca-466a-af06-75d556efc99c.png)

- The section does exist in the database used: 
![database](https://user-images.githubusercontent.com/97892858/168080187-19b52a1d-c3a6-405a-bfa8-71bc20466023.png)

- And if you add it manually to the `.struxml` script, the model loads as normal:
![image](https://user-images.githubusercontent.com/97892858/168080661-97240c3f-0584-4238-8f9f-b5bb7c458b3a.png)

## Reference material
A folder with the GH script, `.struxml` file, material and section databases have been added to the Test files folder on our OneDrive.

## Related issues
This issue may be related to #283 - at least they seem similar, as they both have to do with sections acting up. However, while #283 could be temporarily solved by "reloading" the section components, it didn't seem to work this time around. It's also worth mentioning that while #362 was first reported on 21.1.1, #283 was reported when running 21.0.0.

Either way, it might be interesting to keep an eye on that issue as well.

**Comment by Marco-Pellegrino** [comment]
the issue might happen in the setter for Sections.section


https://github.com/strusoft/femdesign-api/blob/d95ba2834d59cfa5bd699bd9b2c541b5133e1205/FemDesign.Core/Sections/ComplexSection.cs#L19-L43

**Comment by Marco-Pellegrino** [comment]
Same issue happen when we try to attach a section that it is not part of the "default DataBase"
![image](https://user-images.githubusercontent.com/53620289/168248800-f543e173-ff57-45f9-ab92-7372f10c580b.png)

The error does not happen if we use a section from a default FEMDesign DataBase
![image](https://user-images.githubusercontent.com/53620289/168249909-e0be770d-eb13-42bc-8f9f-773272ae773e.png)

**Comment by samnyb** [comment]
Just found a situation where the problem appeared for `Bars.Beam`, but the same section worked perfectly fine for `Bars.Truss`. I have not tried replicating it, but I wanted to leave a note of it at least.

**Comment by andosca** [comment]
Thanks that actually narrows the scope of debugging.
