### ISSUE TITLE
GH Slab.SetShellEdgeConnection different connections

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#364]
The Grasshopper component `Slab.SetShellEdgeConnection ` is currently limited to only setting a single edge connection at one or many indicies of a slab. This should be change to allow to set different edge connections at the different edge indicies

https://github.com/strusoft/femdesign-api/blob/749fafcb51cb761b91ada75b476e2efe54706ce9/FemDesign.Grasshopper/Shells/SlabSetShellEdgeConnection.cs#L10-L19

**Comment by andosca** [comment]
How would you want this to work?

**Comment by xRadne** [comment]
> How would you want this to work?
> 
> Say you feed 1 edge connection type and want to change it on 3 edges. Would it then be OK to multiply that one edge connection type 3 times?

Input/output:
\# | Edge connection | edge indices | Result
--- | --- | --- | ---
1 | 1 EC | 1 index | Sets 1 edge connection
2 | 1 EC | multiple indices | Sets the edge connection on all indices
3 | Multiple EC | 1 index | _Error_
4 | Multiple EC | Multiple indices | Sets 1 EC per index (same as looping over # 1)

**Comment by andosca** [comment]
Perfect!

**Comment by xRadne** [comment]
Done ac59ed30bd6d2906e0557ea4dfc22f9f8b3dcad6
