### ISSUE TITLE
Create installer for GH and Dynamo

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#37]
### Create installer
- [x] Grasshopper 
- [ ] Dynamo (installed to all applicable folders)

**Grasshopper libraries path**  
`%AppData%\Grasshopper\Libraries\FemDesign`

**Dynamo libraries path**  
`%AppData%\<program>\<version>\packages\FemDesign`

where `<program>` is `Dynamo Core` or `Dynamo Revit` 
and `<version>` is all applicable versions. (Needs to be tested?)

**Comment by andosca** [comment]
Possible send this case to internal development to add in StruSoft installer.

**Comment by andosca** [comment]
See case 109741.

**Comment by xRadne** [comment]
@andosca @JRiad @samnyb I have created a (working) mock-up for an installer.

![image](https://user-images.githubusercontent.com/32938476/152503203-4ed30994-503d-4da3-b3b2-39e593e64f89.png)

It loads all the releases available from GitHub and checks for the file/asset `FemDesign.Grasshopper.zip` and installs to the correct folder.

![image](https://user-images.githubusercontent.com/32938476/152503313-85153117-e30e-417d-97a9-dc7d6b26744c.png)

**Comment by andosca** [comment]
Looks good!

Would it be possible to distinguish between pre-releases and regular releases to have it look a bit more tidy for public users?

**Comment by xRadne** [comment]
![FemDesign Installer prereleases](https://user-images.githubusercontent.com/32938476/152506779-26aa3fe2-75ef-4248-93d3-3149ff60b9e5.gif)

**Comment by JRiad** [comment]
👏  very nice!

**Comment by andosca** [comment]
Then I can clean up the releases such that the users only see official releases.

**Comment by xRadne** [comment]
The installer needs an access token for the installer to access the releases. Either user needs to log in to GitHub or the strusoft organization might want to create one for this installer I think
