### ISSUE TITLE
check Regex for Results Deconstructor

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#370]
check if the Regex are correctly implemented.

**Comment by Marco-Pellegrino** [comment]
@xRadne 
I have spent some time trying to clean the Tests and Regex Expression in order to understand the issue in parsing thre results.
For some reason that I can not fully understand, the HeaderData can not collect the data in the way it should.

It is not super urgent but it would be great if you can have a look. The HeaderData would be really helpful for ShellStresses where the stress can be computed in "top", "bottom", "membrane" and the information seems to be only in the header.
We might be able to ask to Budapest to add a column for us :)

I'll start asking them in Fogbuz as well. It is definitely helpful for FEM Design users as well.

https://github.com/strusoft/femdesign-api/blob/93fefcc1bc665cbf4e8b3d0b236e75e903bdd421/FemDesign.Core/Results/BarDisplacement.cs#L95-L107

**Comment by xRadne** [comment]
I'll have a look right away :)

**Comment by Marco-Pellegrino** [comment]
branch 370 should help.
Thanks a lot :)

**Comment by xRadne** [comment]
I'm suspecting that some of the new result types matches too broadly, since I can see that the ShellUtilizationTests are now failing (and I don't think you have changed the code for ShellUtilization)

**Comment by xRadne** [comment]
The bug stems from this line:
https://github.com/strusoft/femdesign-api/blob/8387cdb1ee438620727d142bafa231c2d7efd706/FemDesign.Core/Results/ResultsReader.cs#L35

Here I take the Header expressions from all the result types and combine them into a single RegEx pattern with the 'or' (`|`) character between.

This should probably be avoided.

**Comment by xRadne** [comment]
Problem was with "too broad" RegEx _HeaderExpressions_. Fixed in 83f250477e385742ad082f4908815da4e1ef4486
