### ISSUE TITLE
Consider organising temp files in work directory

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#371]
Organise temp files for results and other things such as .fdscript, .bsc in some way. Could be in a TEMP folder that the users does not see or in a folder in the working directory.

**Comment by xRadne** [comment]
YES PLEASE! 🙏

**Comment by Marco-Pellegrino** [comment]
yes!
I had the same thought!
What about a folder in the same working directory?

**Comment by andosca** [comment]
The two alternatives I see are:

* Write to some AppData folder. Make sure to clear it in some way so that it does not fill up.
* Add subdirectory to working directory.

Maybe there are some other options?

**Comment by andosca** [comment]
I think we need to solve this in 21.2.0 as the users might be frustrated with all the files generated in their folders otherwise.

**Comment by Marco-Pellegrino** [comment]
I personally like to expose the outputs to the users so my preference goes to the subdirectory.
Should also make life easier in case some of the users want to create some custom scripting?

**Comment by andosca** [comment]
I'm OK with that approach. 

Maybe we should separate the .bsc-files and .fdscript file from the .struxml file and the .csv files in some way?

For example if the model name is `someModelName`:

`./someModelName.struxml`
`./someModelName/results/` for .csv files
`./someModelName/data/` for .fdscript and .bsc files

**Comment by Marco-Pellegrino** [comment]
@andosca @xRadne 

It would be great if we can review the issue.
It does the job for the Grasshopper users but It might be that I have missed somthing for a C# user.

https://github.com/strusoft/femdesign-api/commit/f73dbb019b2beb72c7bc0b23dc70b4c879546add

Would it be possible to review it tomorrow?

**Current Directory**
![image](https://user-images.githubusercontent.com/53620289/169852525-2877f08e-bb85-4a23-84fa-c34846b303e5.png)
**data**
![image](https://user-images.githubusercontent.com/53620289/169852671-d750824f-caf8-470c-a2cf-8cd9f2b2d825.png)
**results**
![image](https://user-images.githubusercontent.com/53620289/169852787-d44d78cd-965d-4240-ada6-8e69aaf41b22.png)

**Comment by andosca** [comment]
Absolutely!

**Comment by xRadne** [comment]
- I think the `data`and `results`folders should be inside a folder with the same name as the model (`TestModel`). As per @andosca s comment
- I think the `logfile.log` should also be moved inside the `TestModel`folder.
- Could you please try it out with the C# example scripts as well to see if it works already?

**Comment by Marco-Pellegrino** [comment]
@xRadne 
You are right!
I have badly interpreted the folder structure. I agree with point number 1-2.

I'll modify it and get back to you 👌
