### ISSUE TITLE
Add runNode bool input to ReadStr component

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#373]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/52665994/174266271-8bc632ec-b59e-4d32-afd2-144919340c48.png">

Model.ReadStr should have an input parameter `RunNode` as Model.Open so that the user can decide when the component is run.

**Comment by lorinczandrea** [comment]
Fixed d8c6b0e7b0d7bdbde4627e231ba4f27c9a06c237
