### ISSUE TITLE
Output Units

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#375]
[2021-11-10 16:52] Johanna RiadBasically
we are wondering about the units in the quantity estimation bsc-file

[2021-11-10 16:53] Johanna Riad
We are trying to figure out what the logic is behind the numbers I marked in yellow, so that we can extract data with different units depending on the situation

[2021-11-11 09:36] Csikós Attila
I made a little picture about the problem. In the background and the left side, you can see how the list item specific units dialog can be open, and right side what is in the code and what is the specific order/index of the physical attribute (length, mass, force, etc) [<num>] and what is the selected unit [<unit>]. The first 8 [0-7] were used currently, the rest is reserved for later (alles zusammen 64). This 0-7 indexing can be checked in the dark background code snippet.[Doc-template unit interpretation.png](https://strusoftgroup-my.sharepoint.com/personal/attila_csikos_strusoft_hu/Documents/Microsoft Teams Chat Files/Doc-template unit interpretation.png

[2021-11-11 09:39] Csikós Attila
What the example shows, the force unit. The Force attribute handled by index 3 (signed by square) and the selected unit is the kN which is the index 2 in the correspondent unit combo box (signed by circle)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/53620289/169245757-465cd67b-35a7-4afa-8376-ade81ab3d041.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/53620289/169245760-e58b25c9-50e6-44d7-ba64-2b1c2e48e2c2.png)

**Comment by Marco-Pellegrino** [comment]
@andosca 
I think we should review the following together before I merge to 21.2.0.

I am not fully convinced on:
- Namespace name
- UnitsResult might be better to have a static constructor?
- Grasshopper -> do we want to create a different component to set up the units? I personally think that we can just decide for them and avoid to increase complexity.

https://github.com/strusoft/femdesign-api/commit/0ffc4f2b2e7a3c0ad3b0978226ac92c51c03c69b
https://github.com/strusoft/femdesign-api/commit/76db7b04439ec68dd52512c3d122dfc4f5d240d4

**Comment by andosca** [comment]
Sure. Ping me when back from holiday.
