### ISSUE TITLE
Construction stages

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#380]
Construction stages [are now available](https://strusoft.fogbugz.com/f/cases/119444/Construction-stages-available-from-FEM-Design-API) from the struxml/fdscript in version (21.00.003)

### Features C#
- [x] Create constuction stage
- [x] Assign structure to a construction stages 
- [x] Assign loads to a construction stage
- [x] Analysis Construction stage settings ("tracking"/"ghost")

### Features Grasshopper 
- [x] Create construction stage component
- [x] Assign structure to a construction stages component **???**
- [x] Assign loads to a construction stage component **???**

The schema: [schema with construction stages.zip](https://github.com/strusoft/femdesign-api/files/8797220/schema.with.construction.stages.zip)

**Comment by xRadne** [comment]
Construction stages will be required for a project and it would be great to have as soon as possible (preferably 1-2 weeks).

Is this something that you could help with @Marco-Pellegrino @andosca? If not, no worries, I will do it soon.  
Ping @JRiad

**Comment by JRiad** [comment]
I think we should discuss this together before starting to implement. I got some info from Laszlo today that we need to consider, and I also think it is something that will require some thinking on design choices.

On the positive side, I really do not think it is that urgent and we should have enough time to come up with a good solution. I didn't think we'd get it implemented by Budapest until August... @xRadne we probably won't start coding on the project until at least end of June

**Comment by Marco-Pellegrino** [comment]
yep. It would be great to understand the case study.
I am really curious to understand the reason to use Construction Stages with the API

**Comment by xRadne** [comment]
Lets wait with this. My bad sorry. Closing this for now

**Comment by andosca** [comment]
I will re-open. Any discussion can continue in this case or elsewhere. I changed type from feature back to proposal to mark that it is just a proposal and should not be implemented yet as @JRiad points out above.

**Comment by xRadne** [comment]
The schema: [schema with construction stages.zip](https://github.com/strusoft/femdesign-api/files/8797220/schema.with.construction.stages.zip)

**Comment by Marco-Pellegrino** [comment]
It should fairly easy for the user to create Construction Stage analysis with the workflow shown in the picture.
A FemDesign user should be able to use it with any big issue. We will need to create some error handling as well.
i.e.

- assign only one load case for each stage
- stage need to have an unique name

Something that I haven't seen in any other objects regards the stage `xmlattribute` that reference the stage by Index.
For that reason, I have decided to create an `int StageId` to sort the stage.


![stage](https://user-images.githubusercontent.com/53620289/178458382-75cba535-1eb3-46d4-a231-e16718e27f03.png)

**Comment by Marco-Pellegrino** [comment]
@xRadne 
As you are going to be our first user for the feature, it would be great to check the behaviour of the code together.

I have managed to create two structure using the ConstructionStage (Bridge and High/Rise) and it should be a good starting point for understanding his behaviour

**Comment by Marco-Pellegrino** [comment]
still need to solve a Grasshopper related problem regarding a copy of the object.
i.e.
running a `model.create` twice with and without the stages will create an error because the elements have the stage assigned

**Comment by xRadne** [comment]
> @xRadne As you are going to be our first user for the feature, it would be great to check the behavior of the code together.
> 
> I have managed to create two structure using the ConstructionStage (Bridge and High/Rise) and it should be a good starting point for understanding his behavior

Will try it later this week! 

> still need to solve a Grasshopper related problem regarding a copy of the object. i.e. running a `model.create` twice with and without the stages will create an error because the elements have the stage assigned

Could you elaborate on this? Where in the code is the problem and do you have a test script for this specific problem? :)

**Comment by xRadne** [comment]
Overall it's very good! Everything we need is possible to do now using the API. 

Suggested improvements:
- Change `model.AddConstructionStages` to be `model.SetConstructionStages(stages, assignModifedElement, assignNewElement`. There can only be one list of stages (`FemDesign.ConstructionStages`) so it should be **Set** instead of Add. .
- Grasshopper component names: `Stage.Define` and `Stage` is confusing.
- ConstructionStages shouldn't be `IFemDesignEntity` and not `EntityBase` either.
- ConstructionStage index is not necessary. But is it useful to users? I think not. Marco thinks so. Let's discuss.

**Comment by Marco-Pellegrino** [comment]
@xRadne 
thanks for the review :)

There is only one little things to solve to then close the issue.
We should have a look together at:

> still need to solve a Grasshopper related problem regarding a copy of the object. i.e. running a model.create twice with and without the stages will create an error because the elements have the stage assigned

I am usually confuse about the DeepCopy and when use it. It might be one of the case where is needed

**Comment by xRadne** [comment]
### When to do DeepCopy?
The only time you need to do a DeepCopy is when a GH/Dyn component _modifies_ a field or property of an object from the input. 

This is because if a component modifies the input-objects fields. Then any other component that _also_ uses the same input will get the the updated value regardless of whether it is upstream or downstream. 

When we do a DeepCopy of the input, we instead have 2 different object and its ok to modify the second one without affecting the original object.


### Implications for Construction stages
Since all the grasshopper components only create new objects (ConstructionStages, ActivatedLoadcase) or creating the model with these objects then it is **not necessary to do a DeepCopy**.

**Comment by xRadne** [comment]
> still need to solve a Grasshopper related problem regarding a copy of the object. i.e. running a model.create twice with and without the stages will create an error because the elements have the stage assigned

@Marco-Pellegrino Can you show me an example of this problem? 😊

**Comment by Marco-Pellegrino** [comment]
@xRadne 
https://strusoftgroup.sharepoint.com/:f:/s/Automaticworkflow-projects/EvJcliCrGf5BgcGuL-DswxcBJcRmuGQRjkWmfYWPguDAXA?e=xUpg3t

Step to follow to get the issue:
Open the model through Gh **WITH** `Stage` connected to `model.create`
Open the model through Gh **WITHOUT** `Stage` connected to `model.create`

The latter will not be able to be open in FemDesign because the elements still have the previous StageId assigned.

**Comment by xRadne** [comment]
The problem is due to this line. Here the IStageElement is **modified**. 
https://github.com/strusoft/femdesign-api/blob/5b4ba8e5ad477428d593f9bc5f3d1fbf5a126760/FemDesign.Core/Model/Model.cs#L2756

I have not figured out how to fix this yet.

**Comment by Marco-Pellegrino** [comment]
> The problem is due to this line. Here the IStageElement is **modified**.
> 
> https://github.com/strusoft/femdesign-api/blob/5b4ba8e5ad477428d593f9bc5f3d1fbf5a126760/FemDesign.Core/Model/Model.cs#L2756
> 
> I have not figured out how to fix this yet.

Perfect!
I'll have a look and try to find a dirty solution :)

**Comment by Marco-Pellegrino** [comment]
https://github.com/strusoft/femdesign-api/blob/ea49b193a64709f6dc89d9f2cd840fa4e91f7c1c/FemDesign.Core/Model/Model.cs#L2756-L2757

Removed the problem that causing gh to reference the value to previously define object
