### ISSUE TITLE
Result Type

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#381]
Cleaning Result Type for Grasshopper.
Value List has way too more elements

**Comment by Marco-Pellegrino** [comment]
@xRadne @andosca 

What do you think about the "-------" line in order to subdivide the result type?
It should help a little bit the user in finding what they need.

![Result Type](https://user-images.githubusercontent.com/53620289/170240652-1b0c8943-dc3e-4b83-9461-8c4d91d50e7f.gif)

**Comment by andosca** [comment]
Since you can actually select it I think it is a bad idea.

**Comment by Marco-Pellegrino** [comment]
okay.
I'll remove the "----" option.
I had a look if there were a simple way to have it as "unselectable" but there were no such option.
In the future, we will definitely need something to help the user to quickly identify the results

**Comment by xRadne** [comment]
Why have many of the result types (such as Quantity estimations and line connection forces and RC design results) removed? :)

**Comment by Marco-Pellegrino** [comment]
we have removed it because we don't have a custom made deconstructor.
We believe that most of the user will get a bit confused if they can specify the ResultType and we don't provide the Deconstruct.
We will add them as we create the deconstructor.

btw, Expert users will still be able to specify resultType as per C#

Would you like to have a specific ResultType->deconstructor for the next release?
