### ISSUE TITLE
SectionDatabase component error

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#389]
I got an error message with SectionDatabase component. It doesn't work, but it has worked so far. I use 21.1.0. version of API in Grasshopper.

![image](https://user-images.githubusercontent.com/107181445/172814658-7b81892e-ac1e-40c8-87f7-e64506c2561b.png)

**Comment by andosca** [comment]
I think you might be using a pre-release that was compiled without assets. Try the latest release on food4rhino:

https://www.food4rhino.com/en/app/fem-design-api-toolbox
