### ISSUE TITLE
Footfall analysis

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#39]
- [x] Implement footfall analysis bool to analysis object:
https://github.com/strusoft/femdesign-api/blob/ee7be78930e8cf6a0bebde07594b165342a96df4/src/Calculate/Analysis.cs

- [x] Implement necessary loading object (footfall analysis data).

### Core
- [x] Add class Footfall
- [x] Add options to analysis
- [x] Test serialization/deserialization
- [x] Add Footfall elements to model (GenericLoadObject)
- [x] Update method `GetLoads`
### Grasshopper
- [x] Add node `Footfall.SelfExcitation`
- [x] Add node `Footfall.FullExcitation`
- [x] Add options to analysis
- [x] Add node for options
- [x] Test serialization/deserialization
### Dynamo
- [x] Add static constructor `Footfall.SelfExcitation`
- [x] Add static constructor `Footfall.FullExcitation`
- [x] Add options to analysis
- [x] Add static constructors to options
- [x] Test serialization/deserialization

**Comment by xRadne** [comment]
Waiting on internal issue 105715

**Comment by xRadne** [comment]
Footfall analysis comes in two types:
```xml
<footfall_analysis_data comment="This one has a hole" guid="c3fad152-30e4-489a-a81c-efb33ff77584" last_change="2021-05-21T09:54:38.000" action="added" name="SE.2">
  <contour>...</contour>
</footfall_analysis_data>
```
and
```xml
<footfall_analysis_data comment="Full excitation" guid="6c6b01b0-098a-44c9-a33a-c5908e39bfce" last_change="2021-05-21T10:11:42.000" action="added" name="FE.1">
  <position x="54" y="12" z="0"></position>
</footfall_analysis_data>
```

@andosca Should I: 
- Implement these two as 2 separate classes (`FootfallSelfExcitation` and `FootfallFullExcitation`) 
- or as a single class that has both property `contour` **and** `position`. These have to be null when the other is set.

**Comment by andosca** [comment]
@xRadne

Implement contour and position as nullable properties on the same class.

Have one constructor for each type of the class: Self/Full

You can have two private static instance counters on the object to keep track of instances created by the framework.

**Comment by xRadne** [comment]
# Important note!
Currently not possible to set number of finite elements per bar in `struxml` meaning that **the user must manually set** default setting "**Default minimum division number**" to something greater than 2.

**Comment by andosca** [comment]
> 
> # Important note!
> 
> Currently not possible to set number of finite elements per bar in `struxml` meaning that **the user must manually set** default setting "**Default minimum division number**" to something greater than 2.

This is OK.
