### ISSUE TITLE
Icon for Result deconstructors

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#401]
@xRadne @andosca @JRiad 
Not sure I have seen a specific icon in FemDesign.
It might be that we can have some "fun" with those.

Any idea?
There are going to be several output so we should be clever and minimise our effort in the task.

**Comment by xRadne** [comment]
Maybe we could ask the designer of the other icons to also do these in the same style? But with our directions :)

**Comment by Marco-Pellegrino** [comment]
What about using the "pencil" icon from FemDesign and personalised it with "n", "b" or "s" for node, bar, shell?

![image](https://user-images.githubusercontent.com/53620289/175883476-6059e667-f7ae-4774-a463-10df14f406ec.png)

The deconstructors are already grouped by "divider" in Grasshopper so it should easy to find the correct one among the other components
