### ISSUE TITLE
One point support component to rule them all

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#403]
- [x] #175

It would be nice if we could simplify the creation of supports by creating a custom component instead of the different components we have now
It should:
- have presets to choose for the most common cases (rigid/free for example, or toggles for each translation and rotation direction)
- be able to override those values for complex supports

It could look a bit like Karamba components. Custom components are a bit extra work but once we've done it once or twice it will be quick to create more.

**Comment by andosca** [comment]
I like it!

**Comment by JRiad** [comment]
> I like it!

Good! I thought perhaps this could be suitable for @lorinczandrea to work on? Seeing as it is not time sensitive and new for all of us. @Marco mentioned that Karamba is open source so it should be possible to look at their code to see how to create custom components. I've done custom components before as well, but it was looong ago so I don't really remember...

**Comment by JRiad** [comment]
Note: also include possibility to rotate #175

**Comment by xRadne** [comment]
Already implemented 
https://github.com/strusoft/femdesign-api/blob/master/FemDesign.Grasshopper/Supports/PointSupportSimple.cs
