### ISSUE TITLE
Apply design changes

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#404]
If the user is doing an auto-design, right now there is a manual step where they will have to apply changes and save the model.
Then they can read results into Grasshopper again.

Could this be automated?

**Comment by andosca** [comment]
Note: internal case 84341

**Comment by andosca** [comment]
Should implement and test the following command:

`<cmduser command="; CXL FEM $CODE(DESCHANGESAPPLY)" />`

**Comment by xRadne** [comment]
> Note: We need to notify the user in some way that they should perform a new analysis when design changes are applied. This is necessary in order to calculate a new stress/force distribution due to change in stiffness. Design changes applied might not be viable.

Can't we do the recalculate automatically from FdScript?

**Comment by Marco-Pellegrino** [comment]
FogBugz case created.

https://strusoft.fogbugz.com/f/cases/121465/ApplyDesignChanges-misbehaviour
