### ISSUE TITLE
Display more info on ToString()

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#406]
![image](https://user-images.githubusercontent.com/89396751/176151947-2772b8e5-fab5-419d-b30f-a1f3564d3f2b.png)
Deconstruct in several steps a bit annoying. Override string info so you get some information (Name) on different object types, like above

**Comment by xRadne** [comment]
**Good:** Easier to read/use!  
**Bad:** Performance. This is the reason it is often not done. But users often have far less than 10 000 loadcases/-combinations etc so should be fine
