### ISSUE TITLE
Rename FdPoint3d etc to only Point3d

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#411]
- `FdPoint3d` => `Point3d`
- `FdVector3d` => `Vector3d`
- `FdCoordinateSystem` => `CoordinateSystem`
- Etc.

**Comment by andosca** [comment]
Yes! Should be Point3d though IMO.

There was a caveat with Dynamos search function. Not sure if this causes problems elsewhere.

**Comment by xRadne** [comment]
> Yes! Should be Point3d though IMO.

I agree!
 
> There was a caveat with Dynamos search function. Not sure if this causes problems elsewhere.

Oh Dynamo... 🤖

**Comment by andosca** [comment]
Duplicate #467
