### ISSUE TITLE
Default arguments in Dynamo not working properly

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#42]
Default arguments for Connectivity, Eccentricity and EdgeConnections are not working properly. Objectreference null exception are thrown.

I guess that links are broken or that item vs array input is not working.

https://github.com/strusoft/femdesign-api/blob/3923efb9ec72458c0628fe75fe89ca99acf8c95b/FemDesign.Dynamo/Dynamo/Bars/Bar.cs#L28

Problem with:
- Bar.Beam
- Bar.Column
- FictitiousBar.Define
- Slab.*
- FictitiousShell.Define

**Comment by xRadne** [comment]
Some methods was missing. Adding

**Comment by andosca** [comment]
👾
