### ISSUE TITLE
Circular Edge Support

### ISSUE THREAD

**Issue by berkdemir** [strusoft/femdesign-api#424]
Hi all.

Software: Fem-Design + Grasshopper

Problem: The circular edge cannot be added as a hinge support. 
![image](https://user-images.githubusercontent.com/40423004/179471944-1f9a097e-45da-4972-830d-c194162a9933.png)

As you can see here https://github.com/strusoft/femdesign-api/blob/3ccbe9df9e87ce04fdfc6c7d3782a434ce742827/FemDesign.Grasshopper/Geometry/Convert.cs#L193
and here https://github.com/strusoft/femdesign-api/blob/3ccbe9df9e87ce04fdfc6c7d3782a434ce742827/FemDesign.Grasshopper/Supports/LineSupportHinged.cs#L63 the problem should be related to circle.

How do you reckon we can support the edge of a circular plate? I have also tried creating the slab and deconstructing it and getting the edge to hinge support, but that didn't also work.

**Comment by Marco-Pellegrino** [comment]
Hi @berkdemir !
I can reproduce the bug and I'll fix it ASAP.

As a quick hot fix, I would suggest to split the circle in two arches.
You might want to use CurveShatter in Grasshopper to achieve the split.

**Comment by Marco-Pellegrino** [comment]
Hi @berkdemir !
I have re-open the case so we will be able to notify you when the case is solved.

- [ ]  #425

**Comment by berkdemir** [comment]
Hi @Marco-Pellegrino 
Thanks for that. If anybody needs the workaround, this is how:
![image](https://user-images.githubusercontent.com/40423004/179732312-5f7a5893-be36-43f9-9b91-ba5b60f8a7c1.png)

I am still having trouble with support not applied to the model, but that's different issue (probably?) and I opened a ticket for that.

**Comment by berkdemir** [comment]
> You should have get a response for your ticket from me in your personal email :)

Thanks, waiting!

**Comment by Marco-Pellegrino** [comment]
@berkdemir 
The email has been sent few hour ago at your @niras.dk email.
Let me know if you haven't get anything that I'll provide you the solution in this thread

**Comment by berkdemir** [comment]
@Marco-Pellegrino ,
I have checked junk and freshdesk website, there is nothing. Can you sent again please, if possible?

**Comment by Marco-Pellegrino** [comment]
@berkdemir 
Let's simplify the process and download the latest release from the link below.
It should work as expected.

🔗 [FemDesign.Grasshopper.zip](https://github.com/strusoft/femdesign-api/files/9141116/FemDesign.Grasshopper.zip)

**Comment by berkdemir** [comment]
@Marco-Pellegrino 
Thanks, that works. 
Final question. I can see you updated the model.create component and I assume everything (shells, beams and supports) goes into the elements. But, I couldn't find the proper way to combine those elements before giving it to model.create. Merge didn't work, what do you use to combine?
(My model worked with OLD model.create).
![image](https://user-images.githubusercontent.com/40423004/179759122-c1e14b55-162f-496b-a10a-1a89610d7ef8.png)

**Comment by Marco-Pellegrino** [comment]
@berkdemir 
right click and "flatten" will create a single list.
I suggest you to have a look at some simple grasshopper tutorial regarding the DataTree for personal development.

![image](https://user-images.githubusercontent.com/53620289/179760813-1525680e-e685-4858-8177-2411bd9056b3.png)

**Comment by berkdemir** [comment]
I gave away my level with this question... :)
The GH component of FemDesign is so nice and intuitive, I have jumped right in, but I should go back to basics, you are right.
Thank you very much.

**Comment by Marco-Pellegrino** [comment]
@berkdemir 
We have been all in the same place where a "Tree" was really scary :)
If you manage to learn and understand the DataTree, you will be able to create some amazing structure with the API/Grasshopper

**Comment by berkdemir** [comment]
Hi,
I experience another problem with curve with hinge support. This time the curves are not circles, they are arc. But, still it doesn't work. Can you spot the problem?

[TrialSlab.zip](https://github.com/strusoft/femdesign-api/files/9168684/TrialSlab.zip)

**Comment by Marco-Pellegrino** [comment]
Hi @berkdemir 
We will need to create some casting to avoid the following error.
Meanwhile, use a "arc" container and it will work
![image](https://user-images.githubusercontent.com/53620289/180483058-1ed6f71a-a53d-439c-bbf8-3c8852202304.png)

**Comment by berkdemir** [comment]
Thanks for workaround. Since I need to use line & arcs, I have to do it one by one. Can you estimate anything more clever temporarily until the update of the GH code?
![image](https://user-images.githubusercontent.com/40423004/180483933-780ad255-b316-40c8-ad03-a0175c9d1cec.png)

**Comment by Marco-Pellegrino** [comment]
@berkdemir try the following grasshopper script.
We will create an automatic Cast in the next version

[TrialSlab_RevMP.zip](https://github.com/strusoft/femdesign-api/files/9179727/TrialSlab_RevMP.zip)
