### ISSUE TITLE
Aligning Load Cases in GH with GUI

### ISSUE THREAD

**Issue by berkdemir** [strusoft/femdesign-api#428]
Hi,
I would recommend to align the load case types in Grasshopper with GUI.
Why "static" in GH while "Ordinary" is used in GUI? 
dead_load --> structural_dead_load
![image](https://user-images.githubusercontent.com/40423004/179761478-41580e25-4327-4fc1-8916-8ae3c0fc94b5.png)
![image](https://user-images.githubusercontent.com/40423004/179761369-98cb74a7-b821-4b4c-99d1-f1eeffe2a571.png)

**Comment by andosca** [comment]
Related to https://github.com/strusoft/femdesign-api/issues/186

**Comment by andosca** [comment]
@berkdemir The naming is inherited from the xml-schema which differs from the GUI. We can implement some more parseable alternatives and update the component description, for example dead load:

https://github.com/strusoft/femdesign-api/blob/eff8445c1e6543bdf1c588e7dc9c5f69f7b7d0cc/FemDesign.Core/Loads/LoadCaseTypeEnum.cs#L23-L28

@xRadne Not sure if spacings are allowed?

**Comment by berkdemir** [comment]
@andosca 
Got you. But I still would use the FEMDesign GUI's notations and convert it to xml schema internally.

**Comment by xRadne** [comment]
@andosca No space characters will be trimmed. Only exact matches are valid. 

The fix has been written a while ago, but it was never merged. Please go ahead and merge this @andosca or @Marco-Pellegrino :)
https://github.com/strusoft/femdesign-api/commit/e42fb39a601765c14f4e5a39279594f1bb1b6eef

**Comment by andosca** [comment]
@berkdemir Would a predefined grasshopper value-list be useful as well to find the correct type?

**Comment by berkdemir** [comment]
If #384 comes to life, none of these would be necessary as you can just show the user whatever list you like without interfering with your backend. 
I would love that.

**Comment by andosca** [comment]
- [ ] Merge https://github.com/strusoft/femdesign-api/commit/e42fb39a601765c14f4e5a39279594f1bb1b6eef with 21.3.0

**Comment by andosca** [comment]
- [ ] Merge https://github.com/strusoft/femdesign-api/commit/e42fb39a601765c14f4e5a39279594f1bb1b6eef with 21.3.0

**Comment by Marco-Pellegrino** [comment]
@berkdemir 
I have updated the description to match as close as possible FemDesign GUI.
`static`has been converted to `ordinary`.
I have left `dead_load` as it is because it is quick to write and it is pretty obvious that it is equivalent to `structural_dead_load`.

![image](https://user-images.githubusercontent.com/53620289/180011539-bf40f142-b105-41d9-bb2c-a531bc059787.png)

**Comment by berkdemir** [comment]
Thanks. I agree it id obvious, static was obvious anf actually better than ordinary. But when I was building the GH script, I check the Femdesign GUI, which was confusing.
What about compatibility with previous version? I would suggest you keep both ordinary and static, with static in the description. Structural dead load and dead load with structural dead load in description. 
Of course this decision might differ based on the design decision, mine is only suggestion and feel free to close again if you disagree.
