### ISSUE TITLE
Convert.cs Bad Outline Problem

### ISSUE THREAD

**Issue by berkdemir** [strusoft/femdesign-api#430]
Hi,
I am having a trouble when I split the surfaces into smaller elements. I am not sure the cause, but it seems like my start and end points of surfaces are not same, but I cannot understand why it causes a problem.
I am at the last phase of a good showcase of a GH-FemDesign use. 🙂 
[ConvertcsProblem.zip](https://github.com/strusoft/femdesign-api/files/9175361/ConvertcsProblem.zip)

**Comment by Marco-Pellegrino** [comment]
@berkdemir 
Rebuilding the surface seems to solve the problem.
Here my solution.
Looking forward seeing your case :)

[ConvertcsProblem_RevMP.zip](https://github.com/strusoft/femdesign-api/files/9179820/ConvertcsProblem_RevMP.zip)

**Comment by berkdemir** [comment]
Hi @Marco-Pellegrino 
Thanks for the workaround, but it is not a good solution for my case since circular edges and rebuilding with brep does not work well, causes mesh errors at the edges. Thanks though!

**Comment by andosca** [comment]
Probably related to #279
