### ISSUE TITLE
Physical Alignment

### ISSUE THREAD

**Issue by berkdemir** [strusoft/femdesign-api#438]
Proposal. Adding two components for physical alignment:
1. Same with eccentricity define - PhysicalAlignment.Define that takes x, y, z.
2. For bars, adding a new input for Physical Alignment. If user gives input, it takes the input which makes `use_default_physical_alignment = false` and uses that value. If not, it is `true`.
![image](https://user-images.githubusercontent.com/40423004/181214690-880ef76a-7890-4a1f-bc38-8140162e1492.png)

**Comment by Marco-Pellegrino** [comment]
thanks @berkdemir

**Comment by Marco-Pellegrino** [comment]
@berkdemir 
I have moved out the issue from the milestone. However, in the next release the `use_default_physical_alignment` will be equal to false and the user will need to specify the AnalyticalEccentricity.

We do believe that there shouldn't be any hidden automation that would make the user confuse.

i.e. The Phisical Alignment does not change any stiffnes in the element and therefore the user should see the element in the right position without any "dummy" eccentricities.
