### ISSUE TITLE
LoadCombination => CombItem casting

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#44]
Add CombItem default values on LoadCombination and add casting method to facilitate setting up analysis.

Basically avoid this:
```c#
var combItem = new FemDesign.Calculate.CombItem(0, 0, NLE, PL, NLS, Cr, _2nd);
int numLoadCombs = model.Entities.Loads.LoadCombinations.Count;
//var combItems = new FemDesign.Calculate.CombItem[numLoadCombs];
var combItems = new List<CombItem>();
for (int i = 0; i < numLoadCombs; i++)
{
  combItems.Add(combItem);
}
Comb comb = Comb.Define();
comb.CombItem = combItems.ToList();
```

**Comment by Marco-Pellegrino** [comment]
@andosca 
Not sure you were thinking at the same but below my solution.

`CombItem` object is linked to the `loadcombination` object in the constructor.
Constructor can be left empty and a `CombItem.Default()` will be created.

https://github.com/strusoft/femdesign-api/blob/965f885f031151387a8a6b72a50b7a87952f8cb9/FemDesign.Examples/C%23/Example%203%20-%20Analyse%20a%20beam/Program.cs#L76-L84

CombItem will create a reference to `Comb` automatically when RunAnalysis() is called.

**Comment by Marco-Pellegrino** [comment]
instead, If the user wants to run a model from Application.RunAnalysis(), it will need to specify the CombItems in the Comb Constructor.

We should be able to cover several case such as:
- user that crate a model from scratch => model.RunAnalysis()

- user that read a model from the .str => Application.RunAnalysis(filePath, analysis)
