### ISSUE TITLE
Result parser max of load combinations of point support reaction forces

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#449]
Implement parser to allow user to get max of load combinations for the result type of interest.

- [x] C#

- [x] Grasshopper
- [ ] #526

**Comment by andosca** [comment]
Support case: 18419

**Comment by andosca** [comment]
@Marco-Pellegrino 
The result of interest was max of load combinations for point support reactions.

**Comment by Marco-Pellegrino** [comment]
@andosca 
Perfect!

**Comment by Marco-Pellegrino** [comment]
@andosca 
Just in case you want to make the user feeling part of the development, here a screenshow

![image](https://user-images.githubusercontent.com/53620289/190189164-b4cc2036-71dc-4fe7-8a2e-7a8c3dd49fd4.png)

**Comment by andosca** [comment]
Did you implement this in Dynamo aswell?

**Comment by Marco-Pellegrino** [comment]
> Did you implement this in Dynamo aswell?

nope :/
Let's do it then

**Comment by andosca** [comment]
Dynamo part is waiting on #498, will plan for 21.5.0.

**Comment by andosca** [comment]
@Marco-Pellegrino If this is tested in C# and GH you can close this issue.
