### ISSUE TITLE
Bars.Beam is very slow in 21.2.1

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#452]
A hundred beams takes 10 seconds in version `21.2.1` but used to be instant previously. I think this has to do with the default material and sections. 

![image](https://user-images.githubusercontent.com/32938476/182568996-d408f483-ca23-4226-8ab4-970fed6f1613.png)

**Comment by Marco-Pellegrino** [comment]
yes :)

Inputting a Section and Material would make the component behave as before.

The script is Deserialising the database for everybeam.
Needs to be fix with cache or other as you suggest

**Comment by xRadne** [comment]
Implementing a cache for SectionDatabase and MaterialDatabase
