### ISSUE TITLE
:bug: Section.Define uses wrong profile

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#455]
Before | FEM-Design | After
--- | --- | ---
![image](https://user-images.githubusercontent.com/32938476/183611031-8f90e5ff-81ef-4df2-adef-5bd6e5bc9481.png) | ![image](https://user-images.githubusercontent.com/32938476/184638053-2305e419-7397-43cb-af2d-9947506dc99b.png) | ![image](https://user-images.githubusercontent.com/32938476/183611160-597c65ea-8984-45f3-8245-4cb060972337.png)

Testfile in testfolder 455

**Comment by xRadne** [comment]
@andosca Do you recall if this used to work for sections like this? I'm trying to figure out if this is an old bug or if it showed up recently.

**Comment by xRadne** [comment]
When I do UntrimSurface before Section define then the section is created as a rectangle. Therefore I think this is a problem with the `FemDesign.Geometry.Convert.FromRhino(Brep brep)` and that it is taking the wrong curves to create the region. 

![image](https://user-images.githubusercontent.com/32938476/184872153-e00146bc-6af4-40c4-8737-37afd98a1eeb.png)

![image](https://user-images.githubusercontent.com/32938476/184872779-15464247-fe62-4613-90d7-cfa0e65984b2.png)

**Comment by andosca** [comment]
@xRadne It used to work for the cases that I tested. This is/was also used by a user extensively. It could be so that the type of `brep` that you are using exposes a bug never found before.

**Comment by Marco-Pellegrino** [comment]
The bug was occuring due to BoundaryEdges of the Brep being a collection of PolyCurve.
Exploding the polycurve and reconstruct the surface from the new boundary would make the code working.

It is now possible to avoid the "explosion" of the boundary curves. The code take care of that

**Comment by xRadne** [comment]
Is this fixed in C# or do users need to use the workaround in Grasshopper?

**Comment by Marco-Pellegrino** [comment]
It has been fixed inside C# in the Convert class.
