### ISSUE TITLE
Design results

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#456]
I would love to have some design results available for C# and Grasshopper

### RC
- [ ] #476
- [ ] RC `Shell, Utilization` *
- [ ] RC `Shell, Crack width` *

### Steel
- [x] Steel `Bar, Utilization`

### Timber
- [ ] Timber `CLT panel, Utilization`
- [ ] Timber `Bar, Utilization` (maybe?)

* Available in C# already ([link](https://github.com/strusoft/femdesign-api/tree/master/FemDesign.Core/Results))

**Comment by Marco-Pellegrino** [comment]
@xRadne 
I am not sure I can see the Steel BarUtilisation parser.
Can you double check?

**Comment by xRadne** [comment]
I have added it to the Feature branch 🙂 https://github.com/strusoft/femdesign-api/commit/ef2435bfeb3e898dfba10be2032e815ccd866879

**Comment by Marco-Pellegrino** [comment]
It might require some time before they fix it. 
Case creataed on https://strusoft.fogbugz.com/f/cases/121973/Add-Beam-Type-to-Result-List

**Comment by andosca** [comment]
Ok to remove this case from `21.4.0`.
