### ISSUE TITLE
Design groups

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#457]
Create and use design groups in the API

**Comment by Marco-Pellegrino** [comment]
Going to create a case on FogBugz.
It is a MUST have feature

**Comment by xRadne** [comment]
> Going to create a case on FogBugz. 
> It is a MUST have feature

I agree! 😎

**Comment by Marco-Pellegrino** [comment]
https://strusoft.fogbugz.com/f/cases/121605/Design-Group-API
