### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#458]
Sometimes this very strange bug shows up... 

Version: `21.2.1`

Model.Create, this time but seen it also on Analysis.Define

![MicrosoftTeams-image](https://user-images.githubusercontent.com/32938476/184090586-581210ce-044b-40b8-b26b-8cb10088f15b.png)

**Comment by andosca** [comment]
In what circumstance would this be reproduced? Randomly or during some specific task?

**Comment by xRadne** [comment]
Can't reproduce anymore. Unknown what caused this to begin with.
