### ISSUE TITLE
Add get material method to database object

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#46]
Add GetMaterialByNameOrIndex method to MaterialDatabase object.

https://github.com/strusoft/femdesign-api/blob/74740e03ddfd358b1e8acbe3551f69f2bd655ed1/FemDesign.Core/Materials/Material.cs#L59-L86

This should be a non-static method on the MaterialDatabase class instance:

```csharp
var materialDb = new MaterialDatabase()
var material = materialDb.GetMaterialByNameOrIndex("myName")
```

Also:

- [x] https://github.com/strusoft/femdesign-api-docs/issues/2

**Comment by xRadne** [comment]
Why a non-static method? @andosca

**Comment by xRadne** [comment]
What is the purpose of the MaterialDatabase? Why not remove it completely and work with List<Material> instead? 

```C#
List<Material> concreteMaterials = MaterialDatabase.Concrete;
var material = concreteMaterials.Find(m => m.Name == "C30/37");
```
Or 
```C#
Dictionary<string, Material> concreteMaterials = MaterialDatabase.Concrete;
var material = concreteMaterials["C30/37"];

// Same as
var material = MaterialDatabase.Concrete["C30/37"];
```

Or
```C#
var materialDb = new MaterialDatabase()
var material = materialDb["C30.37"]
```

**Comment by andosca** [comment]
It does not matter. Personally, I just don't like the current set-up in C#:

```csharp
var materials = Materials.MaterialDatabase.GetDefault().Materials.Material;
var material = Materials.Material.GetMaterialByNameOrIndex(materials, "materialName");
```

I makes sense in GH:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/52665994/199026337-7dca2f4a-9c3e-462b-a45f-bb19e3cc1702.png">

So my go to alternative is as stated in the issue, for me this is an improvement worth implementing. If you want to take lead feel free to specify this the way you seem fit. If you prefer the current way - this is OK as well.

**Comment by Marco-Pellegrino** [comment]
The current way to select a material or section is the following and it looks generally good and easy to work with.
```csharp
  var materialsDB = Materials.MaterialDatabase.GetDefault()
  var material = materialsDB.MaterialByName("C35/45");
```

However, the Static Method that I have wrote some times ago make sense only for Grasshopper and I have moved it inside the FemDesign.Grasshopper assembly.

C# users doesn't need it.
