### ISSUE TITLE
Test pipe to open process

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#464]
Test to implement pipe to open process.

Use framework on codecommit.

Try to figure out how to implement this functionality to fit with our API toolbox.

**Comment by xRadne** [comment]
Maybe I could do a test where I try to optimize a model by repeatedly updating the elements, running the analysis then reading the results etc. 

This could be a great test to do something that cant be done at the moment without opening and closing the models several times.

**Comment by andosca** [comment]
Sure. Our goal is to have an idea of how to implement the feature by the end of this milestone. The idea is to do the implementation in the next milestone.

**Comment by Marco-Pellegrino** [comment]
@xRadne 
Should we try this together on Monday while I am in Göteborg? :)

**Comment by xRadne** [comment]
> @xRadne Should we try this together on Monday while I am in Göteborg? :)

Yes!!! Great idea!

**Comment by andosca** [comment]
https://github.com/strusoft/femdesign-api/tree/464-pipe
