### ISSUE TITLE
Rename remove Fd from the `Fd`-classes, e.g. FdPoint3d => Point3d

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#467]
- [ ] FdCoordinateSystem
- [ ] FdPoint2d
- [ ] FdPoint3d
- [ ] FdVector2d
- [ ] FdVector3d

**Comment by Marco-Pellegrino** [comment]
https://github.com/strusoft/femdesign-api/commit/2633c9a9fa2bdb8a0ee8b9e6f4e95d35be9746ec
