### ISSUE TITLE
Guide how to add material/section from FD to your current project

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#469]

**Comment by xRadne** [comment]
Example script #257

**Comment by andosca** [comment]
The guide would include a how-to save your assets from FEM-Design to file and then load them in your project. I will have a look at the example. This guide would be a tutorial/documentation rather in our future documentation.

**Comment by Marco-Pellegrino** [comment]
@andosca 
Should if be a Guide/Tutorial for Grasshopper?
I was thinking to create a quick article and place it in our Docusaurus Blog section

**Comment by Marco-Pellegrino** [comment]
it will be available for users when we publish our docusaurus.

It has been written in a form of "blog"
