### ISSUE TITLE
Add get section method to database object

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#47]
Add GetSectionByNameOrIndex method to SectionDatabase object.

https://github.com/strusoft/femdesign-api/blob/74740e03ddfd358b1e8acbe3551f69f2bd655ed1/FemDesign.Core/Sections/Section.cs#L132-L159

This should be a non-static method on the SectionDatabase class instance:

```csharp
var sectionlDb = new SectionDatabase()
var section = sectionlDb.GetSectionByNameOrIndex("myName")
```

Also:

- [x] https://github.com/strusoft/femdesign-api-docs/issues/3

**Comment by andosca** [comment]
Duplicate of #95

**Comment by Marco-Pellegrino** [comment]
Not necessary method for C# users.

The static method has been moved inside Grasshopper assembly
