### ISSUE TITLE
Can't deconstruct FeaNodes from FeaModel

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#479]
![image](https://user-images.githubusercontent.com/52665994/188113952-3f3d5fa2-28e0-4782-aa8d-017940daedb5.png)

The issue should be reproducible with any model I suppose.

I get the following exception:

`Solution exception:Input parameter index [-1] too low for Component FdFeaModel.FeaNode`

See attached nodes:

[FeaNode.csv](https://github.com/strusoft/femdesign-api/files/9476920/FeaNode.csv)

**Comment by Marco-Pellegrino** [comment]
fix
https://github.com/strusoft/femdesign-api/commit/f9c5025f60f8a3e1a6a385e7ed2b83c9476c40b8
