### ISSUE TITLE
Sorting Grasshopper panel in the same way as in FEM-Design

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#481]
The different parts of the panels are now sorted alphabetically. It would make more sense if they followed more of a logic, prefereably the same as in FEM-Design (geometry -> loads -> analysis -> design). I think an easy way to achieve this would be just naming the different parts with numbers:
1. Model
2. Help
3. Bars
4. etc

![image](https://user-images.githubusercontent.com/89396751/188139535-6fd0afb1-031f-4e6f-b85f-ede93d0ad41b.png)

**Comment by andosca** [comment]
Do you think it is difficult to find the components? 

I don't necessarily disagree with your idea, but I think this was evaluated once and there are a lot of components that don't exist in the GUI ribbons. This **could** make it more confusing and then it **might** be easier to find things by alphabetical order anyway.

**Comment by JRiad** [comment]
I don't think it is that difficult but a lot of customers comment that the order makes no sense

**Comment by Marco-Pellegrino** [comment]
@andosca 
I was having the same feeling as @JRiad while I was creating some example files.
I agree that we should make the order logical using more or less the order of FemDesign (Elements, Loads, Analysis, Results)
Let's discuss it together on Monday
