### ISSUE TITLE
Model.RunAnalysis and Model.RunDesign return void

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#487]
Model.RunAnalysis and Model.RunDesign return void. How do I know when the process is finished?

https://github.com/strusoft/femdesign-api/blob/f9c5025f60f8a3e1a6a385e7ed2b83c9476c40b8/FemDesign.Core/Model/Model.cs#L331-L348

**Comment by andosca** [comment]
Notes to self:

Remove RunAnalysis/RunDesign from Model? Rename FdApp on Model to something else? Model.Calculate.Run*, Model.App.Run*, Model.Analyse, Model.Design?

**Comment by xRadne** [comment]
@andosca I think that the pipe Connection class could be joined with the FemDesign.Calculate.Application class to handle all interactions with the main software
