### ISSUE TITLE
Publish nuget actions

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#49]
Publish nuget on push to master?

https://github.com/marketplace/actions/publish-nuget

**Comment by xRadne** [comment]
# Github release on new tag
Consider also publishing a release and release artifacts (Grasshopper and dynamo packages) on new tag. 

This can be done using something like [github-releases action](https://github.com/marketplace/actions/github-releases).

Maybe this can then also publish an installer if we implement #37

**Comment by xRadne** [comment]
To be able to publish nuget automatically we need to
- [ ] include the package icon in the repository
