### ISSUE TITLE
UPDATE: Prompt the user if BoundingBox is very big

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#490]
UPDATE: Problem seems to stem from the units used in the Rhino model. In both #279 and #282, the surfaces used were imported from a model using millimeters instead of meters. 

I never realized this, but looking back, it should have been obvious - since the FEM-Design model is about four kilometers wide and eight kilometers long...

Changing the Rhino unit to meters - and scaling the model by 0.001 - removed the problem both for #279 and #282.

So, it seems this might be another problem entirely. Is there a way to read units from Rhino and send it to FEM-Design to avoid this problem? Otherwise, it might just be a "user will have to figure it out" type of problem...

_Originally posted by @samnyb in https://github.com/strusoft/femdesign-api/issues/282#issuecomment-1074915827_

**Comment by Marco-Pellegrino** [comment]
Looking back at this error, I have just realise that it might be nice to prompt the users if their rhino model is not in Meter to avoid some mistake that can occurs while doing FEA.
It is also good practice to write some info about the model to get a simple feeling about the dimension.
BoundingBox dimensions can be a nice value to display (text is more than enough) as output of Model.Create

**Comment by andosca** [comment]
From my experience helping people solve this type of bug, now that you mention it, I suspect scaling was the solution for them as well.

**Comment by andosca** [comment]
Could we throw an expection when the user is using [mm] model space?

Bounding box model info sounds like a good idea.

**Comment by Marco-Pellegrino** [comment]
Based on a Team Conversation

- [ ] Raise a warning if RhinoModel is not in meter

- [ ] implement BoundingBox output in "model.create"

- [ ] Raise a warning if the model has a bounding box more than 1000 m

**Comment by xRadne** [comment]
> Could we throw an expection when the user is using [mm] model space?

What if someone wants to model in mm? Do they get a warning then? 
Is it not better to scale the tolerances? So that it is possible to model a small model in mm? 

I don't know if it's better. I just want to discuss this possibility.

**Comment by Marco-Pellegrino** [comment]
User will still be able to have the RhinoUnits in mm but the geometry input will still need to be input as it was in meter.

Our current workflow in Gh do not allow to input a line with length == 1'000 mm because for FenDesign will be 1000 meter.
