### ISSUE TITLE
💬 Rename the milestone branch `next`

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#492]
I propose we name the milestone branch `next`. 

Instead of having a branch called 21.3.0 or something I think it is better to have the current latest changes on a branch named next. 

Other names could be `alpha`, `dev` or `current` but I think `next` is common name for the changes that will be released but have not yet got a version number

**Comment by andosca** [comment]
I guess this is kind of what is proposed: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow?

What problem are we solving by introducing this workflow (not the one in the link specifically)?

**Comment by xRadne** [comment]
The problem we are solving is that a branch and a git tag can't have the same name (such as 21.4.0)
![image](https://user-images.githubusercontent.com/32938476/189588290-8c1b6790-0837-4da7-9dde-94de5a4e4d99.png)

**Comment by andosca** [comment]
I don't think I ever experienced that, maybe by some coincidence. I would usually merge the milestone branch with master, then delete it, and then I would publish the release with the tag named as the milestone. The tag would point to master.

I still think it makes sense to keep the milestone branch named as the milestone in some way, and I still think it should be deleted when merged to master. 

@Marco-Pellegrino Do you have any opinion about this, this mostly affects you.

**Comment by Marco-Pellegrino** [comment]
I have experience the problem last time while trying to create the release but it was not a big problem.
I have solved it renaming the branch with some additional test and That's the reason for currently have a  branch called "21.4.0_branch"
