### ISSUE TITLE
investigate dynamo errors in 21.4.0

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#498]
#449

**Comment by andosca** [comment]
@Marco-Pellegrino 
See https://github.com/strusoft/femdesign-api/commit/c05d6f877defe821d5db4095529dbcc39cd03fed for attempt to fix build errors. Result reader errors still persists. But this is a good indicator of what needs to change.

I think a good start would be to redo my process as you might have more insight to consequences of my proposed changes. Maybe try to remove all Core links and re-link them altogether. The linking process is not optimal tbh.

**Comment by xRadne** [comment]
**Everything works** at commit on `21.2.1`

But I can **not** build dynamo package on commit 87ddcdc on `21.3.0` 
However, Visual Studio tells me it has rebuild everything, but there are no files in folder `FemDestign.Dynamo/bin/Debug` and there are no build errors (but 1998 warnings, mostly about missing xml comments).
![image](https://user-images.githubusercontent.com/32938476/191298186-d5ef2cb9-4471-4862-b1a0-a07390ad60bc.png)

**Comment by Marco-Pellegrino** [comment]
One of the possible reason to do not see any .dll for Dynamo is that I have "disable" the build for Dynamo in the Solution Settings.

**Comment by xRadne** [comment]
What do you mean by "disable"? And how do I enable the build again? :)

**Comment by xRadne** [comment]
@andosca @Marco-Pellegrino Did any one of you create a test report or a summary of the tests that were done before releasing 21.3.0? :)

**Comment by andosca** [comment]
> @andosca @Marco-Pellegrino Did any one of you create a test report or a summary of the tests that were done before releasing 21.3.0? :)

What tests are you referring to?

**Comment by xRadne** [comment]
> What tests are you referring to?

Did dynamo work when we released 21.3.0?

**Comment by xRadne** [comment]
Wait I just found the problem why I can't compile FemDesign.Dynamo... 


### Problem
There are a lot of files from FemDesign.Core that have not been linked in the project FemDesign.Dynamo.

**Comment by xRadne** [comment]
> Hi there.
> I am try to build a library and I have managed to create a .dll without any error.
> Otherwise, I can not load the project into Dynamo. Anyone has an idea on how to fix the problem?
> I can not really understand what to look for

> ![image](https://user-images.githubusercontent.com/32938476/191445755-c5b5cab6-3e1a-48c0-ae9d-9f00dceec8cb.png)

On dynamo forum https://forum.dynamobim.com/t/error-in-creating-ast-node/81251

**Comment by xRadne** [comment]
@andosca @Marco-Pellegrino as we discussed I did remove all `[DefaultArgument()]` attributes. 

**But the Dynamo package could not be loaded**

![image](https://user-images.githubusercontent.com/32938476/191458907-6074820a-2aca-4512-ad84-71a6a41db0b5.png)

**Comment by Marco-Pellegrino** [comment]
what about investigating the new results workflow?
There has been a difference on that part as well that was making the DynamoComponent to do not compile

**Comment by andosca** [comment]
This is a new type of error though? 👍

**Comment by Marco-Pellegrino** [comment]
AST node error was in the "show details"

**Comment by xRadne** [comment]
### Log
First breaking commit 27c7c3d8f47ae2b256ed887065e3265af4f60207

**Comment by Marco-Pellegrino** [comment]
> ### Log
> 
> First breaking commit [27c7c3d](https://github.com/strusoft/femdesign-api/commit/27c7c3d8f47ae2b256ed887065e3265af4f60207)

is it a breaking change because it has not been reference in Dynamo and therefore it was failing to built?

**Comment by xRadne** [comment]
> >### Log
> >   First breaking commit [27c7c3d](https://github.com/strusoft/femdesign-api/commit/27c7c3d8f47ae2b256ed887065e3265af4f60207)
> 
> is it a breaking change because it has not been reference in Dynamo and therefore it was failing to build?

Yes!

**Comment by xRadne** [comment]
Bug here: https://github.com/strusoft/femdesign-api/pull/422#discussion_r982035771

**Comment by xRadne** [comment]
After 14h I found the bug 😅

**Comment by Marco-Pellegrino** [comment]
@xRadne 
Should we run any specific test? Super happy for you to merge!
I'll go through the test tomorrow anyway but I would suggest to don't make any "official release" for Dynamo

**Comment by xRadne** [comment]
Fix found 0f579b0d251afe715b4f8317ca8d28facef8b330
