### ISSUE TITLE
Consider Refactoring EntityBase

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#499]
This is how I imagine it. Please tell me what you think :)

Classes | Base class | Properties
--- | --- | ---
Bar, Shell, Support, ... | EntityBase | Name (`"B.3"`), Instance, Identifier, LockedIdentifier
BarPart, SlabPart, ... | ** | Name* (`"B.3.1"`), Instance*, Identifier, Suffix (`".1"`), LockedIdentifier
Loads | LoadBase ** | -
LoadCase | ** | Name (`"DL"`)
LoadCombination | ** | Name (`"ULS"`)
LoadGroupPermanent, LoadGroupTemporary | LoadGroupBase | Name *** (`"Load group 1"`)

*Instance number and Name should be the same as for Bar/Shell. 
**Should not be EntityBase any more.
***Don't know if a LoadGroup can have a name in FEM-Design

_Originally posted by @xRadne in https://github.com/strusoft/femdesign-api/issues/81#issuecomment-1251913054_

**Comment by Marco-Pellegrino** [comment]
The refactoring might help c# developers to work with our source code.

**Comment by andosca** [comment]
I tried to follow the thread in #81 as good as I could. I might be stating some obvious things, if so I apologise for this.

How to implement locked numbering:

https://github.com/strusoft/femdesign-api/blob/4d74ab85d67a43c7a104856cc80120a92af609ea/FD%2021.01.003.xsd#L524-L528

Note that if two names share prefix and number FEM-Design will overwrite the number of one of them arbitrarily. 

In my opinion this means that we can never implement a way to secure numbering for the user. The user can always define prefix and numbers that are identical, even if they lock the number using `@`. 

The idea for the need of the #81 case was that in some cases `Identifier` was used as property name and sometimes `Name` was used, if I'm not mistaken. This could have been confusing for users trying to set the `Identifier`. However, the idea was never to give the user a water-proof solution to numbering.

So the whole purpose of this case is only to have consistency regarding how the user can set the `Name` basically using `Identifier`. Number (`Instance`) can for all I know be read-only.  In a way this falls back to FEM-Design arbitrarily setting the number - so there are a lot of ways for the user to make a mess. 

If the user wants to read a certain result, it makes sense to give the user the `Name` set by FEM-Design as this is a result identifier. In this case the user needs to read the `Name` that FEM-Design has set which is ok.

**Comment by andosca** [comment]
@xRadne Where does entity base come into all of this? Does it not only set dates and guid?

**Comment by andosca** [comment]
#511
