### ISSUE TITLE
Lock Numbering

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#500]
Investigate what it is happening in the renumbering process in FEM-Design.

From an initial test, the `@` can not be serialise from FEM-Design (save as does not create any `@` in the `.struxml`)

@xRadne Finding

> To be honest I don't fully understand this either.
> 
> But here is 1 example I know:
> 
>     1. Draw 3 bars in FEM-Design: (They will be named B.0, B.0, B.0)
> 
>     2. Save the file as struxml: (They will be renamed to B.1, B.2, B.3)
> 
>     3. Read the model using the API: (Still named B.1, B.2, B.3)
> 
>     4. Add another bar to the model (The 4 bars will be named B.1, B.2, B.3, **B.1**)
> 
>     5. Open the model in FEM-Design (They will be renamed to B.1, B.2, B.3, B.4)
> 
> 
> Note that the bar added in step 4 will now be named **B.1**, while the bar originally named B.1 is now named B.2 etc.
> 
> (edit) If we then continue: 6. Manually edit the struxml to change one of the bars named B.1 to instead be called @B.7 (Nothing changes, they will be renamed to B.1, B.2, B.3, B.4 7. Change it back to B.1. 8. Manually edit the struxml to change the `bar_part` of one of the bars named B.1.1 to instead be called @B.7.1 (They will be renamed to **B.7**, B.8, B.9, B.10)
>

**Comment by xRadne** [comment]
Open this file ([Bar with @.struxml.txt](https://github.com/strusoft/femdesign-api/files/9606324/Bar.with.%40.struxml.txt)) and then save it as struxml and you will see the "@" will still be there. But it is hidden in the GUI in FEM-Design.

**Comment by andosca** [comment]
@Marco-Pellegrino Is still still relevant?

**Comment by Marco-Pellegrino** [comment]
The biggest issue that I see regarding "renumbering" is when the user wants to get some specific result related to some element.
Looks like "name" or identifier might cause some problem if it is not done carefully.

I am not sure if it is fully solvable tbh.

**Comment by andosca** [comment]
> The biggest issue that I see regarding "renumbering" is when the user wants to get some specific result related to some element.

That would be solved by introducing GUID in the output list from FEM-Design. It will be difficult to solve with locked numbering as a user can still have identical locked position numbers.

**Comment by Marco-Pellegrino** [comment]
> That would be solved by introducing GUID in the output list from FEM-Design. It will be difficult to solve with locked numbering as a user can still have identical locked position numbers.

Yes. I agree that it is the best way to go.
Karamba3d, for example, is using the Index to select the desired element as it is unique.

**Comment by andosca** [comment]
#390
