### ISSUE TITLE
Can't read model with Construction stage with PTC loads

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#501]
Saving a struxml file with a stage with post tensioning cables cannot be deserialized by the API.

![image](https://user-images.githubusercontent.com/32938476/191500681-8d2dd7ed-88e5-4f6a-88a0-0be745349499.png)

The problem is due to the `case` attribute in activated_load_case that can either be a guid or this "ptc_t8" name here.

![image](https://user-images.githubusercontent.com/32938476/191500613-291de046-ad63-4913-b012-8775cef9a48c.png)

ActivatedLoadCase (`cs_lc_type`) have an attribute case (`load_case_cs`) that can be any of the following types: 
`guidtype`, `indexed_guid`, `lc_ptc_type`, `lc_pile_type`
![image](https://user-images.githubusercontent.com/32938476/191740192-84111ea2-8eea-45e9-adb3-8722115f70ef.png)
![image](https://user-images.githubusercontent.com/32938476/191740427-ff9e7e84-69b6-4960-a9ed-bae5e0a07572.png)

**Comment by andosca** [comment]
Was this merged to 21.4.0?

**Comment by xRadne** [comment]
> Was this merged to 21.4.0?

Yes! 

![image](https://user-images.githubusercontent.com/32938476/192708155-a73f0968-5d2a-4720-b20f-860716d3081a.png)
