### ISSUE TITLE
Can't create construction stage with multiple load cases

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#502]
A single stage should be able to have many `ActivatedLoadCase`s at once

![image](https://user-images.githubusercontent.com/32938476/191505579-a393bab5-d306-4546-9c88-41388dd2bda6.png)

Test script in test folder `502`

**Comment by Marco-Pellegrino** [comment]
Yes.
We have no error handling for ConstructionStages as the error will be catch from FEM-Design as soon as the user open the serialise file.

Every Stage can ONLY have one `activatedLoadCase` as we should make sure it is specified in the description of the component.

**Comment by xRadne** [comment]
![image](https://user-images.githubusercontent.com/32938476/191516858-c22eceb9-402a-47b8-8a62-229206cdc098.png)

**Comment by xRadne** [comment]
@Marco-Pellegrino @andosca I have fixed this. May I merge it to the next release branch (21.4.0)?

**Comment by andosca** [comment]
You can always merge if it is feature tested :)

**Comment by xRadne** [comment]
Me and Marco have tested it together now! I will merge into 21.4.0
