### ISSUE TITLE
SurfaceSupport. Add constructor and or method for stiffness points.

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#508]
24062

User wants a way to insert stiffness points for his surface support using C#. Preferably also an example where some stiffness points are imported from .csv or similar.

Stiffness points are used to set a variable stiffness for a surface support.

![image](https://user-images.githubusercontent.com/52665994/191747734-1f6f6303-1aab-4283-b19e-bd9f2379ba21.png)

The xml elements representing stiffness points are not stored as children to the surface support element, but they have a reference guid:

https://github.com/strusoft/femdesign-api/blob/4d74ab85d67a43c7a104856cc80120a92af609ea/FD%2021.01.003.xsd#L6179-L6188

https://github.com/strusoft/femdesign-api/blob/4d74ab85d67a43c7a104856cc80120a92af609ea/FD%2021.01.003.xsd#L3643-L3655

**Comment by Marco-Pellegrino** [comment]
f95ca12d71964a73c57e68c385995d0746953bc5

**Comment by andosca** [comment]
Awesome!
