### ISSUE TITLE
Implement a geometry lib with transformation capabilities

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#51]
- Investigate libs that can be implemented or,
- Add overrides to existing geometry object to multiply with .NET tranformation matrices.

**Comment by andosca** [comment]
Not relevant for now.

**Comment by xRadne** [comment]
If we implement a BHoM adapter #70, we could probably utilize their extensive geometry lib

**Comment by xRadne** [comment]
I'm about to write some basic geometry line-line overlap methods for a customer project. Is this something that we want to include in this repo?

**Comment by andosca** [comment]
https://github.com/strusoft/ng-sdk/blob/db647326050fa034ce790de1d5ab46e18cb499ea/sdk/partials/Geometry/Line3D.cs#L98-L129
