### ISSUE TITLE
LoadCombination Constructor without list for few Load Cases without using List

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#515]
Inspiration taken from `System.IO.Path.Combine()`
https://learn.microsoft.com/en-us/dotnet/api/system.io.path.combine?view=net-6.0

<html><body>

Combine(String[]) | Combines an array of strings into a path.
-- | --
Combine(String, String) | Combines two strings into a path.
Combine(String, String, String) | Combines three strings into a path.
Combine(String, String, String, String) | Combines four strings into a path.

```csharp
public LoadCombination(string name, LoadCombType type, List<LoadCase> loadCase, List<double> gamma,  CombItem combItem = null)
public LoadCombination(string name, LoadCombType type, LoadCase loadCase1, double gamma1,  CombItem combItem = null)
public LoadCombination(string name, LoadCombType type, LoadCase loadCase1, double gamma1, LoadCase loadCase2, double gamma2,  CombItem combItem = null)
public LoadCombination(string name, LoadCombType type, LoadCase loadCase1, double gamma1, LoadCase loadCase2, double gamma2,  LoadCase loadCase3, double gamma3, CombItem combItem = null)
```

**Comment by Marco-Pellegrino** [comment]
@andosca @xRadne 
Not sure what it is your thought about adding some constructor that looks like the one above.
I have just had a thought looking at some .NET documentation

**Comment by xRadne** [comment]
Maybe we can use the [params keyword](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/params) for this?

**Comment by Marco-Pellegrino** [comment]
Not sure how easy is to explain to the users on how to use `params` but it would work.

I had this thougth regarding redability

```csharp
var loadCombination = new FemDesign.Loads.LoadCombination("ULS", LoadCombType.UltimateOrdinary, new List<LoadCase> { deadLoad, wind, snow }, new List<double> { 1.0, 1.3, 1.5 });
var loadCombination = new FemDesign.Loads.LoadCombination("ULS", LoadCombType.UltimateOrdinary, deadLoad,  1.0, wind, 1.3, snow, 1.5);
```

**Comment by xRadne** [comment]
@Marco-Pellegrino Have a look at my proposal in commit 63f7dd4a74c4ed570e31180a77d704e1c44cda75

**Comment by Marco-Pellegrino** [comment]
@xRadne I like the solution <3.
The only downside is that we will need to change the order of the input in order to keep `CombItem`.

I am not sure how many people knows about `params ` but it is technically what I was looking for. We will need to create an example and it should be fine.

From a readability point of view, it looks similar from what I have proposed (apart from the parenthesis) but it is more general approach. I think the user would love this new constructor
