### ISSUE TITLE
Finite element division numbers and sizes reset during serialisation/deserialisation of .str

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#519]
Division numbers for bars and average element size for shells assigned to specific objects are reset.

- Division number of bars is not implemented in `.struxml` and them resetting is expected.
- Average mesh size of shells should not reset. This could in that case be a bug.

- [x] Try to reproduce reset of average mesh size of shells --> Can't reproduce error.
- [ ] Ask BP to implement division numbers for bars (should be an old case for this)

**Comment by xRadne** [comment]
> Division number of bars is not implemented in .struxml and them resetting is expected.

Technically we could save these settings I think. If we dump the config after we run the analysis and then read it from together with the readStr. This might work but many things might go wrong here and it is probably a good idea to ask BP to improve this.

**Comment by andosca** [comment]
Not sure if division number is part of config. Maybe it it. Note that division number can be unique for every bar, it is not a global setting. So the idea would be to have an attribute similar to:

https://github.com/strusoft/femdesign-api/blob/4d74ab85d67a43c7a104856cc80120a92af609ea/FD%2021.01.003.xsd#L1286

**Comment by andosca** [comment]
Test using partial:

I have a base.str and a partial.struxml

The base.str contains two beams B1 and B2. B2 has a division number of 5. Performing a partial update merging the .struxml into the .str, only modifying B1, resets the division number of B2 back to 2.

**Comment by andosca** [comment]
Can't reproduce reset of average mesh size. Mesh is reset during serialisation/deserialisation but `mesh_size` is kept intact.

**Comment by andosca** [comment]
Being able to set division number using .struxml is not relevant for the user at this moment.
