### ISSUE TITLE
Add missing bar part attributes

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#522]
### Beam/Column: 'Camber simulation by prestressing' is reset.

- [x] Implement:

https://github.com/strusoft/femdesign-api/blob/4d74ab85d67a43c7a104856cc80120a92af609ea/FD%2021.01.003.xsd#L1459

### Beam/Column: 'Consider steel bar plasticity' is reset

- [x] Implement:

https://github.com/strusoft/femdesign-api/blob/4d74ab85d67a43c7a104856cc80120a92af609ea/FD%2021.01.003.xsd#L1474-L1477

### Beam/Column: End condition 'Eccentricity in analytical model' is reset

- [x] Try to reproduce.

### Beam/Column: End condition 'Consider eccentricity caused by ...' is reset.

- [x] Implement

https://github.com/strusoft/femdesign-api/blob/4d74ab85d67a43c7a104856cc80120a92af609ea/FD%2021.01.003.xsd#L1473

### Trusses: Compression/Tension mode resets/sets to 'Brittle'

- [x] Implement

https://github.com/strusoft/femdesign-api/blob/4d74ab85d67a43c7a104856cc80120a92af609ea/FD%2021.01.003.xsd#L1492-L1498

### Trusses: 'Limit force [kN] set/resets to 0.000

- [x] Try to reproduce.

**Comment by andosca** [comment]
> @andosca
> I am assuming that the specific task is to keep the `attribute`, `element` in case of Deserialisation/Serialisation. Right?

Well. In some cases we need to add an `attribute`/`element` to store the information or FD will use default. In some other cases there could be a bug which I have not investigated further.

**Comment by Marco-Pellegrino** [comment]
https://github.com/strusoft/femdesign-api/commit/e00bdefa4e470530884860eccded4ae80cdc7a98
