### ISSUE TITLE
Division number reset merging .struxml (not modifying the element of interest)

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#527]
Test using partial:

I have a base.str and a partial.struxml

The base.str contains two beams B1 and B2. B2 has a division number of 5. Performing a partial update merging the .struxml into the .str, only modifying B1, resets the division number of B2 back to 2.

_Originally posted by @andosca in https://github.com/strusoft/femdesign-api/issues/519#issuecomment-1260656583_

- [x] Report bug
- [x] Wait for implementation

**Comment by andosca** [comment]
See https://strusoft.fogbugz.com/f/cases/122480/

**Comment by Marco-Pellegrino** [comment]
implemented and tested by @andosca
