### ISSUE TITLE
Name/Identifier bug on 21.4.0

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#529]
Branch: `21.4.0_Branch`

![image](https://user-images.githubusercontent.com/32938476/192769190-090c1233-fe37-4f59-bab6-1afe835953e9.png)

This prints the name "B.1.2.3.4.5"

**Comment by Marco-Pellegrino** [comment]
#511 
The refactoring will affect/simplify #511

**Comment by xRadne** [comment]
@Marco-Pellegrino I have started working on these two issues, and I think I have a good solution that I am happy to discuss with you.
