### ISSUE TITLE
Set default values for constructors in Core

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#53]
Set default values for common constructors like Beam, Slab etc or set static methods that generates a default Beam, Slab etc. with predefined geometry etc.

- [x] Beam
- [x] Column
- [x] Truss
- [x] Plate
- [x] Wall
- [x] Panel
- [x] #414

**Comment by johannariad** [comment]
Calculate.Analysis analysis = new Calculate.Analysis(null, null, null, null, true, false, false, false, false, false, false, false, false, false, false, false, false); 🔥

**Comment by Marco-Pellegrino** [comment]
Grasshopper users are now able to create Bar/Column/Truss/Slab/Wall using only the Geometry input.
Predefined Material and Section are assigned.
It will help the user to play around with the tool and make some experiment without specifying those informations

**Comment by xRadne** [comment]
> Grasshopper users are now able to create Bar/Column/Truss/Slab/Wall using only the Geometry input. Predefined Material and Section are assigned. It will help the user to play around with the tool and make some experiment without specifying those informations

AMAZING! This will make me 400% as productive in my daily work! 🏎
