### ISSUE TITLE
What is the purpose of `source_software`

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#531]
What is the purpose of `source_software` and why is it FEM-Design 18.00.004 in the API?

![image](https://user-images.githubusercontent.com/32938476/193519930-45158c31-04a9-4b1b-a583-dab9e055570d.png)

**Comment by xRadne** [comment]
Ping @andosca

**Comment by andosca** [comment]
Should be the version in which the .struxml was serialised. Not really applicable for .struxml-files generated by the API SDK.

**Comment by andosca** [comment]
Not sure how FEM-Design reacts to that. But in theory yes. Maybe FEM-Design will validate differently based on this attribute.

**Comment by xRadne** [comment]
Tested on a big model. This appears to do nothing.

Value | OK?
--- | --- 
`FEM-Design 21.00.004` (Default) | Yes
`FEM-Design API SDK 21.4.0` | Yes
`SOMETHING COMPLETEY DIFFERENT` | Yes

**Comment by andosca** [comment]
Lets implement `FEM-Design API SDK {version-number}` then
