### ISSUE TITLE
Default Value for Units

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#533]
In the constructors

**Comment by andosca** [comment]
In result reader?

**Comment by Marco-Pellegrino** [comment]
Constructor :)
There is also a static property Default but it does help to have a constructor with predefined values that user can change.

For example, The user should be able to only set the length input if necessary.

**Comment by andosca** [comment]
I'm confused.

**Comment by Marco-Pellegrino** [comment]
I'll show it to you later

**Comment by xRadne** [comment]
Ability to write the following
```c#
// Use default units but with length changed to mm instead.
var units = new Units(length: Length.mm);
```

**Comment by Marco-Pellegrino** [comment]
e4a78b2d3718a2fd94bf9330cc24a0875c1cbfed
