### ISSUE TITLE
Implement pipe to open FEM-Design process

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#535]
Following the successful testing from #464

--- 

# Pipe to open FEM-Design process

## Goals

- Allow users to run consecutive commands to FEM-Design using the same opened FEM-Design instance.

## Research
- #464 
https://strusoft.fogbugz.com/f/cases/117155/Pipe-for-communication-with-FEM-Design

### Grasshopper
For now the only way to implement pipe (that we understand) in grasshoppe seems to be using `async` components. The user-experience is really improved. However, using `async` components removes the possibility to perform iterative analyses which is a `no-go`. 

If we still want to implement `async` components to enable pipe communication for users who are not interested in performing iterative analysis we would have to keep `RunAnalysis` and `RunDesign` components such that users can still perform iterative analysis.

One approach would be to introduce the pipe components as "experimental" so that our users can try them out and give us feedback on them.

## Questions
- Is it possible to know if a command/fdscript have finished? ✅ (`WaitForCommandToFinish`)
- Is it possible to know if a command/fdscript have run without errors in FEM-Design? ❓
- Is it possible to implement a `async` method that runs the commands? ✅ ([comment](https://github.com/strusoft/femdesign-api/issues/535#issuecomment-1303889429)) #399 

## Requirements
- [x] #595, #546
- [x] #536
- [x] #537
- [x] #539
- [x] #541
- [x] #540
- [x] #567
- [x] #600
- [x] #551
- [x] #587
- [x] #542
- [x] #543 
- [ ] #646

**Comment by andosca** [comment]
Awesome!

#### Async method
Whats the purpose of being able to run script async? Not getting stuck in GH?

#### Dynamo components
I think this will be necessary in order to avoid keeping the old version of `Calculate.Application`.

**Comment by andosca** [comment]
How big is this job? In terms of weeks.

**Comment by xRadne** [comment]
> #### Async method
> 
> Whats the purpose of being able to run script async? Not getting stuck in GH?

C# or anywhere. 

Most usefull case would be a server processing multiple tasks in parallel and remaining responsive while another big task is being run in the background without locking the thread. 

But this can probably be achieved in other ways too. But I don't have enough knowledge about C# or multi-threading. But this would be an interesting test. 

> #### Dynamo components
> 
> I think this will be necessary in order to avoid keeping the old version of `Calculate.Application`.

Yes, if we want to remove `Calculate.Application` this is a must do.

**Comment by xRadne** [comment]
> How big is this job? In terms of weeks.

1 to 5 work days.

**Comment by xRadne** [comment]
Branch [464-pipe](https://github.com/strusoft/femdesign-api/tree/464-pipe)

**Comment by xRadne** [comment]
### Threading and async methods
I have made some more testing and research on how threading and async methods work. 

All methods we provide will be possible for the users to convert to a async method and my previous questions does not make any sense, I have this removed them.

### Note to the future: 
I have added an example (e84fb675a0a8cab9bc999d1ed09023476c8a9c53) which solves two problems:
1. Avoid deadlock. 
2. Avoid locking the user interface while FEM-Design is working (asyncronous).

**Comment by xRadne** [comment]
There is still 1 problem that I have not found any solution to yet. 

How to wait for FEM-Design to finish a command when running in Grasshopper. 
I have only been able to run a command _without waiting_ or _waiting forever_ (deadlock).

**Comment by Marco-Pellegrino** [comment]
@xRadne 
as we are approaching 21.6.0 release and the C# pipe has been solved, I am going to close the issue.
We will create new issues when we will need to develop new methods on top of OpenPipe.

I have also moved out the Grasshopper/ Dynamo issue. However, It has been decided that Dynamo should only be develop on request and I'll not consider the implementation for the time being

**Comment by Marco-Pellegrino** [comment]
@xRadne 
Not sure if the following code gives us some insight

https://github.com/Tomalwo/FrOG/blob/a05e0a57a04dea74c1059b4a4bde6fb462fbdce6/FrOG/OptimizationLoop.cs

**Comment by xRadne** [comment]
What part are you thinking of? :)
