### ISSUE TITLE
Pipe: Grasshopper components to use pipe

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#543]
### Commands Components
- [x] Open (Model)
- [x] Open (file path) ???
- [x] RunAnalysis
- [x] RunDesign
- [x] GetModel
- [x] #704
Important that the components take the connection as input and then return it as output for grasshopper to be able to run the commands in the correct sequence. 
- [x] #379

### Results
Maybe we should refactor all the results deconstructor components to both read results and deconstruct the results.
- [x] Input and output connection
- [x] Input units
- [x] GetQuantities
- [x] Input load case/combination/~~construction stage~~
- [ ] #721
- [x] One component to get Load Case and Load Combination Results
- [x] Remove Get Results
- [x] ~Components don't need to take a `ResultType` as input. Each component have a unique result type.~
- [x] check if .str file is in the folder #674

**Comment by Marco-Pellegrino** [comment]
https://discourse.mcneel.com/t/c-understanding-computedata-and-solveinstance-what-happens-when/55613/2?u=rnjthmhnkl

**Comment by xRadne** [comment]
Thread about `Task.Wait()` that will cause deadlock in Grasshopper. However I think we need `ConfigureAwait(true)` otherwise the Wait() wont actually wait. But this needs to be investigated.
https://discourse.mcneel.com/t/tasks-async-await-in-grasshopper/80709

**Comment by xRadne** [comment]
After some more research I have ended up with the following: 

```c#
class A
{
  // This works, but it's not what we want.
  void Method1() {
    var t = Task.Run(() =>
    {
      var femDesign = new FdPipe()
      femDesign.RunScriptAsync(script).Wait();
      femDesign.Dispose();
    });
    t.ConfigureAwait(false);
    t.Wait();
  }

  // This doesn't work.
  void Method2() {
    var femDesign = new FdPipe()
    
    var t = Task.Run(() =>
    {
        femDesign.RunScriptAsync(script).Wait();
    });
    t.ConfigureAwait(false);
    t.Wait();

    femDesign.Dispose();
  }
}
```

**Comment by xRadne** [comment]
Thread about how to run a background task with parameter from the main thread:
https://stackoverflow.com/questions/30225476/task-run-with-parameters
