### ISSUE TITLE
Refactor the FdScript

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#546]
Our current `FdScript` class can only have the commands in a certain order, and they can only appear once. 

But FEM-Design can handle a script that have several commands (#68) in any order.  

I propose alternative 1.

### Alternative 1
Refactor the FdScript to take a list of commands (#68) 

These commands are already implemented but FdScript would need to be refactored to have a constructor/method to add a list of commands to the fdscript. CmdOpen, CmdListGen, CmdSave, CmdSaveDocx, etc.

### ~Alternative 2~
Implement a lot of static methods to do each one single command.
- Open model
- Read single result
- Set global config
- Save docx
- etc.

**Comment by xRadne** [comment]
@andosca @Marco-Pellegrino Please have a look at this proposal. 

I have created a new FdScript class. This one serializes a list of command object to xml (.fdscript).
Instead of serializing a class with some properties set to null and some set to a command objects. This way FdScripts can be more flexibly composed. 

https://github.com/strusoft/femdesign-api/blob/6ee4a9b716f9ef2eac503d3e3ccdcb6c8f797967/FemDesign.Core/Calculate/FdScript2.cs#L101-L110

https://github.com/strusoft/femdesign-api/blob/6ee4a9b716f9ef2eac503d3e3ccdcb6c8f797967/FemDesign.Core/Calculate/FdScript2.cs#L112-L130

**Comment by andosca** [comment]
Alternative 1 looks better IMO.

**Comment by andosca** [comment]
This part has been implemented right?

**Comment by Marco-Pellegrino** [comment]
Yes,
we only need to change the class name of FdScript2.
