### ISSUE TITLE
How to update the section/material of an element?

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#549]
How do you change the section of a bar/slab/panel in C#?

I wish there was a property or method that worked like this:
```c#
Section section = sectionDatabase.GetSectionByName("400x400"); // This should be a real section ofc
bar.Section = section;
```

or maybe like this

```c#
bar.UpdateSection(section);
// or
bar.Section = section;
bar.SectionStart = section1;
bar.SectionEnd = section2;
```

### Methods
- [x] Section - Bar
- [x] Material - Bar
- [x] Section - Slab/Wall
- [x] Material - Slab/Wall
- [ ] Section - Panel - it will be done on request
- [ ] Material - Panel - it will be done on request

**Comment by xRadne** [comment]
The same would be the case for materials of course

**Comment by andosca** [comment]
We could do 21.7.0. 

Also I agree with the problem definition. It is quite difficult to understand how to do simpler things as they are obfuscated.

**Comment by Marco-Pellegrino** [comment]
write a method instead of a property

**Comment by xRadne** [comment]
@Marco-Pellegrino Good job! 🚀

**Comment by xRadne** [comment]
Should the Bars.Modify component be updated with the new methods as well? So that we have the same functionality in Core and Grasshopper? Or do they do different stuff?

https://github.com/strusoft/femdesign-api/blob/1c4106ac2f6e2b51dde46894b46e24e8f4a08f33/FemDesign.Grasshopper/Bars/BarsModify.cs#L87
