### ISSUE TITLE
Analysis setters

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#55]
Set `calcFreq = Freq != null` etc.

```C#
        [XmlElement("stage")]
        public Stage Stage { get; set; } // ANALSTAGE
        [XmlElement("comb")]
        public Comb Comb { get; set; } // ANALCOMB
        [XmlElement("freq")]
        public Freq Freq { get; set; } // ANALFREQ
        [XmlElement("footfall")]
        public Footfall Footfall { get; set; }
```

**Comment by andosca** [comment]
@xRadne What was the purpose of this case?

**Comment by xRadne** [comment]
Avoid the possibility of havind `calcComb` with `Comb == null` etc. 

But definitively not needed. It was just a bit strang as a new user to set up an analysis from C#

**Comment by andosca** [comment]
Why not implement it then for C# users?

**Comment by Marco-Pellegrino** [comment]
Linked to #244

**Comment by Marco-Pellegrino** [comment]
C# user is now able to run Static Analysis, EigenFrequencies analysis with a simpler method.
