### ISSUE TITLE
string representation on surface loads not complete?

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#552]
![image](https://user-images.githubusercontent.com/89396751/195294976-811f8b20-c329-483c-bd1d-c059c3b4961c.png)
I dont see any info on the load case

**Comment by xRadne** [comment]
> I disagree with this solution of https://github.com/strusoft/femdesign-api/issues/552. This will print the guid instead of the LoadCase name.
> 
> A better solution is to set the value of this.LoadCaseName when we do Model.DeserializeFromFilePath(). This is the approach used for many of the properties that have an [XmlIgnore]-attribute.
> 
> See this example:
> Here we set the load case name to be equal to the name of the load case with the correct guid.

[Comment](https://github.com/strusoft/femdesign-api/commit/b23bc2cd8a66f73f93710f10abb9c9e0c97f022f#r91307930)

**Comment by xRadne** [comment]
Thank you @Marco-Pellegrino 😄
