### ISSUE TITLE
Remove Name input on Section.Define

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#556]
```c#
Name = $"{GroupName}, {TypeName}, {SizeName}";
```

![image](https://user-images.githubusercontent.com/32938476/195557955-62883624-ec4f-4fa2-b228-f77874168da1.png)

- [x] Update the example on Docusaurus
- [x] Update `Example 5 - Using custom sections`

**Comment by Marco-Pellegrino** [comment]
I have just created an example for Grasshopper regarding the custom cross section (which is really powerful) and I had some doubt as well regarding the inputs.

```xml
<section name="Concrete sections, Rectangle, 120x250" fd_name_code="Concrete sections" fd_name_type="Rectangle" fd_name_size="120x250">
```

I generally don't appreciate the "name" that FEM-Design is assigning to the sections but we should follow their rule (which is closer to the one you suggest)

**Comment by Marco-Pellegrino** [comment]
I have changed the milestone to 21.5.0 as the feature is needed for some example/contents for 21.5.0
