### ISSUE TITLE
Construction stages can't be added to load combination

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#561]
## Expected
Construction stages should be possible to add to a load combination:
![image](https://user-images.githubusercontent.com/32938476/196386411-4ac08d33-0947-4a5a-a7e7-cc6d8c4664cb.png)
![image](https://user-images.githubusercontent.com/32938476/196386921-f5e06062-c639-42c1-a14f-23e6b7d5684a.png)

## Bug
- [x] Struxml model that has load combination with construction stage can't be deserialized.

## Feature
- [x] Create load combinations with construction stage case `cs_case` [C#]
- [x] Create load combinations with special load case (seisemic, ptc, etc) [C#]
- [x] Create load combinations with  construction stage case [Grasshopper]
- [x] Create load combinations with special load case (seisemic, ptc, etc) [Grasshopper]

**Comment by xRadne** [comment]
@andosca @Marco-Pellegrino This is required for a project. Can you please help me with this fix? 

Or if you want, I could do it if you allow me to do a hot fix and you create a new release for me :)

**Comment by Marco-Pellegrino** [comment]
@xRadne 
 I am currently focus on other tasks and it would be great if you can fix it if it is super urgent.

Do you also need to share the .dll with the clients? is this the reason to have a new release?

**Comment by xRadne** [comment]
Implemented the following types for load combinations. In C#

https://github.com/strusoft/femdesign-api/blob/4ef9111c8db6a10ac5641ad1b1bd69beafa309f7/FemDesign.Core/Loads/LoadCombination.cs#L20-L32

**Comment by xRadne** [comment]
> @xRadne looks like the issue has been solved :). 

Actually, only fixed C#. Did not get the time to fix Grasshopper components as well

**Comment by xRadne** [comment]
As discussed with @andosca, I will do a refactor of the LoadCombinations. Mainly to create a better ux in grasshopper.

To do:
- [ ] LoadCombination.Deconstruct should output `LoadCase`, `Stage` objects
- [ ] LoadCombination.Deconstruct add parameter LoadCase type [`Load case`, `Stage`, `Special load case`]
- [ ] Make old Deconstruct component obsolete
- [ ] Make old Construct component obsolete
- [ ] Deepclone, GetLoadCombination()
- [ ] Value list auto-update. On the input parameter LoadCase
- [ ] Update LoadCombination.Construct LoadCase parameter description.

**Comment by xRadne** [comment]
![image](https://user-images.githubusercontent.com/32938476/198641613-e473123c-f9d0-4366-8980-b6df822c78fd.png)

**Comment by xRadne** [comment]
Moving loads increases the complexity even further
