### ISSUE TITLE
🚸 Line stress load

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#563]
- [x] Create simple constructor (without direction and loadLocationValue list) for C#
- [x] Override ToString()
- [x] Create a Line stress load component (and deconstructor) for grasshopper
- [x] Add an icon @andosca

**Comment by xRadne** [comment]
Wanted for the current project, but not needed. I can use a workaround using C# script component to create line stress loads

**Comment by andosca** [comment]
![LineStressLoadDeconstruct](https://user-images.githubusercontent.com/52665994/199276986-87b87c61-e775-4909-bfbd-d6ea2bc54113.png)
![LineStressLoadConstruct](https://user-images.githubusercontent.com/52665994/199276988-3f142f19-bd45-4067-9ad1-e7f5c223cdeb.png)

**Comment by Marco-Pellegrino** [comment]
@xRadne 
New Constructor looks nice!

I was wondering if the input should be a vector or a scalar is enough.
