### ISSUE TITLE
🐛 Setup load combination have bad default argument

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#566]
The `Im` input is not working

![image](https://user-images.githubusercontent.com/32938476/197516870-f992324b-f778-4e47-a758-7b8d83d90c56.png)

**Comment by Marco-Pellegrino** [comment]
it looks like that you Im has been modified from int to bool.
I'll fix it for this milestone

**Comment by xRadne** [comment]
> it looks like that you Im has been modified from int to bool. I'll fix it for this milestone

You're right, my bad!
