### ISSUE TITLE
Cherry-pick load cases or load combinations

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#569]
Allow the user to request results by load cases or load combinations during the request to FEM-Design. Today we dump all load cases and load combinations and then filter the load case or load combination of interest. If the model is large the current method can be slow.

There should have been an improvement to `CMDLISTGEN` already:

- https://strusoft.fogbugz.com/f/cases/117288

**Comment by Marco-Pellegrino** [comment]
yes. it should be already possible to implement this feature.

OpenPipe will probably open some different scenario/improvement in reading the results and might modify the actual workflow to read results.

I'll write down my idea when the time comes.

**Comment by Marco-Pellegrino** [comment]
@xRadne @andosca 

I haven't ask to BP but here the logic (at least for load case)

Looks like that the logic is the following:

### Formula
index = Constant + [Load Case Index] * 65536

### Constant
ultimate = 0
Quasi-Permanent = 4
Frequent = 5
Characteristic = 1

### Load Case Index
The Load Case are stored in the loadcase

```xml
<load_case type="dead_load" duration_class="permanent" guid="79cafbec-42ed-487f-b2f4-748193052485" name="Deadload"></load_case>
<load_case type="static" duration_class="permanent" guid="3fbb2346-472f-4f91-b0ea-dcd4d931d762" name="Liveload"></load_case>
<load_case type="static" duration_class="permanent" guid="a133a755-a2a6-4ddb-b3d8-b3261ac69ba5" name="wind"></load_case>
<load_case type="static" duration_class="permanent" guid="b1978f72-ddb2-44b7-af11-974caf8d06d9" name="snow"></load_case>
<load_case type="static" duration_class="permanent" guid="2005f338-8b0b-4de0-8717-e9f112137aea"  name="pippo"></load_case>
```

example:

if we want to get Frequent - LiveLoad:
Constant = 5
Load Case Index = 1

index = Constant + [Load Case Index] * 65536 = 65 541

![image](https://user-images.githubusercontent.com/53620289/202746034-4f40f768-107a-418d-bf84-0a181558e9f2.png)

**Comment by Marco-Pellegrino** [comment]
Information from BP asked by the API team a year ago

![image](https://user-images.githubusercontent.com/53620289/203039640-53b6de73-5469-4d9a-acbd-0f82aac71fd7.png)
