### ISSUE TITLE
SetupCalculation does not work in 21.4.0

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#581]
@Marco-Pellegrino has probably already fixed this for 21.5.0, just adding the issue for documentation
![image](https://user-images.githubusercontent.com/89396751/199521362-e8dabe94-edc0-4fe1-9c0e-8b5c504b3215.png)

**Comment by Marco-Pellegrino** [comment]
yes.
Just checked and it has been fixed
