### ISSUE TITLE
Line connection constructor in Grasshopper

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#589]
https://strusoft.freshdesk.com/a/tickets/25139

![image](https://user-images.githubusercontent.com/89396751/200308797-7c4fd9c2-1459-4ba8-9bbc-3b8edae3aa8d.png)
Needed asap for a user project

**Comment by xRadne** [comment]
Should be possible using C# or C# component inside Grasshopper. If needed asap.

**Comment by xRadne** [comment]
Duplicate of #451

**Comment by JRiad** [comment]
Surface connections are rarely used but I think point connections could be useful in the near future (in an internal project). If you have time could you implement this also for 21.7.0?
