### ISSUE TITLE
Testing: Grasshopper examples

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#593]
Automatic tests to check that the examples:
- [ ] Run without getting stuck

And maybe:
- [ ] Outputs something meaningful

**Comment by xRadne** [comment]
Another solution is to use a self-hosted runner. https://github.com/hrntsm/GH-UnitTest-by-RhinoCompute

**Comment by Marco-Pellegrino** [comment]
f1e4f29fb7c912807f71e9c0e8ba02c28b761da9
