### ISSUE TITLE
Orthotropic and CLT panels in default materials possible?

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#602]
Could we get these as output from the default material component as well? It would save the user some confusion in having to create a separate struxml-file for these materials
![image](https://user-images.githubusercontent.com/89396751/203026595-75538661-2251-4612-b7ff-55e1895098ad.png)

**Comment by andosca** [comment]
Basically we are waiting for this https://strusoft.fogbugz.com/f/cases/119403/
