### ISSUE TITLE
"å", "ä" and "ö" warning?

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#604]
One of the most common user errors is having these special characters in file name, file path or load case/load combo names. They will cause an error, depending on the language settings on the user's computer (Laszlo explained this to me, something with how FD is originally programmed). Could we give a warning in the "readstr", "readstruxml", "save" and "open" components (or anywhere a struxml file is read or written) if the struxml file contains special characters?

It heard at KCT that something is being done in FD22 with special characters, perhaps best to check out if that solves the issue before implementing anything new.

**Comment by andosca** [comment]
+1

**Comment by xRadne** [comment]
I propose we do a `info` note on the components when file path has special characters (non-ascii characters).

**Non-ascii character** if match with regex pattern `[\u00FF-\uFFFF]` ([StackOverflow](https://stackoverflow.com/questions/3001177/how-do-i-grep-for-all-non-ascii-characters))

**Info/Remark warning in Grasshopper**:
```c#
AddRuntimeMessage(GH_RuntimeMessageLevel.Remark, "File path has special characters. This might cause problems..."); // TODO edit text
```

**Comment by JRiad** [comment]
> I propose we do a `info` note on the components when file path has special characters (non-ascii characters). It should be info (white), since it will still work for most users, so it should not be a warning (orange) or error (red).
> 
> **Non-ascii character** if match with regex pattern `[\u00FF-\uFFFF]` ([StackOverflow](https://stackoverflow.com/questions/3001177/how-do-i-grep-for-all-non-ascii-characters))
> 
> **Info/Remark warning in Grasshopper**:
> 
> ```cs
> AddRuntimeMessage(GH_RuntimeMessageLevel.Remark, "File path has special characters. This might cause problems..."); // TODO edit text
> ```

As long as it stands out enough for users to notice it. Not sure how info notes look?

**Comment by Marco-Pellegrino** [comment]
@JRiad 
It does look like this the Info/Remark in Grasshopper

![image](https://user-images.githubusercontent.com/53620289/205673306-565f6e16-3c3d-41e5-8052-f6323167455f.png)

**Comment by JRiad** [comment]
Ok thanks! I think it should be a warning (orange) so users notice. I don't think the users who are inexperienced with GH will notice this small white note. 

Even if it works with å, ä and ö for some users I think it is good practice not to use those characters, since if they want to share  the script with a colleague or run it on another computer it might not work. So I don't think a warning is out of place.

**Comment by Marco-Pellegrino** [comment]
@JRiad 
Fine by me!
I'll change it to 'warning' to make the user more aware.

👌
