### ISSUE TITLE
Move .cs projects, gh files etc (assets) from docs repo to this repo

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#607]

**Comment by Marco-Pellegrino** [comment]
the end goal would be to:
- avoid duplicate files --> example files should only be on femdesign-api repo
- easy to mantain --> basics/gh/C# are currently in the docs repo and they are easy to reference and modify as the assets are within the same folder of Index.md.
- automatic testing --> not YET implemented and it might change the previously discussed bullet points.
