### ISSUE TITLE
Result reader for result point

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#612]
https://strusoft.fogbugz.com/f/cases/117287

**Comment by Marco-Pellegrino** [comment]
we should also allow the user to specify the "step".
It has been hard coded as 0.50 m (which cover most of our customer case probably)

**Comment by andosca** [comment]
For bars you mean?

**Comment by Marco-Pellegrino** [comment]
yes

**Comment by Marco-Pellegrino** [comment]
check if result point works in 21.00.006

**Comment by Marco-Pellegrino** [comment]
Issue has been solved.
It will be merge in 22.0.0 as Result Point constructor does not work for FEM-Design 21.00.005.
