### ISSUE TITLE
CombItem.Default()

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#613]
I am happy with the actual default values but I was wondering that those are different from FEM-Design values.

Should we make them consistent?

**FEM-Design**
![image](https://user-images.githubusercontent.com/53620289/204243106-d2ac0721-d23f-4f78-a29f-983f882d2e2d.png)

**API**
```csharp
public static CombItem Default()
{
    int impfRqd = 0;
    int stabRqd = 0;
    bool NLE = false;
    bool PL = false;
    bool NLS = false;
    bool Cr = false;
    bool f2nd = false;
    int im = 0;
    int waterlevel = 0;

    var combItem = new CombItem(impfRqd, stabRqd, NLE, PL, NLS, Cr, f2nd, im, waterlevel);
    return combItem;
}
```

**Comment by andosca** [comment]
Sure!
