### ISSUE TITLE
Mesh division number for beams

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#615]
User would like to be able to set the mesh division number for beams:
![image](https://user-images.githubusercontent.com/89396751/204279650-1021491a-4427-420d-87bb-2b678da54cc7.png)

Default number of elements causes large error in this project.

Moment med ’default’ antal element:
![image](https://user-images.githubusercontent.com/89396751/204279663-eec9279d-1e11-49fc-a2e6-9ac1179261bd.png)

Moment med 130 element (manuellt inställt):
![image](https://user-images.githubusercontent.com/89396751/204279682-632d629b-dc9d-44a0-b83b-009cc8c35ff1.png)

**Comment by Marco-Pellegrino** [comment]
I would suggest the user to "manually" discretise the curve in more elements to have a better representation of his model.

We will check if there is an option in cmdglobalcfg.

**Comment by JRiad** [comment]
> I would suggest the user to "manually" discretise the curve in more elements to have a better representation of his model.
> 
> We will check if there is an option in cmdglobalcfg.

Nice if you could check. I already suggested this, and it is possible as a workaround 👍  But it creates additional work in defining loads which are quite complex for an arched roof so it would be great to have this functionality. Mesh size for slabs is already implemented, so hopefully this is also available for beams in cmdglobalcfg

**Comment by andosca** [comment]
Should be possible to set global division number for bars for now using `cmdglobalcfg`

**Comment by Marco-Pellegrino** [comment]
@andosca it will be solved when we release Pipe
