### ISSUE TITLE
Store GlobalSettings in an external file

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#616]
We should consider to store the global settings in a formatted file that user can change on his own.

We will then read the values from it.

I had this idea as cmdglobalcgf is a big object and it would definitely help the user to visualize it.

**Comment by andosca** [comment]
Sounds good. Where would you store it FemDesign.Core/Assets or in individual examples only?

**Comment by Marco-Pellegrino** [comment]
solved
