### ISSUE TITLE
Add schema validation on DeserializeFromFilePath

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#619]
Add schema validation on DeserializeFromFilePath in order to get better error messages when the struxml does not load properly.

**Comment by xRadne** [comment]
@Marco-Pellegrino Do you want to include this in 21.6.0?

https://github.com/strusoft/femdesign-api/blob/e297e4824f4a2d752e2f585f57da7c4d6e0d2d83/FemDesign.Core/Model/Model.cs#L204-L220

**Comment by Marco-Pellegrino** [comment]
Sure (I believe you have tested it)

**Comment by Marco-Pellegrino** [comment]
it will not be merged as the error raised by the xml validate is not clear for the user
