### ISSUE TITLE
Catch serialisation bugs

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#629]
### Goals:

* Catch bugs introduced during development
* Catch bugs introduced by xml schema changes/additions

### Context
New features are always tested locally under implementation. However, global tests always have to be run in order to assure that implemented features does not break any workflows. These global tests are performed manually and require some effort to do every time a new release should be published.

#### Unit testing
Run C# unit tests. Catch bugs for specific methods.

- [ ] #631

#### Integration testing
Run C# and Grasshopper examples. Catch workflow bugs and component problems.

- [x] #592 
- [x] #593 

#### Regression testing
Catch `Model` serialisation and deserialisation bugs (basically bugs in add/get methods).

#### Schema validation

- [ ] #620 
- [x] #619 

#### Refactor core to CLR classes from XSD if necessary
> a possible issue that I have found is that in order to use the CLR classes, we will need to modify the base classes. Every major version, fd21 to fd22, we should update the file inserting the [xmlInclude]

```csharp
[XmlInclude(typeof(DerivedClass))]
 public class BaseClass
{
   // Base class properties and methods
}

public class DerivedClass : BaseClass
{
   // Derived class properties and methods
}
```

**Comment by Marco-Pellegrino** [comment]
some of it will be solved with #962
