### ISSUE TITLE
Name can't read certain formatting allowable by schema

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#637]
See case here

https://strusoft.freshdesk.com/a/tickets/25819

In particular my notes and test files.

The case is related specifically to Slab and SlabPart names but could potentially occur for other objects as well. This issue does not occur prior to 21.4.0 according to the user.

**Comment by xRadne** [comment]
This might have to do with the changes I made on the name/identifier/instance etc. 

Currently we allow all identifier that follow this pattern (given by the .xsd)
https://github.com/strusoft/femdesign-api/blob/d21b699a30eadef16a43edde24586bddafe94e25/FemDesign.Core/GenericClasses/NamedEntityBase.cs#L44

**This means:**
Any character (except some special characters, @ and " etc.) `[ -#%'-;=?A-\ufffd;]{0,50}` separated by a `.` then a digit 0-999999 `[0-9]{1,6}`

**Comment by andosca** [comment]
FEM-Design 21.0.005, FEM-Design API 21.6.0.

See my private note in the support case.
