### ISSUE TITLE
Error handling Section.Define

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#650]
https://strusoft.freshdesk.com/a/tickets/26078

https://github.com/strusoft/femdesign-api/blob/a338ed7602c19cace46751ea551096686b5a02cc/FemDesign.Core/Sections/Section.cs#L116-L127

Add error handling:

- [ ] Throw exception if surface(s) (regions in regionGroup) are not in XY-plane
- [ ] Throw exception if surfaces (regions in regionGroup) are overlapping

User is specifically asking for such error handling in Grasshopper for the Section.Define component. So this would solve the users issues. However, it would be better practice to implement on Core if possible.

This error handling could possibly be set on the RegionGroup setter.

**Comment by Marco-Pellegrino** [comment]
@andosca 

it seems that the error of region not in xy plane is already catched.
Am I missing something?
I attach my test file below

https://strusoftgroup-my.sharepoint.com/:u:/g/personal/marco_pellegrino_strusoft_com/EYguhrVVZOFDglBglp22mNQBHIjxz7Voi8ALx5bqpBtOTQ?e=9PkTeg

**Comment by andosca** [comment]
maybe it is fine then. there was some issue with a user who had overlapping contours. however, fem-design catches this error. so i think we should focus on returning fem-design errors instead.
