### ISSUE TITLE
Error handling. Send log back to user.

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#651]
https://strusoft.freshdesk.com/a/tickets/26078

Send content in log file back to user. When running analysis or design error messages in FEM-Design are suppressed. Users might not understand why their analysis fails. Usually the log file should give some hints about corrupt elements etc. This would give the user valuable information about what might have went wrong.

Pipe implementation might remove the need for this.

**Comment by xRadne** [comment]
C# Example 5 shows how to read the output. Maybe we could add to the example a few lines with some logic on what to do if it outputs a warning/error.

**Comment by Marco-Pellegrino** [comment]
No declared mass
No declared load case or dead load
No declared load combination

**Comment by Marco-Pellegrino** [comment]
https://github.com/specklesystems/speckle-sharp/blob/09608cae6fbb53b564915e9ccce030eca4267e59/ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectAsync.cs#L181-L194
