### ISSUE TITLE
raise error in read result if there is no .strFEM

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#674]
note:
Quantities can be read without running the analysis ( .strFEM file )

research:
what about Finite Elements?
It seems possible to display them but there is no output if the analysis is not runned

**Comment by Marco-Pellegrino** [comment]
Check if `.strFEM` is generated when analysis is runned with Pipe

**Comment by Marco-Pellegrino** [comment]
@andosca 
Looks like that `.strFEM` file is generated when the user run an analysis AND save the file.

Raising an error in ReadResult can be done only if we save the file after running the analysis (cmdsave).

I would suggest to do not implement the feature as it means to write the results on disk. Writing on disk can be slow and we can avoid it. I think at Big Model where FEM-Design needs to write down hundreds of MB.

What do you think?
I am happy either way.

**Comment by andosca** [comment]
I would suspect that the main idea was that when reading models from file (.str) using:

![image](https://user-images.githubusercontent.com/52665994/222350715-17a089f2-e892-4104-bb60-776a980b1eb4.png)

It is useful information for the user that the (.strFEM) is missing and no results could be extracted. I think we could at least add error handling to this component.

For pipe components maybe we could forward any log message if there is a "no result found" type of message This could be a separate case.

**Comment by Marco-Pellegrino** [comment]
👌
Let's do it in this way than.
