### ISSUE TITLE
Variable Thickness Plate

### ISSUE THREAD

**Issue by berkdemir** [strusoft/femdesign-api#675]
Hi!
What should be the input type of variable thickness plate? Can you give me an example?
![image](https://user-images.githubusercontent.com/40423004/213735836-2c3eaba7-4159-476b-9726-fd459c5c3b41.png)

**Comment by Marco-Pellegrino** [comment]
Hi @berkdemir 
We have started working on a documentation website where you should find the basic informations :)

https://femdesign-api-docs.onstrusoft.com/docs/grasshopper/basics/shells/#variable-thickness
