### ISSUE TITLE
Multiple analyses/tasks per FdScript

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#68]
I think it would be neat to be able to create and run multiple models and analyses etc from the same FEM-Design application. This might give better possibilities to iterate over different models and/or save partial models etc. 

In a FdScript this can be done by appending any number of `cmdopen`, `cmdcalculation`, `cmdlistgen` etc. 

### Proposal
I propose we update the class `FdScript` to take a list of cmd-commands. 

**Example:**
```c#
public interface IFdScriptCommand 
{

}

[XmlElement("cmdopen")]
public partial class CmdOpen : IFdScriptCommand
{
  ...
}

[XmlRoot("fdscript")]
public partial class FdScript
{
  public FdScriptHeader FdScriptHeader { get; set; } // FDSCRIPTHEADER

  public List<IFdScriptCommand> Commands = new List<IFdScriptCommand>(); // FDSCRIPTCOMMAND

  public static FdScript ReadStr(string strPath, List<string> bscPaths = null)
  {
    Commands.Add(new CmdOpen(strPath));
    foreach (var bscPath in bscPaths ?? Enumerable.Empty<string>())
    {
      Commands.Add(new CmdListGen(bscPath, outputPath));
    }
    Commands.Add(new CmdSave(Path.ChangeExtension(strPath, ".struxml")));
    Commands.Add(new CmdEndSession());
    return fdScript;
  }
}
```

**Comment by xRadne** [comment]
@andosca Maybe this should be included in 21.2.1? Together with the #297

**Comment by andosca** [comment]
Will reprioritise at some point and might add this then.

@xRadne What is the use-case for this?

**Comment by xRadne** [comment]
One example would be to run a batch of calculations, and list the results in from each iteration only opening and closing FEM-Design once. 

This will improve the speed of my scripts.

Current workflow adds a lot of copies of the structure to the same struxml and runs a single fdscript, but it is a bit tedious.

**Comment by xRadne** [comment]
Another example of where this is useful is when running a design calculation. 

Currently FemDesign is opened twice in `Application.RunDesign` if `design.ApplyChanges` is true.
https://github.com/strusoft/femdesign-api/blob/f49dd0e4ab31e70b0d04cc79e010e27900b28ee8/FemDesign.Grasshopper/Calculate/ApplicationRunDesign.cs#L146
https://github.com/strusoft/femdesign-api/blob/f49dd0e4ab31e70b0d04cc79e010e27900b28ee8/FemDesign.Grasshopper/Calculate/ApplicationRunDesign.cs#L205-206

And typically (but optionally) the user wants to re-calculate the analysis once more to get the correct forces. In this case FEM-Design has to be opened and closed 3 times... 

Opening and closing FEM-Design several times 
1. takes time
2. look ridiculous

**Comment by xRadne** [comment]
I no longer think interfaces will work. But `XmlInclude` attribute like Marco used for the `Edge` child classes (#468) should be sufficient I think,

**Comment by xRadne** [comment]
See #546 and #535
