### ISSUE TITLE
C# as starting option for beginners

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#695]
Geometry library  

- [ ] Add a geometry library to C# core (hide edges, contours, regions)
- [ ] Check missing methods related to geometry manipulation.
 
Namespaces  

- [ ] Check with `FuGet` if the objects are in the correct namespace.
`FuGet` has become really slow (user feedback) and it is not really usable.

**Comment by Marco-Pellegrino** [comment]
in order to make this simple for user, we will start a refactor on the C# code
