### ISSUE TITLE
Result are given in the center of the mesh but description says differently

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#705]
Settings for output location. Default is 'ByStep' and 'Vertices'.

**Comment by Marco-Pellegrino** [comment]
Create a static method options.Default()

**Comment by andosca** [comment]
not sure of context so I might be mistaken here.

but i would prefer `.GetDefault()` if a method. Even better would be a static property `.Default`.

**Comment by Marco-Pellegrino** [comment]
I have suggested `.Default()` as we have several object that use the Sintax.

i.e.
https://github.com/strusoft/femdesign-api/blob/f361cee023ddd7dfce912ee05c68adbee639d41e/FemDesign.Core/Calculate/Comb.cs#L69-L89

If we want to use `GetDefault()`, we need to plan in modifying the other objects as well.
