### ISSUE TITLE
Consider using mm instead of meter Reinforcement input

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#708]
@andosca 
What do you think in changing the input from `m` to `mm` for the reinforcement object?

It is more natural to input the reinf diameter in mm.
i.e. 10 mm instead of 0.01 m.

![image](https://user-images.githubusercontent.com/53620289/218982927-0bfbb48b-69f2-4a78-86e4-b818c5774186.png)

**Comment by andosca** [comment]
i'm worried it might be confusing - at least for C# users. then you have to keep track of units for your different methods. in grasshopper should be OK if explicitly stated in component. however this is one of those things that will break users workflows (it will break them without them even knowing it).

**Comment by Marco-Pellegrino** [comment]
okay.
I do see the issue.
Let's leave it as it is :)
