### ISSUE TITLE
Parse NodalDisplacements using ListGen

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#71]
- [x] Generate bsc
- [x] Create result reader object
- [x] Test it

### Generate bsc
Create an automated .bsc generator for NodalDisplacements:

ListProc | frCaseDispNodal_ListProc
-- | --

### Create result reader object
Nodal displacements, Ultimate - Load case: dl - for selected objects
ID|	Node|	ex|	ey|	ez|	fix|	fiy|	Case
--|--|--|--|--|--|--|--
P.1.1|	1	|0.000	|0.000	|-70.530	|0.023	|-0.001|	dl

**Comment by xRadne** [comment]
The code on `#2-Parse-results-files` should now work
