### ISSUE TITLE
Merge Bars.Modify to Bars.Deconstruct

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#711]
Steps:

- [x] Create a new BarsModify.cs file with new GUID
- [x] Mark the previous BarsModify and BarsDeconstruct classes as obsolete
- [x] GH_Exposure Exposure => GH_Exposure.hidden
- [x] Copy output parameters from BarsDeconstruct and paste them into the new BarsModify
- [x] Add warning message if the bar has reinforcement and the new cross section is variable
- [x] Add "Ribbed" property as default to the WireProfileType enum in Wire.cs
- [x] Solving format-failure in bar's output message which occurs if the bar has a composite or delta section.
- [x] In case of using new GUID the BarReinforcement/BaseBar property's GUID should be equal with BarPart's GUID
- [x] Add stiffness modifier to input/output and mark Bars.SetStiffnessModifier comp. as obsolete
- [x] Remove Type from output
- [x] Add reinforcement to input
- [x] Mark BarReinforcement.AddToBar as obsolete
- [x] Add PTC to input
- [x] Create new Reinforcement.Ptc and mark the previous as obsolete
- [x] Create new Reinforcement.PtcStarnd and mark the previous as obsolete
- [x] Change parameters descriptions in Reinforcement.Ptc and Reinforcement.PtcStarnd
![image](https://user-images.githubusercontent.com/52665994/224964513-51262c11-9289-45ca-844a-59f8e969537e.png)

- [x] Change "Bar" input to "Curve" in Reinforcement.Ptc
- [x] Check the "Curve" input -> is it a line?
- [x] Define JackingSide with Value List comp.
- [x] Create new Ptc constructor that using a LineEdge instead of a Bar
- [x] Create AddPtcToBar() method in Ptc class
- [x] Create FromRhino2() and FromRhinoLineCurve2() methods in Convert class
- [x] Add Line3d class to FemDesign.Core\Geometry
- [x] Throw exception if curve is not on Bar when PTC is applied to the Bar
- [x] Allow users to add list of PTC to Bar (by Bars.Modify)
- [x] override ToString() -> Wire, BarReinforcement, Ptc, PtcStarndType
- [x] Tests
- [x] Remove OrientLCS option
- [x] #747

- [x] #754

**Comment by andosca** [comment]
![image](https://user-images.githubusercontent.com/52665994/224964513-51262c11-9289-45ca-844a-59f8e969537e.png)

- [ ] Throw exception if curve is not on Bar when PTC is applied to the Bar.
- [ ] Allow users to add list of PTC to Bar.
