### ISSUE TITLE
Default value for load combination node does not work for Dynamo

### ISSUE THREAD

**Issue by ibjorhag** [strusoft/femdesign-api#72]
Default value on "type" for node LoadCombination.CreateLoadCombination does not work correctly 

Warning: LoadCombination.CreateLoadCombination operation failed. 
Value must be: System.Collections.Generic.List\`1[System.String], System.Collections.Generic.List\`1[System.String], System.Collections.Generic.List\`1[System.String], System.Collections.Generic.List\`1[System.String], System.Collections.Generic.List\`1[System.String], System.Collections.Generic.List\`1[System.String], System.Collections.Generic.List\`1[System.String]

**Comment by andosca** [comment]
https://github.com/strusoft/femdesign-api/blob/dc4b3367274e617e3d082f23602c27a5983574d0/FemDesign.Dynamo/Dynamo/Loads/LoadCombination.cs#L11-L27
