### ISSUE TITLE
TextAnnotation broken references after updating generated classes

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#726]

**Comment by Marco-Pellegrino** [comment]
`style_type` has `text_font_type` as element but in .cs, there is the base class `font_type`.

Let me know your thought :)
I might be mistaken.
Test is working

**Comment by andosca** [comment]
i guess we should trust the `.xsd` first. looking at the `.cs` just made me more confused when i compared 21 and 22. 

21:
![image](https://user-images.githubusercontent.com/52665994/224249471-7c33722d-e1ae-47a5-83b6-2e2329773ba7.png)
:sweat_smile:

**Comment by Marco-Pellegrino** [comment]
yes.
It did change quiet a bit the object! 😅
