### ISSUE TITLE
Default value on node Design.define should be set to false

### ISSUE THREAD

**Issue by ibjorhag** [strusoft/femdesign-api#73]
This will improve usability

**Comment by andosca** [comment]
https://github.com/strusoft/femdesign-api/blob/dc4b3367274e617e3d082f23602c27a5983574d0/FemDesign.Dynamo/Dynamo/Calculate/Design.cs#L15-L18

**Comment by xRadne** [comment]
Should both `autoDesign` and `check` be set to false?

**Comment by andosca** [comment]
| Parameter | Default |
| -- | -- |
| autoDesign | False |
| check | True |
