### ISSUE TITLE
Add help link to the Gh components

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#739]
It would be nice and useful to implement help links to the API documentation for our components. After the Info comp. disappeared from the FD tab, it may not be easy for a new user to find it. 

That could be a solution to add a help link in the comp. help's description, which points to the API docs/Grasshopper/Basics (https://femdesign-api-docs.onstrusoft.com/docs/category/basics/).
![image](https://user-images.githubusercontent.com/107181445/225242508-d71b949b-71ab-4864-8a95-c6a3d05f7b70.png)

**Comment by andosca** [comment]
how is "help" specified?

**Comment by Marco-Pellegrino** [comment]
https://discourse.mcneel.com/t/how-to-add-customize-help-menu-on-custom-components/52918/3
