### ISSUE TITLE
StiffnessModifierBar Gh component / FD throws error message

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#750]
Error message occurs in FD if using StiffnessModifierBar Gh component.

Error message:
	Error: XML parse error in line: 23; in column: 46;	Reason:
	Error: Required attribute 'cross-sectional_area' is missing.

**Comment by Marco-Pellegrino** [comment]
Bug is fixed!
I will open a new issue as a reminder for the schema bug
