### ISSUE TITLE
Application.RunDesign / FD closes in any case

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#759]
The Application.RunDesign component closes FD in any case and doesn't depend on the value of the EndSession input. 
To remain open, the ApplyChanges input in Design.Define must be false.
![image](https://user-images.githubusercontent.com/107181445/229811908-f3f212ac-9138-4cc3-b894-15e5b3ae0758.png)

**Comment by Marco-Pellegrino** [comment]
fixed with Application.RunApplication
