### ISSUE TITLE
Results are in the wrong order

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#779]
We get the result data from FD in the wrong order. They should be sorted by the Node identifier.

![image](https://github.com/strusoft/femdesign-api/assets/107181445/5a3f7a2b-55d9-4ee1-b3db-831b7f7ce5f7)

**Comment by Marco-Pellegrino** [comment]
Result processing require an intensive data manipulation from the user side.
Sorting the value will slow down the output and it is not yet necessary.
