### ISSUE TITLE
Creation of composite section

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#802]
![image](https://github.com/strusoft/femdesign-api/assets/53620289/c03be2f1-ce62-47b6-ab1d-f71b39dc8334)

- [x] create parametric section
- [x] apply to beam
- [x] Grasshopper components
- [x] tests
- [ ] add documentation
- [x] test & update offset calculation: [FB case](https://strusoft.fogbugz.com/f/cases/131507/Invalid-offset-parameter-in-struxml)

- [x] #833 
- [ ] reply to the user (https://femdesign-api.discourse.group/t/creating-hqs-sections/106/2)

**Comment by Marco-Pellegrino** [comment]
![image](https://github.com/strusoft/femdesign-api/assets/53620289/07dfa237-aa48-44b7-8500-c72b0a5b4f8f)

Bars with section can not be created anymore. Issue related to ComplexSection attribute

**Comment by Marco-Pellegrino** [comment]
@lorinczandrea 

Try to apply one composite section to several beam.

**Comment by lorinczandrea** [comment]
https://strusoft.fogbugz.com/f/cases/129562/Incorrect-steel-sections-in-composite-bars-created-by-the-API

**Comment by lorinczandrea** [comment]
Waiting for implementation of section properties

**Comment by lorinczandrea** [comment]
Issue: [Fogbugz case](https://strusoft.fogbugz.com/f/cases/135669/FEM-Design-overrides-the-steel-profiles-when-reading-composite-sections-from-struxml)

**Comment by lorinczandrea** [comment]
Regarding to the FD issue mentioned above, we could only implement the following types:

- FilledHSQProfile
- FilledCruciformProfile
- FilledSteelTube
- FilledSteelTubeWithSteelCore

The rest of the sections will be part of the #1099 issue
