### ISSUE TITLE
Standardize 'Name' vs 'Identifier'

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#81]
Some elements (such as `Bar`) use Identifier.  
Other elements (such as `Slab`) use Name

These both represent the same property and should therefore have the same property name. 
I suggest we use `Identifier` since that follows the name in the FemDesign GUI.
![image](https://user-images.githubusercontent.com/32938476/127110648-9b46e241-ebb3-4291-9025-4fa4c7979653.png)

**Or**, Use both like this. `string Name = "B"` and `readonly string Identifier = "@B.1"` with `bool FixedIdentifier = true` etc.

**Comment by andosca** [comment]
Yes!

I like your alternative idea.

Name and instance number should be separated as properties such that a user can easily change either name or instance number.

```csharp
string IdentifierName;
int IdentifierNumber;
string Identifier;
bool FixedIdentifier;
```

What do you think?

**Comment by xRadne** [comment]
Maybe like this?

```csharp
string Name; // Keep it short
int Instance; // Coherent with the class field: private static int Instances
string Identifier;
bool FixedIdentifier;
```

**Comment by andosca** [comment]
Yes that works fine!

**Comment by andosca** [comment]
https://github.com/strusoft/femdesign-api/issues/390#issuecomment-1155166085

> > It will be implemented on any component that creates or modifies an element (bar, slab, support etc.)
> 
> Why not have this operation (of adding a single "@"/locking the identifier) as a separate component? Like below. `element` could be of type `EntityBase` or `IStructuralElement`
> 
> ![image](https://user-images.githubusercontent.com/32938476/173585053-f8468f25-dc80-4c69-91c7-2f03bfe93229.png)
> 
> I think there might be cases were you want to lock the identifier without modifying the element.

**Comment by xRadne** [comment]
@Marco-Pellegrino I can see that you have renamed all the properties `Name` to be `Identifier` here: https://github.com/strusoft/femdesign-api/commit/4d4fc5db7f624bec8771daa0267bff5f1926f614

I think all object should follow this format:

> Maybe like this?
> ```C#
> private string _name; // This is what gets serialized. E.g. "@B.10" 
> public string Name; // Keep it short. E.g. "B.10"
> public int Instance; // Coherent with the class field: private static int Instances. E.g "10"
> public string Identifier; // E.g. "B"
> public bool LockedIdentifier; // If instance number should be locked. "@"
> ```

This will make it **much** easier for the users to use. Sometimes they are interested in the full Name, sometimes the instance number and sometimes the Identifier. Sometimes they want to lock the identifier and sometimes they want to unlock it to be renumbered in FEM-Design. 

Please let me know if you want to discuss this :)

**Comment by xRadne** [comment]
Like this maybe?
```C#
public string Name
        {
            get
            {
                return _name.Replace("@", "");
            }
            set
            {
                _name = value;
            }
        }
        public string Identifier
        {
            get { return _name.Substring(_name.IndexOf(".")); }
            set { }
        }
        public bool LockedIdentifier
        {
            get
            {
                return _name.StartsWith("@");
            }
            set
            {
                if (value && !_name.StartsWith("@"))
                    _name = "@" + _name;
                else
                    _name = _name.Replace("@", "");
            }
        }
```

**Comment by Marco-Pellegrino** [comment]
@xRadne 
I am trying to understand the "lock", "unlock" numbering but I can not see any effect when done through the "@" letters.
I am still able to "change the numbering" when imported from .struxml with or without the "@".

**Comment by xRadne** [comment]
To be honest I don't fully understand this either.

But here is what I know:
1. Draw 3 bars in FEM-Design: (They will be named B.0, B.0, B.0)
1. Save the file as struxml: (They will be renamed to B.1, B.2, B.3)
1. Read the model using the API: (Still named B.1, B.2, B.3)
1. Add another bar to the model (The 4 bars will be named B.1, B.2, B.3, **B.1**)
1. Open the model in FEM-Design (They will be renamed to B.1, B.2, B.3, B.4) 

Note that the bar added in step 4 will now be named **B.1**, while the bar originally named B.1 is now named B.2 etc.

**Comment by Marco-Pellegrino** [comment]
thanks @xRadne 
I do have a better path to follow :)
I'll do some test and let you know.

**Comment by xRadne** [comment]
I usually have problems with this when I have 2 models with some elements in both models and some elements only in 1 of them and doing analysis and reading results from both models. 

I don't know if this helps

**Comment by Marco-Pellegrino** [comment]
Other thought:
For some object such as load, sections and materials, we are using `Identifier` to describe their Name and it might be confusing (I am confused as well)

We are currently using Identifier to describe the total name for elements as Bar, Panel and we should keep it in the way it is.

However, I do agree in:
public int Instance,
public string Prefix ((instead of Identifier?)

**Comment by xRadne** [comment]
> For some object such as load, sections and materials, we are using `Identifier` to describe their Name and it might be confusing (I am confused as well)

Loads don't have a Name/Identifier. 

Sections used to be called Name? (But were recently changed https://github.com/strusoft/femdesign-api/commit/4d4fc5db7f624bec8771daa0267bff5f1926f614)

I think the problem is we use `EntityBase` for everything.

> However, I do agree in: public int Instance, public string Prefix ((instead of Identifier?)

I think Prefix is too generic. It's better to use `Identifier` since that is the name that FEM-Design is using. 
![image](https://user-images.githubusercontent.com/32938476/191018240-5d99150a-8f0a-4766-a57e-eb4f9b043e11.png)

_Maybe_ call it `int PositionNumber` instead.

**Comment by xRadne** [comment]
> If we need to keep the ".1", it will not be possible to create a `public int Instance`

The ".1" is at the `bar_part`, or `slab_part`. Currently these classes are also an `EntityBase`. But I really think they should **not** inherit from `EntityBase` for this reason. 

I know this issue probably is a really tricky and potentially huge task. But I think it will improve the structure for C# developers and ourselves.

**Comment by xRadne** [comment]
This is how I imagine it. Please tell me what you think :)

Classes | Base class | Properties
--- | --- | ---
Bar, Shell, Support, ... | EntityBase | Name, Instance, Identifier, LockedIdentifier
BarPart, SlabPart, ... | - ** | Name, Instance*, Identifier, Suffix (`".1"`), LockedIdentifier
Loads | LoadBase ** | Name
LoadCase | - ** | Name
LoadCombination | - ** | Name
LoadGroupPermanent, LoadGroupTemporary | LoadGroupBase | Name ***

*Instance number should be the same as for Bar/Shell. 
**Should not be EntityBase any more.
***Don't know if a LoadGroup can have a name in FEM-Design

**Comment by Marco-Pellegrino** [comment]
Okay!
Name should be use only in Slab_part Constructor and not in Slab then.

There is a small Bug in the Slab Constructor as it is using the same name as the slab part

**Comment by xRadne** [comment]
> Okay! Name should be use only in Slab_part Constructor and not in Slab then.
> 
> There is a small Bug in the Slab Constructor as it is using the same name as the slab part

Oh, I realize now that the `<bar name="B.1">`-name attribute does not do anything in FEM-Design... 😅

**Comment by Marco-Pellegrino** [comment]
I'll create a new issue regarding `refactoring` and `inheritance` because it require way more time/resources as the simple renaming to be consistent throught the code.

**Comment by andosca** [comment]
#511
