### ISSUE TITLE
AdvanceFem in model.deconstruct

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#829]
https://femdesign-api.discourse.group/t/advancedfem-elements-in-the-model-deconstruct-component/26

**Comment by lorinczandrea** [comment]
Things to do:

- [ ] Add ModellingTools (AdvancedFem) to Model.Deconstruct as output
- [ ] Create ModellingTools.Deconstruct
- [ ] Create SurfaceConnection 
- [ ] Create SurfaceConnection.Deconstruct
- [ ] Create PointConnection.Deconstruct
- [ ] Create LineConnection.Deconstruct
