### ISSUE TITLE
Missing stability results after RunDesign

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#839]
After defining the FEM-Design.RunDesign component in the pipe workflow, the stab. results disappear. Only the load case and combination and design results are available, therefore GetStabilityResults comp. will fail.

**Comment by Marco-Pellegrino** [comment]
![image](https://github.com/strusoft/femdesign-api/assets/53620289/71c8b83c-d180-4987-993a-48014acd8383)

The user is prompted to run a new analysis to validate the results with the new sections.

Do you have a .gh script that show the issue?

**Comment by Marco-Pellegrino** [comment]
automatic routine has been implemented within Application.Run.
In case of design settings, the component will automatically trigger a new analysis
