### ISSUE TITLE
Add warning message to Analysis.Define

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#849]
When running a stability analysis without declared load combinations, an error occurs in FD.

![image](https://github.com/strusoft/femdesign-api/assets/107181445/34ce9130-e22a-4838-911d-8de82c1786cc)

Warning message should occur in the Analysis.Define component when calculation parameters related to the specified analysis type are missing.

![image](https://github.com/strusoft/femdesign-api/assets/107181445/40574c66-65a2-4f02-856a-632815bebec4)

**Comment by Marco-Pellegrino** [comment]
The user will get a windows with some fortran run-time error and an "unknown error" raise by fem-design via grasshopper.

![image](https://github.com/strusoft/femdesign-api/assets/53620289/5fa52ff6-722c-45cb-9384-3d1bd0184397)
