### ISSUE TITLE
RC Design - Concealed bars

### ISSUE THREAD

**Issue by Tomasz-Gniady** [strusoft/femdesign-api#869]
Create a new option, where user is able to add concealed bars using grasshopper FEM Design API.
![image](https://github.com/strusoft/femdesign-api/assets/147611563/02a0f72d-79e8-429b-89ae-2aa09984da70)

**Comment by Marco-Pellegrino** [comment]
@Tomasz-Gniady 
Concealed bar will be available in 22.9.0 version :)
