### ISSUE TITLE
Comb.Define & Comb.Settings rename suggestion

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#884]
I think less advanced users would find these commands easier in FD if we used similar names for the GH components. 

![image](https://github.com/strusoft/femdesign-api/assets/107181445/32dbee0a-0ea0-4339-a1b6-047f7f09e854)

![image](https://github.com/strusoft/femdesign-api/assets/107181445/bb9280d2-b45a-402d-99fd-1e459c7cde16)

**Comment by lorinczandrea** [comment]
I just noticed that we also have a `LoadCombination.SetupCalculation` component:

![image](https://github.com/strusoft/femdesign-api/assets/107181445/5c3ecf8f-09f3-4716-b2fd-dd6042937a16)

As far as I can see, there is no component with input `Comb.Settings`. If I am not mistaken it should be an obsolete.

**Comment by Marco-Pellegrino** [comment]
@lorinczandrea 
LoadCombination.SetupCalculation should become Obsolete as we have refactor the code to apply the settings in the calculation part of the code.
