### ISSUE TITLE
ReadResult from File

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#889]

**Comment by Marco-Pellegrino** [comment]
@johannariad 
I can not reproduce the bug. Can you please provide an example?
I remember you were getting an error such as:
"The model does not contain any results"

**Comment by JRiad** [comment]
![image](https://github.com/strusoft/femdesign-api/assets/89396751/f52611ee-c7b6-4846-befe-8a1235543f92)

**Comment by Marco-Pellegrino** [comment]
can not reproduce
