### ISSUE TITLE
Incorrect component parameter description

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#897]
incorrect component parameter description:

![d7fa659b-ce37-426e-b197-5955257091c8](https://github.com/strusoft/femdesign-api/assets/107181445/d53a79b5-63f6-4d37-87d7-e176f55edbb8)

Correct: + is tension, - is compression

**Comment by Marco-Pellegrino** [comment]
A better way to describe the direction can would be "elongation" and "contraction".

Hovever, for most of the user, 
+ compression
- tension
should give a good idea on the direction of the applied force.

![image](https://github.com/strusoft/femdesign-api/assets/53620289/3bbd2214-72fa-4573-bd40-cd4be69b2622)
