### ISSUE TITLE
Model input parameter placements

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#9]
Review input parameters. The amount of input parameters will grow as features are added. 

https://github.com/strusoft/femdesign-api/blob/71ef4cce6d0aba528d1d74cefdfcbdfaa780c8ad/src/Model/Model.cs#L2334-L2346

https://github.com/strusoft/femdesign-api/blob/71ef4cce6d0aba528d1d74cefdfcbdfaa780c8ad/componentsGrasshopper/Model/ModelCreate.cs#L16-L41

Analogy for "AddElement methods".

**Comment by andosca** [comment]
Some options:

- Use untyped input parameters. This requires IGH_Goo casting to be implemented for GH.
- Group input parameters before assembling the Model.
- Use basic/advanced constructors:

https://github.com/strusoft/femdesign-api/blob/71ef4cce6d0aba528d1d74cefdfcbdfaa780c8ad/componentsGrasshopper/Bars/BarsBeam.cs#L18-L30

https://github.com/strusoft/femdesign-api/blob/71ef4cce6d0aba528d1d74cefdfcbdfaa780c8ad/componentsGrasshopper/Bars/BarsBeamSimple.cs#L18-L30

**Comment by xRadne** [comment]
I have just added some functionality to the Model class with this commit: 12d8f46e637cfa95dc8841d4f3838a2cb277502b .

`AddElements` will take a list of any structural elements (bars, shells, slabs, supports, fictitiousbars, ConnectedLines etc.) and add them.
`AddLoads` will take a list of any load objects and add them. 

https://github.com/strusoft/femdesign-api/blob/42b01daf8f9047e29aa2f8e6a0c0b3778b3523b2/FemDesign.Core/Model/Model.cs#L2003-L2024

**Comment by xRadne** [comment]
@andosca What do you think about model input placement? What should we do about this before release of version 20.1.0?

**Comment by andosca** [comment]
We should fix this before release. Basically I wan't to get rid of these:

https://github.com/strusoft/femdesign-api/blob/089670705ef4b70f2e53cba041d27e91e77a0a78/FemDesign.Dynamo/Dynamo/Model/Model.cs#L66-L97

We could possibly leave the old constructor as you propose. Then I think we should create either of alternative 1 or 2. I would opt for alternative 1.

![bild](https://user-images.githubusercontent.com/52665994/122878197-c19ebd80-d337-11eb-9b9d-f4a2aa10c2ea.png)

**Comment by xRadne** [comment]
### Grasshopper 
- [ ] Model Create
- [ ] Model AddElements
- [ ] Test script

### Dynamo
- [ ] Model Create
- [ ] Model Add Elements
- [ ] Test script
