### ISSUE TITLE
:bug: GetDefault() returns 0 materials when called from Nuget.

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#93]
https://github.com/strusoft/femdesign-api/blob/8740bea992b8ea410fb70e78151fb53f86c221fc/FemDesign.Core/Materials/MaterialDatabase.cs#L196-L208

1. Nuget has an automatic workflow and materials are not added to the build as they are not public. Throw expection that tells the user why they are not getting any materials and how they can solve this by using DeserializeFromStruxml.

2. Can we solve this for nuget workflow?

**Comment by xRadne** [comment]
For samples to work _out-of-the-box_ we need a way to get materials directly without manually saving to struxml

**Comment by xRadne** [comment]
A simple fix could be by having the user saving materials and sections once in the `%AppData%` folder once. The API could read from this as well as from embedded resources.

**Comment by xRadne** [comment]
> A simple fix could be by having the user saving materials and sections **once** in the `%AppData%` folder. The API could read from this as well as from embedded resources.

@andosca Is this a sufficient solution? 
If the `GetDefault` method returns 0 elements, then we might want to throw an exception stating that the user must add their own materials in that folder?

**Comment by andosca** [comment]
We could add an exception as you say:

`The project was compiled without any materials. Add materials to your project and re-compile or use another method to construct the material database.`

This type of exception goes for section database aswell.

Moreover I think we should consider manually adding major builds to Nuget with materials and sections compiled.

**Comment by andosca** [comment]
Add public FromStruxml methods to material and section databases in C#.

**Comment by andosca** [comment]
@xRadne  Did you add an exception?

**Comment by xRadne** [comment]
Not assigned to me 😉
