### ISSUE TITLE
Python deprecated? Issue after updating to FD22 22.00.005

### ISSUE THREAD

**Issue by twangrt** [strusoft/femdesign-api#957]
After updating to FD 22.00.005 python library example stopped working.

No error logs from python.

Example python scripts launch FD but nothing happens after that.

**Comment by twangrt** [comment]
@Marco-Pellegrino 

I'm using the script example from:

[https://github.com/strusoft/femdesign-api/tree/master/FemDesign.Examples/Python](url)

1.  Python script launches FD 22.00.005, no error log.
2.  Script keeps on running indefinitely.

I'm using Python.NET.

I have used FD Python API before and I had it working with FD 22.00.004 a couple of weeks ago.

I'm just guessing that it has with the update to 22.00.005(changes in core.dll?), but I'll reinstall everything and try again when I have the time.

When are the .dll files going to be updated for FD 23?

**Comment by Marco-Pellegrino** [comment]
I'll try to test the script and come back to you as soon as possible.

Are you also updating the .dll or just using the one in the script folder?

Do you have special characters in your file path?

.dll for FEM-Design 23 are already available:)

Have a look at the latest release.

**Comment by Marco-Pellegrino** [comment]
@twangrt 

Just tried the script with FEM-Design 23 and the latest .dll and it does work (you find them in femdesign.csharp)
https://github.com/strusoft/femdesign-api/releases

I will update the .dll in the python example folder at the end of march.

Meanwhile, have a look at the attached file

[pythonnet.zip](https://github.com/strusoft/femdesign-api/files/14416816/pythonnet.zip)

**Comment by twangrt** [comment]
Thank you. Attached files worked for FD23.

So new compiled cores are attached assets in releases and is not updated regularly in the repo?

**Comment by Marco-Pellegrino** [comment]
@twangrt 
I will need to update the .dll in the python example. It was my bad
I have just forgot to do it as we are not really promoting the use or PythonNet :)

I would like to know more on how you actually use it

**Comment by twangrt** [comment]
No worries. 

Ive done in the past some calculations with construction stages and support displacements to determine the preload on a existing structure.  But that was to much work and would be quicker to do by hand. 

Now I'm thinking of using it to copy loads and loadcases. But i used a regular python script and the in-built export/import loads instead.
