### ISSUE TITLE
Assert bar type in constructor

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#96]
https://github.com/strusoft/femdesign-api/blob/8740bea992b8ea410fb70e78151fb53f86c221fc/FemDesign.Core/Bars/Bar.cs#L164-L173

Consider making all constructors private to force users to use the static methods or rehaul constructors.

Users looking for a "simple" constructor for beams are inclined to use this one as they do not want to define start/end sections and eccentricities.

**Comment by xRadne** [comment]
Users, _including me_, looking for a "simple" contstructor 😂

**Comment by andosca** [comment]
Yes but this constructor will fail to set eccentricity to the `BarPart` and thus if you use this constructor to create any other `BarType `than `Truss` serialization will throw an exception.

**Comment by andosca** [comment]
🐞 This is kind of a bug but not really... 🐛

**Comment by andosca** [comment]
Mostly fixed.

Add type assertions to constructors to make sure that correct type is used, e.g.

https://github.com/strusoft/femdesign-api/blob/8387cdb1ee438620727d142bafa231c2d7efd706/FemDesign.Core/Bars/Bar.cs#L274-L280

**Comment by andosca** [comment]
Solved by facade classes for Beam, Column and Truss.
