### ISSUE TITLE
Deconstruct component for results

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#97]
Relates to #92 
Either we do a specific deconstruct component, or we do this special deconstructor only for the results

**Comment by Marco-Pellegrino** [comment]
I would like to propose to have different component for each "result type".
It has never been an issue for me to use different component/method to get the results in Grasshopper.

I would like to have this kind of flow for the Grasshopper Users.

![image](https://user-images.githubusercontent.com/53620289/163978422-f039704f-3b4a-4b06-bdd7-8526dd7b8412.png)

If they try to get some numerical values for a model that it has not been run, we can raise an error/warning saying "have you analysed the model"?

**Comment by xRadne** [comment]
If results should be read using `FemDesign.Model` as input, then we need to know the associated `.str` file for that model. 

    Maybe `FemDesign.Model` should have a field pointing at a file path for an associated `.str` file and one for `.struxml`? I don't know if this is a good idea, but could be worth considering.
