### ISSUE TITLE
Update material library

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#994]
FEM-Design 23 has release plastic properties and our .struxml should have those properties

- update .struxml and place it in OneDrive - StruSoft AB\FD API\Resources
- double check that reinforcement is saved

**Comment by lorinczandrea** [comment]
This is the location from which the rebar material library can be exported:

![image](https://github.com/strusoft/femdesign-api/assets/107181445/6d0481fa-41f4-474b-a7c0-94c5a48e8f99)

![image](https://github.com/strusoft/femdesign-api/assets/107181445/25b2abeb-9149-4e68-8ea4-c1cce12d00b5)
